### ISSUE TITLE
Treeview not toggling

### ISSUE THREAD

**Issue by danielmurray** [atom/tree-view#1000]
![dec-07-2016 11-30-56](https://cloud.githubusercontent.com/assets/1406265/20983986/6034a01c-bc73-11e6-9994-4112dd603f98.gif)

**Comment by 50Wliu** [comment]
Please make sure the tree-view package is enabled in the Settings View.

**Comment by danielmurray** [comment]
It is, I have disabled and re enabled it many times

**Comment by danielmurray** [comment]
I am sure there is something I am doing wrong, could it be that I might have the source installed locally?

**Comment by danielmurray** [comment]
looks like atom is not including the tree view code...
![screen shot 2016-12-07 at 4 04 44 pm](https://cloud.githubusercontent.com/assets/1406265/20992113/f147c2aa-bc96-11e6-8103-56240ea3c825.png)

**Comment by danielmurray** [comment]
found the issue
![screen shot 2016-12-07 at 4 11 46 pm](https://cloud.githubusercontent.com/assets/1406265/20992282/e2f8b578-bc97-11e6-9095-3c17675ee82b.png)

**Comment by danielmurray** [comment]
Holy cow, just found the little bug icon in the bottom right hand corner, WHAT A COOL FEATURE!

**Comment by 50Wliu** [comment]
If you're using Atom 1.12, run `apm uninstall tree-view`.  While that may sound counterintuitive it should fix any further native module issues with tree-view.

**Comment by danielmurray** [comment]
I ran rebuild, would that do it?

**Comment by 50Wliu** [comment]
Yeah it should, but I would still recommend executing the uninstall command.  Bundled packages aren't meant to be installed manually.
