### ISSUE TITLE
Ignoing all sub-folders syntax for .gitignore does not work.

### ISSUE THREAD

**Issue by znaky** [atom/tree-view#1002]
It seems like tree-view is ignoring the folder_x and all files and folders in it when using ``*/folder_x/*/`` kind of syntax in .gitignore file.

But, I think it supposed to ignore only the sub-folders in folder_x.

**Comment by lee-dohm** [comment]
Can you give an example of a directory structure and `.gitignore` file that reproduces the problem?

**Comment by znaky** [comment]
Yes,
.gitignore file has only that line ``*/folder1/*/``. And directory structure is like below;

```
project
│   file000.abc
│   file001.txt    
│
└───folder1
│   │   file011.abc
│   │   file012.txt
│   │
│   └───subfolder1
│       │   file111.xyz
│       │   file112.txt
│       │   ...
│   
└───folder2
    │   file021.znk
    │   file022.txt
```
I expect tree-view to ignore only subfolder1 and its contents, but not file011.abc and file012.txt. 
what i see is that it is ignoring all files and folders under folder1

**Comment by lee-dohm** [comment]
Using Atom v1.12.7 on Mac OS X 10.12.2, I don't see Tree View ignoring any of the files or folders using that `.gitignore` rule:

<img width="627" alt="screen shot 2017-01-01 at 9 50 55 am" src="https://cloud.githubusercontent.com/assets/1038121/21582325/dd1a6c72-d007-11e6-91d7-94786fab9d7c.png">

I took the liberty of adding a second rule to show what an ignored file would look like.

This also matches the output of `git check-ignore -v **/*`:

```
[master][~/Source/test-project] g check-ignore -v **/*
.gitignore:2:should-be-ignored  folder1/should-be-ignored
.gitignore:2:should-be-ignored  folder1/subfolder1/should-be-ignored
.gitignore:2:should-be-ignored  folder2/should-be-ignored
.gitignore:2:should-be-ignored  should-be-ignored
```

From what I see here, there isn't a bug. If you have a file/folder structure, a `.gitignore` file and output of `git check-ignore -v` that doesn't match with what you see in Tree View (that isn't an instance of https://github.com/atom/atom/issues/2203), please let us know and I'll be happy to reopen the issue.
