### ISSUE TITLE
files closable within tree

### ISSUE THREAD

**Issue by Albertc** [atom/tree-view#1003]
Is it possible to add closable icon "x" in the file name? without using "tree-view-open-files" package, like Textmate:

![image](https://cloud.githubusercontent.com/assets/124529/21423574/08e9b9ce-c83e-11e6-8e61-0e72f89bff96.png)

### Steps to Reproduce

1. Launch Atom
1. Open a file
1. Click `X` next to file in Tree View

**Expected:** Open file tab is closed via normal closing behavior

**Comment by miguelcg** [comment]
Pull request is on the way for this enhancement. I just need to figure out how to close a file (Destroy the `TextEditor` I guess) when the `X` icon is clicked... Any ideas about that @lee-dohm ?

**Comment by lee-dohm** [comment]
To be honest, I'm not sure this is something that we're going to want to accept yet. Most of the team is still out for the holidays right now. I've got it on my list of things to discuss with the team when we get back next week.

If you're still curious, I would look at the implementation of the `core:close` command to see how it works.

**Comment by miguelcg** [comment]
Thanks for letting me know @lee-dohm. I have this feature currently working (I'm polishing it) so when it's ready I'll create a pull request and it's up to you and the team to accept it or not. At least people will be able to see the code and add the feature to their own fork if they interested.
What do you think?

**Comment by lee-dohm** [comment]
Sounds good to me. Thanks! :+1:

**Comment by miguelcg** [comment]
No problem @lee-dohm, PR opened as agreed! #1010

**Comment by lee-dohm** [comment]
Thanks very much for the suggestion @Albertc and the work @miguelcg :grinning: I've discussed this with the team and this isn't a feature that we want to add to Tree View. It could probably be implemented as a package that adds the button to Tree View or a fork of Tree View itself.

Thanks again for contributing to Atom :tada:
