### ISSUE TITLE
"Hide VCS ignored files" option should respect .gitignore even if not a git project

### ISSUE THREAD

**Issue by onury** [atom/tree-view#1007]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Hide VCS ignored files" option should support .gitignore file — without checking for actual .git project. If I don't add the project to git, it will not respect the .gitignore file and unwanted files still show in the tree-view.

### Steps to Reproduce

1. Create a TypeScript project without adding it to git 
2. Add .gitignore file to ignore `*.js` and `.map` files 
3. Check tree-view. You'll see these generated files are still visible in the tree-view.

**Expected behavior:** [What you expect to happen]

.gitignore content should be respected and files should be hidden in the tree-view.

**Actual behavior:** [What actually happens]

If the project is not added to git, it won't hide the unwanted files in the tree-view (even if you have a .gitignore file).

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1
MacOS Sierra

### Additional Information

none

**Comment by lee-dohm** [comment]
Thanks for reaching out :grinning:

The meaning of "Hide VCS ignored files" is that they are files that are ignored by a Version Control System. If there is no Git repository, there is no version control system and the setting is meaningless. If you want to ignore files without adding things to a Git repository, you can use the "Ignored Names" setting to define what to ignore and turn on the "Hide Ignored Names" Tree View setting.
