### ISSUE TITLE
Wrong navigation to files in unfolded folders

### ISSUE THREAD

**Issue by believer-ufa** [atom/tree-view#1020]
Sorry, i really misunderstand it.

1. Unfold one of folders in tree
2. Go down to file below unfolded foder
3. Try to go up
4. Cursor will be active on unfolded folder name. 

**Expected behavior:** cursor will go to last file in unfolded folder

**Actual behavior:** cursor will go to unfolded folder name

**Reproduces how often:** always with folders in root of project?

### Versions

I see this behaviour in last years of Atom editor.

**Comment by AndreaGriffiths11** [comment]
I'm unable to reproduce this using Atom v1.13.1 on Mac OS X 10.12.3. Could you please let us know what version of Atom were using when experiencing this error.

**Comment by AndreaGriffiths11** [comment]
Here's how I tried to reproduce this:

1. Launch Atom in my local atom repository
1. Single-click the `exports` folder to expand it
1. Press the down arrow key three times
1. Press the up arrow key three times

**Expected and Actual:** Selected item highlight is on the `exports` folder

**Comment by believer-ufa** [comment]
Im using Windows and Ubuntu machines, and this bug exists on both of theirs.

**Comment by believer-ufa** [comment]
Please check this video: https://youtu.be/dxR8IDSMEeA

Windows 7

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by synthetiv** [comment]
The scrolling in the video linked above is really too fast for someone who's never noticed this issue to see the problem, but I've had this happen too.

![Screenshot](https://content.screencast.com/users/synthetiv/folders/Jing/media/1cdc8cdd-bbe1-416a-bd5c-26578d475387/00000022.png)

## Repro Steps

1. Find or create a directory (let's call it dir A) whose last child item as ordered by tree-view is also a directory (dir B). Dir B must contain at least one item.
2. Expand dirs A and B in the tree view.
3. Highlight the next file/folder on the same level as dir A (i.e. two levels up from the contents of dir B).
4. Dispatch core:move-up.

**Expected:** Last child of dir B is highlighted.
**Actual:** Dir B itself is highlighted.

## Versions

* **Atom:**       1.16.0
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.12.3
* **Misc**
    * apm  1.16.1
    * npm  3.10.5
    * node 6.9.5 x64
    * python 2.7.13
    * git 2.11.0

**Comment by rsese** [comment]
Thanks again for the report everyone - going to go ahead and close in favor of #1261 since the issue body is more fleshed out.  @synthetiv I've made a note to bring up your pull request with the team :bow:
