### ISSUE TITLE
Tree-View Closed When Opening Folder

### ISSUE THREAD

**Issue by mikebronner** [atom/tree-view#1023]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom used to show the TreeView automatically when opening a folder (CMD-SHIFT-O). It no longer seems to do this since the last one or two Atom updates.

### Steps to Reproduce
1. Close all windows in Atom.
2. Open a project / folder using CMD-SHIFT-O or just CMD-O.
3. Select the project folder you want to work in, and click open.
4. Notice that the tree view does not display automatically, but has to be toggled on.

**Expected behavior:** [What you expect to happen]
I would expect the tree-view panel to show automatically when opening a project, or even just editing a file.

**Actual behavior:** [What actually happens]
The tree-view panel needs to be toggled on manually.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1

**Comment by ajoslin103** [comment]
I would prefer that the tree view be closed until I specifically ask for it (I have been disabling it until I want it, rather a bore.)  Perhaps it could be a persistent behavior (remain open if I left it open, closed if I left it closed.) Or perhaps a setting, default open/closed.

**Comment by ajoslin103** [comment]
I would vote for the solution proposed in #689

**Comment by mikebronner** [comment]
Just wanted to provide a quick update: I no longer seem to have this issue under Atom 1.14.x.
