### ISSUE TITLE
Show in Explorer opens My Documents instead of the folder of the selected file

### ISSUE THREAD

**Issue by Ben3eeE** [atom/tree-view#1034]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since https://github.com/atom/tree-view/pull/791/commits/6b6feb3141750addb8bf366366bf052269a4383c right clicking on a file and choosing `Show In Explorer` opens the `My Documents` folder instead of the folder of the selected file.
I mention this commit because if I put a breakpoint on this line in the `tree-view` and run `new BufferedProcess({command, args, stderr, exit})` from the dev tools console the correct folder opens. If I run it with the `options: {shell:false}` argument `My Documents` opens.

### Steps to Reproduce

1. Open Atom from the terminal in the Atom repository. `atom . --safe`
2. Right click on `CONTRIBUTING.md`
3. Select `Show in Explorer` from the context menu

**Expected behavior:** Open folder where my Atom repository is located with `CONTRIBUTING.md` selected.

**Actual behavior:** Opens `My Documents` folder with no file selected.

**Reproduces how often:** 100%

### Versions

`tree-view` 0.213.2 and newer
```
atom --version

Atom    : 1.15.0-dev-f7424ae18 (Electron 1.4 branch)
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
```

Windows 7.

### Additional Information

@damieng @50Wliu

**Comment by damieng** [comment]
I'd say just revert it - having this working is more useful than accurate error detection in this code path.
