### ISSUE TITLE
"Hide VCS Ignored Files" keeps turning itself back on

### ISSUE THREAD

**Issue by thislooksfun** [atom/tree-view#1035]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

I have not checked this because I have as of yet not been able to reproduce it on my own.

### Description

For some as-yet unknown reason, the setting "Hide VCS Ignored Files" occasionally turns itself back on. I have yet to discover a reason behind this, but it is very annoying.

It's worth noting that this has happened at least 2-3 times now, and as I mentioned, I still have no clue what is causing it.

### Steps to Reproduce

1. Unknown. :/

**Expected behavior:** The setting should remain in the user-set state until it is manually clicked.

**Actual behavior:** It occasionally re-checks itself.

**Reproduces how often:** ??(?)%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

$ atom --version
v6.5.0
$ apm --version
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1

macOS 10.12.2 (16C67)

### Additional Information

As a fellow developer, I understand this kind of bug report (it's broken, help), is frustrating and difficult to fix, however I have honestly no idea what is causing it. I am open to running (almost) any tests you can think of, just let me know what I should try, or if you need any more data.

Thanks,
-tlf

**Comment by 50Wliu** [comment]
This is probably because you've been accidentally pressing `i` while the Tree View is focused.  That's the shortcut to toggle the setting.  You can unbind it in your keymap.cson - if, after you unbind it, it still keeps resetting, then please comment here and I'll reopen the issue.

**Comment by thislooksfun** [comment]
....oh. Yeah, that would make sense, thanks.

**Comment by ppo** [comment]
To unbind, add this in `keymap.cson`:

```
".tree-view":
  "i": "unset!"
```
