### ISSUE TITLE
.gitignore and .gitattributes dont hidden

### ISSUE THREAD

**Issue by malyarevich** [atom/tree-view#1045]
### Prerequisites
add git to project

### Description
I want hide my git files but tree-view not actually hide all files

### Steps to Reproduce

1. set flag "Hide VCS Ignored Files" = true
2. go to project folder

**Expected behavior:** [hidden .gitignore and .gitattributes]

**Actual behavior:** [I see my .gitignore and .gitattributes]

**Reproduces how often:** [3/3 100%]

### Versions
atom 1.15.0 x64 release
tree-view 0.214.1
windows 10 Pro x64 

### Additional Information
set "Hide Ignored Names" = true
and folder ".git" was hidden

**Comment by malyarevich** [comment]
This my crutch :
ctrl+shift+p -> pref -> core -> ignored names -> :
add to end ", .git*"

**Comment by 50Wliu** [comment]
Yes, that is the correct way to do it.  Hide VCS Ignored Files will only ignore the files specified _in_ your `.gitignore`, not the `.gitignore` file itself.

**Comment by malyarevich** [comment]
Awful way!))
