### ISSUE TITLE
Need "Sort Files Before Folder" option

### ISSUE THREAD

**Issue by arfordweb** [atom/tree-view#1066]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

I put an X above because this is a feature modification request, not a bug.  I'm fairly certain I understand the existing functionality and what would need to change to get the desired functionality.

### Description
I am currently on version 0.214.1 of tree-view on Mac.

Right now, there are 2 options available for sorting folders and files.

1. Sort Folders Before Files CHECKED
  - Keeps folders and files grouped with each other instead of intermingled
![screen shot 2017-04-11 at 1 30 28 am](https://cloud.githubusercontent.com/assets/1002408/24894186/94fd9318-1e56-11e7-9356-93db2744719f.png)
2. Sort Folders Before Files UNCHECKED
  - Folders and files are in alphabetical order and not grouped, so folders and files are mixed in together.
![screen shot 2017-04-11 at 1 30 16 am](https://cloud.githubusercontent.com/assets/1002408/24894193/a071a234-1e56-11e7-92a5-a4171da617f6.png)

You select between these 2 options with a checkbox, making it an either/or choice.  But a nice third option would be to sort files before folders.  This could be achieved with a dropdown containing 3 options instead of 2.  Or maybe a second checkbox that is disabled when the first is selected.

#### My Use Case ####
I use a folder hierarchy to keep up with a hierarchy of components and sub-components in a UI I'm building.  In doing so, my components contain a few standard files and potentially lots of sub-folders.  When these sub-folders are expanded, it's visually difficult to tell which set of files belong to which of the expanded folders above.

I'd love for the files to be sorted before the folders since the files are associated with the folder that contains them, and would make better sense located directly under the containing filename.

**Comment by lee-dohm** [comment]
Thanks for the submission.

On further reflection, we've decided that we aren't going to be adding any more sorting options for the Tree View nor are we going to be accepting PRs to add them. Thanks very much for the detailed suggestion and specification.

As for your use case, there is [this stylesheet tweak that can make the file/folder connection more obvious](https://www.atom-tweaks.com/users/lee-dohm/tweaks/b5c80678-e8e9-4318-b12d-3aac33c9bbb5). @simurai describes the change here: https://github.com/atom/tree-view/issues/662#issuecomment-166201370

**Comment by arfordweb** [comment]
😞

**Comment by hyrumcarlile** [comment]
If you don't mind a plugin, you could use [tree-view-sort](https://atom.io/packages/tree-view-sort) to sort files first.
