### ISSUE TITLE
Tree View Dock does not respect showOnRightSide flag

### ISSUE THREAD

**Issue by LucasKA** [atom/tree-view#1076]
### Description

Tree View Dock does not respect showOnRightSide flag

### Steps to Reproduce

1. Open Atom Preference
2. Navigate to Tree-View package settings
3. Check "show on right side"

**Expected behavior:** 

Expect the tree view to show on the right side of the main window when that option is selected

**Actual behavior:** 

It stays on the left side

**Reproduces how often:** 

100%

### Versions

1.17-beta3

**Comment by 50Wliu** [comment]
That setting has been removed as you can now _drag_ the Tree View over to the right side.
Simply drag the "Project" header to the right side of the window and over a chevron that should appear once you start dragging.
