### ISSUE TITLE
Atom 1.17.0-beta4 broke "Show on right side"

### ISSUE THREAD

**Issue by webRat** [atom/tree-view#1084]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using the atom beta, "Show on right side" no longer works. I realize I'm using a beta version of atom, but I'm assuming this should be reported before this goes downstream.

### Steps to Reproduce

1. Use atom 1.17.0-beta4
2. click "show on right side"
3. Observe in glory that it's not on the right side.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

It stays on the left side.

**Reproduces how often:** [What percentage of the time does it reproduce?]

No amount of toggling fixes the issue.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by webRat** [comment]
Actually, I completely re-installed atom beta and now I don't even see the option to show on the right side. Has this feature been removed?

**Comment by 50Wliu** [comment]
You can now drag the tree view to the right side, which I think is better UX than a config option :).  Start dragging the "Project" header over to the right and over the chevron that should appear.

**Comment by webRat** [comment]
Is this documented anywhere? :|

**Comment by 50Wliu** [comment]
No, because it's still in beta.  We'll most likely add documentation when the feature reaches the stable channel.

**Comment by webRat** [comment]
Thanks again for your patience. That documentation is pretty important. 👍

**Comment by 50Wliu** [comment]
Just wanted to check in and say that we now have a FAQ about this: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762

**Comment by caseywatts** [comment]
I just updated to atom 1.17 (it's out of beta as of today! 🎉 )

Here's what my experience with this upgrade was like - this might help determine where to update documentation etc? :)

- I tried right clicking the pane for an option to move it to the right (no such option) - or for the name of my filesystem package.
- I googled until I figured out that `tree-view` is the name.
- Went to settings for `tree-view` and looked through settings. See that `Show on Right Side` is still checked. Tried checking and unchecking it a bunch; tried restarting atom.
- Googled more
- Ended up on the old issue https://github.com/atom/tree-view/issues/786 (that issue will link to this one now, and that'll help some!)
- searched the `tree-view` github issues for `right side`, and found this issue 🎉 
- dragged to the right once and it didn't work
- watched the GIF in @50Wliu 's [FAQ entry](https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762)
- dragged to the right again, hovered over the drawer expansion icon, and then dropped it in the spot - success! (I'm glad I read the [release notes for 1.17](http://blog.atom.io/2017/05/16/atom-1-17.html) for once so I knew what a dock was lol)


Here's @50Wliu 's gif (from discuss.atom.io):
![a042f3ce0d521de104024a3c8532fb6e09d636c1_1_690x467](https://cloud.githubusercontent.com/assets/273653/26127753/42e4c736-3a58-11e7-98e6-e8c25496f4a5.gif)

**Comment by 50Wliu** [comment]
Minor correction: that's @lee-dohm's GIF, not mine :smile:.  Thanks for the feedback; I'll pass it on to him and see if we can improve the experience.

**Comment by Bleeky** [comment]
Hi guys,
Is there still a way to save your configuration for the sidebar position ? The drag and drop doesn't seem to change anything to the config file.

**Comment by 50Wliu** [comment]
It should automatically save the state without writing anything to your config file.  If it does not, please open a new issue on atom/atom.

**Comment by kramse** [comment]
Sad it disappeared, since I have Atom quite a few places, so have to go through all of these - and took some time to find this. Still a great editor, so thank you!

Where IS the state saved then? I might be able to copy that to other places?

**Comment by 50Wliu** [comment]
Unfortunately, I'm not familiar with how/where it gets saved, I just know that it _does_.  You might have some better luck asking on [Slack](http://atom-slack.herokuapp.com/).

**Comment by Leehman** [comment]
In my atom ide 1.17 I only have 1 draw button on the left. How do I configure the right side draw?

**Comment by Leehman** [comment]
It worked as you stated.

**Comment by ankitsinghaniyaz** [comment]
I'm facing a weird problem. I move the tree view to the right but on a restart, it is back to the left. It used to remember in the older versions. Anyone else facing this?

I'm on Atom 1.27.1
