### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

### ISSUE THREAD

**Issue by romikoops** [atom/tree-view#1091]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.215.1

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/directory-view.js:17

TypeError: Cannot read property 'onDidDestroy' of undefined
    at /app.asar/node_modules/tree-view/lib/directory-view.js:17:44)
    at /packages/tree-view-bundler/lib/tree-view-bundler-view.coffee:68:17)
    at /packages/tree-view-bundler/lib/tree-view-bundler.coffee:38:29
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

### Commands

```
  2x -3:19.1.0 core:copy (atom-pane.pane.active)
```

### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-protocol-buffer 0.2.0 
linter-swift-package-manager 0.1.0 
linter-ui-default 1.2.4 
native-ui 0.20.6 
path-copy 0.14.0 
phoenix-migrations-navigation 0.7.4 
phoenix-snippets 0.5.0 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.3 
rails-model-schema 0.9.0 
railscasts-theme 1.4.0 
ruby-block-converter 3.5.0 
ruby-test 1.0.2 
ruby-turnip 1.1.0 
screen-recorder 1.2.3 
swift-debugger 0.1.2 
sync-settings 0.8.1 
tree-view-bundler 0.0.3 
webbox-color 0.5.9 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by romikoops** [comment]
I fixed the problem by removing all atom user settings and restoring via sync_settings plugin. I guess it was my fault, because I removed part of files in my user folder by mistake from terminal

**Comment by misterbridge** [comment]
I've this issue by using an other package: https://atom.io/packages/temporary-root
There a discussion about this being a required feature for tree-view: https://discuss.atom.io/t/double-click-on-folder-structure/6235

When I use this other package, the "Enter" action does not work, and I get this error.

**Comment by rsese** [comment]
Thanks for opening an issue in the temporary-root package @misterbridge.  It may be that there is still a bug in Atom and if so, we'll need the maintainer of the package that is causing the problem to help track that down.  They can then either fix the problem or tell us where the problem is coming from.

**Comment by misterbridge** [comment]
Yup that's why I've create the issue with details here and created at the same time an issue with a link to this one on temporary-root package :)
(https://github.com/wasikuss/temporary-root/issues/2)

**Comment by wasikuss** [comment]
problem with `onDidDestroy` in `temporary-root` (already fixed) and `tree-view-bundler` is connected to update of `tree-view v0.214.1 -> v0.215.0`.

**Comment by misterbridge** [comment]
Thanks guys !

**Comment by sss-hnguyen** [comment]
Uninstalling highlight-selected fixed it for me.
