### ISSUE TITLE
Tree view forgets about open files while moving or renaming a directory

### ISSUE THREAD

**Issue by hugollm** [atom/tree-view#1093]
If you move or rename the directory of an open file, Atom starts to think it's a new file, since it doesn't know it was moved. It's annoying because it causes duplicate files to be created (if you save the file by mistake) or waste your time with pointless popups ("are you sure you wanna discard this?").

The tree view should update open files when directories are renamed or moved. At the very least, it should close the saved tabs, to avoid duplicates and popups.

Reproduced in Atom version: 1.16.0 (xubuntu x64) - safe mode

1. Open a file inside a directory in the tree
2. Rename or move the directory
3. Try to close the tab

The problem will happen every time you do this.

Obs: since I bump into this issue so often, I was expecting an issue to be already open about this. Since I couldn't find it, I'm posting this. My apologies if it's a duplicate.

**Comment by hugollm** [comment]
UPDATE: this was fixed in 1.17 \o/
You can close this.

**Comment by 50Wliu** [comment]
Awesome, thanks for the update!
