### ISSUE TITLE
"show on right side" don't work in atom 1.17.0

### ISSUE THREAD

**Issue by qoli** [atom/tree-view#1094]
Using: Atom 1.17.0
Theme: One Dark

![2017-05-17 12 52 23](https://cloud.githubusercontent.com/assets/2818670/26118060/1d2b19d0-3a9b-11e7-952d-420bf01e0a30.png)

**Comment by 50Wliu** [comment]
The Show on Right Side config option has been removed in favor of the new Docks feature.  Simply drag the Tree View to the right side of the editor and a chevron should show up - move the Tree View onto the chevron to place it on the right side of the editor.

**Comment by in-in** [comment]
Still not working for me. By the way, what is a chevron?
Maybe because I'm on a Linux Mint system? Should I open a new issue for a specific Linux?

**Comment by 50Wliu** [comment]
Here's a GIF:
![drag-tree-view](https://cloud.githubusercontent.com/assets/2766036/26120017/648f0ec0-3a3d-11e7-9d28-ae956603a653.gif)

If it still doesn't work, you may need to open a new issue and we'll triage it further.

**Comment by in-in** [comment]
Thank for GIF
In my case, second(right) chevron doesn't appear

**Comment by in-in** [comment]
@50Wliu I lost this panel, can you tell where I can find it?
![c2894](https://cloud.githubusercontent.com/assets/8797432/26222564/20c75f66-3c23-11e7-9de7-1f740ae3fd67.png)

Now it looks like this
![dd0e0](https://cloud.githubusercontent.com/assets/8797432/26222587/48cfb6e8-3c23-11e7-9e27-ff46b3618196.png)

**Comment by in-in** [comment]
I found this
That checkbox should be active then "Project" tab is visible.
Atom force me to use tabs it is weird :confused:
![4d2e5](https://cloud.githubusercontent.com/assets/8797432/26222989/d29d9268-3c24-11e7-8fd8-1c13a9e41367.png)  

Of course, this issue is related to tabs package
