### ISSUE TITLE
After upgrading to 1.17 it's impossible to move to the right

### ISSUE THREAD

**Issue by davidbarratt** [atom/tree-view#1097]
I can't seem to move the tree view to the right in Atom after upgrading to 1.17.

I found #1076 but at least on MacOS the pane is not draggable, or if it is dragging, it is not moving.

**Comment by BrunoBernardino** [comment]
I had this issue but was able to drag. I did have tabs open, not sure if that played a part in it.

**Comment by davidbarratt** [comment]
oh! I finally got it! you have to drag it onto the little "dock" arrow that appears. whew... good thing it was user error, but it would help if the target was a bit bigger.

**Comment by Igor10k** [comment]
@davidbarratt thanks for describing your experience, I didn't notice the arrow too.

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762
