### ISSUE TITLE
Tree view on wrong side in Atom 1.17.0

### ISSUE THREAD

**Issue by 03l54rd1n3** [atom/tree-view#1098]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Even when toggling the side setting for the tree view, it keeps sticking to the left.

### Steps to Reproduce

1. Update Atom to 1.17.0
2. See how the side setting doesn't work anymore

**Expected behavior:** side should change

**Actual behavior:** side doesn't change

**Reproduces how often:** 100%

### Versions

1.17.0 on Win10, no creators update

### Additional Information

It works when pulling the whole tree view to the other side, though.

**Comment by epilektric** [comment]
For anyone landing here because their tree view is on the left side, follow this link and scroll down to the animated GIF explaining how the drag and drop functionality works.
[https://github.com/atom/tree-view/issues/1084](https://github.com/atom/tree-view/issues/1084)
