### ISSUE TITLE
Tree View No longer shows on right side

### ISSUE THREAD

**Issue by koush** [atom/tree-view#1101]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tree View No longer shows on right side

### Steps to Reproduce

1. Use the "Show On Right Side" setting in Tree View Settings.

**Expected behavior:** Tree View is on the right side.

**Actual behavior:** Tree View stays on the left side.

**Reproduces how often:** 100%

### Versions
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0

**Comment by koush** [comment]
Ok, apparently you can do this now to move it: 
https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762

But the settings no longer work.

**Comment by 50Wliu** [comment]
The setting was removed in favor of the drag-and-drop functionality.

**Comment by koush** [comment]
The setting still exists. As do the various application level menus. None of those work. Currently only drag and drop works.

**Comment by 50Wliu** [comment]
They have been removed; Atom just has no way of telling which settings are valid, so it displays all of them.

**Comment by inoas** [comment]
Drag and drop doesn't work for me

**Comment by inoas** [comment]
Well... it doesnt work on maximized windows on the main monitor when on the right side there is another monitor, in os x - *good lord*...

**Comment by rsese** [comment]
Oh looks like you found one of the newer issues since the introduction of docks @inoas (I just replied to you in https://github.com/atom/tree-view/issues/786#issuecomment-335487726).  So it sounds like it works for you but not in the particular case you mentioned.

Can you open a new issue for that and fill out the issue template so we can take a look and try to reproduce?
