### ISSUE TITLE
Tree-View controlling commands

### ISSUE THREAD

**Issue by alexmattson** [atom/tree-view#1105]
With my Tree-View package enabled I am unable to edit a file. Also, it treats it as if I am using the shortcuts for the Tree-View. I.e. if I press 'a' it treats it as command+a and tries to create a file. 

If I disable the package I am able to work in the files again as if nothing is wrong.

Here is my list of community packages in case there are any known conflicts.
```
Community Packages (51) /Users/amattson/.atom/packages
├── Sass-Syntax-Highlight@0.1.1
├── angularjs@0.4.0
├── angularjs-snippets@0.10.18
├── atom-typescript@11.0.3
├── autocomplete-modules@1.6.10
├── autocomplete-paths@1.0.5
├── autoprefixer@3.7.0
├── busy-signal@1.4.1
├── chester-atom-syntax@0.1.1
├── cobalt2-syntax@0.5.1
├── color-picker@2.2.5
├── copy-path@0.4.1
├── docblockr@0.9.4
├── editorconfig@2.2.2
├── emmet@2.4.3
├── es6-javascript@1.0.0
├── file-icons@2.1.6
├── git-blame@1.1.0
├── highlight-line@0.12.0
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── javascript-snippets@1.2.1
├── js-refactor@0.7.5
├── language-babel@2.61.0
├── language-javascript-jsx@0.3.7
├── linter@2.1.4
├── linter-eslint@8.1.7
├── linter-ui-default@1.5.4
├── markdown-scroll-sync@2.1.2
├── markdown-writer@2.6.5
├── merge-conflicts@1.4.5
├── mighty-react-snippets@1.0.1
├── minimap@4.28.2
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── minimap-selection@4.4.0
├── oceanic-next@1.0.0
├── oceanic-reef-syntax@0.6.0
├── open-recent@5.0.0
├── pigments@0.39.1
├── pretty-json@1.6.3
├── react-snippets@0.7.2
├── redux-snippets@0.2.2
├── refactor@0.11.4
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── synced-sidebar@0.4.3
├── toggle-quotes@1.0.1
├── tree-view-copy-relative-path@1.1.0
├── uglify@1.3.1
└── unity-ui@2.1.8
```

### version 
```
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

```

**Comment by house9** [comment]
I just encountered the same exact thing after atom updated from 0.16.0 to 0.17.0

Reverting atom to 0.16.0 and everything is fine. 
Disable the tree-view package in 0.17.0 and files are editable.

**Comment by house9** [comment]
I just narrowed the issue down to the `synced-sidebar` package, disable that and everything works again!

**Comment by sharkweek** [comment]
I don't have the the synced-sidebar package, but turning off the "Focus on Reveal" option in the tree-view package worked for me on both 1.17 and 1.18-beta.

https://discuss.atom.io/t/cant-edit-files-when-i-open-up-a-project-folder/42832?u=sharkweek
