### ISSUE TITLE
Option to hide "Project"?

### ISSUE THREAD

**Issue by danqing** [atom/tree-view#1108]
I'm not sure if this repo is the best place to ask, but since Atom 1.17 there's a "Project" line above the folders. Is there a way to hide it? I don't know what it is there for or if it can be anything other than "Project", so I may be missing something here, but I can't see much value of it and would like to hide it if possible.

Thanks!

![screen shot 2017-05-18 at 8 34 50 pm](https://cloud.githubusercontent.com/assets/5134133/26232203/76983826-3c09-11e7-8e1b-c5bb5dc80641.png)

**Comment by in-in** [comment]
It depends on tabs package.
Look at my last comments here https://github.com/atom/tree-view/issues/1094

**Comment by danqing** [comment]
Oh sweet. So simply uncheck "Always show tabs" removes it. Thanks @in-in !

**Comment by in-in** [comment]
But now you can not drag it ¯\_(ツ)_/¯

**Comment by danqing** [comment]
haha, I never drag it so it's fine ;)

**Comment by stevenwanderski** [comment]
@in-in Unchecking "Always show tabs" in the `tabs` package also hides the currently open file tab if only one is open. Is there a way to _only_ hide the "Project" tab (in the tree view) if its the only tab open?

**Comment by in-in** [comment]
Sorry, I don't know.
I'm even don't use tabs. This package completely disabled in my editor.

**Comment by stevenwanderski** [comment]
This seems to hide it:

```css
atom-dock .tab-bar {
  display: none;
}
```
