### ISSUE TITLE
Background is not completely filled

### ISSUE THREAD

**Issue by susisu** [atom/tree-view#1110]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When tree view's width is smaller than its content width, the background (including selected item highlight) is not completely filled.

### Steps to Reproduce

1. Show the tree view (by opening some project)
2. Make tree view's width smaller than its content width
3. Scroll horizontally

**Expected behavior:**
Background should be completely filled.

**Actual behavior:**
Background is not completely filled, like this:

<img width="154" alt="2017-05-19 18 13 19" src="https://cloud.githubusercontent.com/assets/2443491/26241255/f7e91110-3cbe-11e7-8753-a1026dce4a07.png">

**Reproduces how often:**
100%.
This happens for any themes.

### Versions
```
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

tree-view version: 0.217.0-7

**Comment by rsese** [comment]
Thanks for the report! 

> 100%.
> This happens for any themes.

Hmm, I do see that gap with Atom Light and Dark but not with the One themes e.g.:

![one-light](https://github-slack.s3.amazonaws.com/monosnap/hello.rb__sandboxhello-world_2017-05-19_13-30-24.png)

Do you see differently with the One themes?

**Comment by Cthulahoop** [comment]
I'm seeing the same issue, and it's true for all themes including the One themes. In your image, you need to scroll the list horizontally to see that the highlight element is rendered only as wide as the dock element. I think the ol.full-menu element is where the truncation happens, but not positive on a fix.
![screen shot 2017-05-19 at 1 48 01 pm](https://cloud.githubusercontent.com/assets/5263654/26268119/85395402-3ca2-11e7-9a13-208b55544d4b.png)

**Comment by susisu** [comment]
@rsese As said above, if you scroll horizontally, you can see this also happens for the One themes.
(Maybe my screenshot was not good, sorry.)

![atom-tree-view-glitch](https://cloud.githubusercontent.com/assets/2443491/26271051/f276ea40-3d3b-11e7-83a3-2cfbc59dca50.png)

There was `.tree-view-scroller` element in the old versions, from which the background width is inherited.
In the latest version, there is no such wrapper element.
This is why I said the problem can happen for any themes.

**Comment by simurai** [comment]
> @susisu There was `.tree-view-scroller` element in the old versions

Right. Probably happened during the "move into docks": https://github.com/atom/tree-view/pull/1056

To make the selection expand, we might can add another wrapper that acts the same as `.tree-view-scroller`. I'll take a look.

**Comment by rsese** [comment]
Weird, though my screenshot wasn't scrolled I'm almost positive I didn't see that gap but I do now - thanks for the clarification @Cthulahoop @susisu :bow: and thanks for the 👓  @simurai 🙌

**Comment by thetomja** [comment]
+1
