### ISSUE TITLE
"Show on right side" option doesn't show tree-view on the right side

### ISSUE THREAD

**Issue by haidran** [atom/tree-view#1116]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When enabled, "Show on right side" setting doesn't move (as it did on previous version) the tree-view to the right side, it remains on the left.

### Steps to Reproduce

1. Toggle "Show on right side" setting.

**Expected behavior:** Tree view changes its position to the right side.

**Actual behavior:** Tree view remains on the left side.

**Reproduces how often:** 100%

### Versions

Atom:

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

APM:

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0

OS: Mac OS Sierra 10.12.5

### Additional Information

-

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762

**Comment by haidran** [comment]
I just read that, sorry. Anyway, if you have the option "Always show tab bar" in Tabs package disabled, this "Project" tab doesn't show, so drag and drop is not possible. IMHO there should be some indication for people like me that had that setting disabled and saw the tree-view stuck on the left side, as there was no hint on how to move it to the right without reading the FAQ.

Thanks.

**Comment by 50Wliu** [comment]
Yeah.  I've already pinged the person who added Docks to see if there's a way to move it without the tab bar.

**Comment by haidran** [comment]
Perfect. In the mean time, I'll enable Always show tab bar when I need to change sides, but I guess it isn't a setting I'll change frequently.

**Comment by Asc2011** [comment]
so two years after - out of the blue - the `tree-view` had hopped to the left side and there is still no solution/workaround/what-so-ever to put it on the right side ?
hmm, that is a like switching the driving lane from right to left :-) a recipe for frontal- or front-end-crashes. Its insane ...
And , yes i've noticed the links to the solution, that does not work on my system : _Out of the frying pan into the fire_ so to say :-)
