### ISSUE TITLE
Click on directory without expanding it

### ISSUE THREAD

**Issue by UziTech** [atom/tree-view#1117]
There should be a way to select a directory without expanding it.

If you want to <kbd>ctrl</kbd> + click on multiple directories when something else is selected you have to click on a directory, which opens, then click on it again to close it, then hold <kbd>ctrl</kbd> and click on the other directories

![right-click-tree-view2](https://cloud.githubusercontent.com/assets/97994/26387205/3c48e394-4011-11e7-9f05-54884564b702.gif)

**Comment by vjpr** [comment]
Duplicate: https://github.com/atom/tree-view/issues/411

**Comment by Ben3eeE** [comment]
Thanks @vjpr
