### ISSUE TITLE
Unable to execute any keyboard events 

### ISSUE THREAD

**Issue by harshattray** [atom/tree-view#1118]
Unable to execute any keyboard events when tree view is enabled in atom . Cannot edit , delete or type anything. The focus persists on the tree-view pane even after the target file is opened  . I have updated to the latest version of atom. Everything works fine once i disable tree-view

Tree view works on safe mode[ atom . --safe  in terminal] but not when i open it normally

**Comment by MeDBejoHok** [comment]
+1

**Comment by harshattray** [comment]
Yup turned  off 'Focus on reveal' and works fine now. Closing the issue . Not sure if its enabled by default and if its enabled then it still doesn't shift focus to the file. Thanks for the fix .

**Comment by 50Wliu** [comment]
In addition, if you have the synced-sidebar package installed, it may be a good idea to uninstall it.  Then Focus On Reveal should work.
