### ISSUE TITLE
tree-view not cooperating "Show On Right Side"

### ISSUE THREAD

**Issue by davnajork** [atom/tree-view#1119]
![screen shot 2017-05-24 at 11 26 52 pm](https://cloud.githubusercontent.com/assets/26757747/26438539/82de8a1c-40d8-11e7-918d-fa53d5899ee2.png)

My tree-view is **not** being displayed on the **RHS** despite my configuration in the settings.

**Comment by Zireael07** [comment]
Duplicate of #1084 

Also you haven't filled out the template...

**Comment by davnajork** [comment]
Very helpful, thanks....
