### ISSUE TITLE
Cannot display on right side of window

### ISSUE THREAD

**Issue by denlinsley** [atom/tree-view#1121]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tree view will not display on right side

### Steps to Reproduce

1. Open a project in Atom
2. In tree-view Settings, check "Show On Right Side"

**Expected behavior:** The tree view displays on the right side of the window

**Actual behavior:** The tree view remains on the left side

**Reproduces how often:** 100%

### Versions
```
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

This seems to have been introduced in a recent update (ever since the expand/collapse caret was introduced).

**Comment by ctcpip** [comment]
I just upgraded from `1.16.0` to `1.17.2` and am now observing this issue.

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762

**Comment by ctcpip** [comment]
@50Wliu Thanks.  Are there plans to remove the 'Toggle Tree Side' menu item since this now has no effect?

**Comment by 50Wliu** [comment]
The setting has been removed from the package and for new installs, but we can't go in and remove it from your config.cson.  Sorry for the confusion.

**Comment by stevenventimiglia** [comment]
So, there's no more right side tree view?  Is there another way to do this?
