### ISSUE TITLE
Adding a keybinding with a '.editor' selector not working

### ISSUE THREAD

**Issue by jdguzman** [atom/tree-view#113]
I tried to add the following binding:

```
'.editor':
  'ctrl-cmd-a': 'tree-view:add-file'
```

This binding didn't work and at the suggestion of kevin​sawicki on the atom discuss forum I'm posting it here as a bug.

**Comment by TPetterson** [comment]
Does this still work? I tried this and nothing happens.
`'atom-workspace':
  'cmd-n': 'tree-view:add-file'`
