### ISSUE TITLE
Key bindings with "\" can be impossible to type on international keyboards

### ISSUE THREAD

**Issue by rocco** [atom/tree-view#114]
A key binding like "Shift-Cmd-\" to reveal an open file in tree view can be impossible to type on e.g. German (and probably on many other) keyboards because we have to type "Shift-Alt-7" to enter a backslash. Internationally compatible key binding defaults would be nice.

Btw. this sucks in the Twitter.app too: "Cmd-\" to show main window, however this is possible with "Shift-Alt-Cmd-7" on a German keyboard... works but not nice.

**Comment by 50Wliu** [comment]
Closing this as a duplicate of atom/atom-keymap#35 and atom/atom-keymap#37, please subscribe there for updates.
