### ISSUE TITLE
Set colour of filename by folder

### ISSUE THREAD

**Issue by steronydh** [atom/tree-view#1141]
Enhancement suggestion: if you have several folders open containing several files, it can be hard to tell them apart. To make it easier to tell files from different project folders apart, could the colour of the folder name and the name of  unaltered files under it have the same colour, and each folder be able to have a different colour?

E.g. instead of uniform grey:
![image](https://user-images.githubusercontent.com/4245329/27689523-5b89ade2-5cd6-11e7-8abd-9631502d6c51.png)
group the file colours by folder:
![image](https://user-images.githubusercontent.com/4245329/27689876-95bdf33c-5cd7-11e7-873a-3411976eadf2.png)

Obviously the colour would have to be (a) subtle and (b) not match the Git colours for altered files.

**Comment by vrgimael** [comment]
Literally looking for this right now. Any updates? Did you manage to get this working somehow?
