### ISSUE TITLE
On open, directory pulls next sibling in-under its children

### ISSUE THREAD

**Issue by zachcoss** [atom/tree-view#1142]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On open, directory pulls next sibling in-under its children. 

![giphy 3](https://user-images.githubusercontent.com/19162337/27767350-feb437fe-5eba-11e7-8cbe-2efb9ee53c49.gif)

### Steps to Reproduce

1. Open a directory with multiple siblings

**Expected behavior:** For only the directories children to indent.

**Actual behavior:** The directories children indent and underneath, the directories sibling.

**Reproduces how often:** 100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.10.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Hmmm, I can't reproduce with Atom 1.18.0 on Windows 10, what operating system are you running?

Also that animation looks interesting, do you have a community package or some custom CSS that does that?

**Comment by zachcoss** [comment]
I'm running Version 1.18.0 on Mac OS 10.12.4.

I just checked the new UI theme I installed called Pristine, and yes there is the issue.
