### ISSUE TITLE
tree-view can't be docked to right side

### ISSUE THREAD

**Issue by nicproject** [atom/tree-view#1145]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrading atom editor to latest stable on 2 July. The tree-view can't be docked to right side.

**Expected behavior:**
When I ticked the 'show on right side', tree view should be on right side

**Actual behavior:** It sits on the left side

**Reproduces how often:**  100%

### Versions

atom 1.18.0 x64
tree-view 0.217.1

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762/1
