### ISSUE TITLE
Can't arrange files the way I want in a project!

### ISSUE THREAD

**Issue by MorrAndSo** [atom/tree-view#1148]
Hi. This may seem like a stupid question but how do I arrange the files in a project the way I want to.
For example I can't seem to be able to move the index.html file at the top of all .js files. 

![help](https://user-images.githubusercontent.com/23421747/27995576-96320d9e-64d9-11e7-8896-656ab73cf7a1.png)

Drag and drop does not seem to work....I feel really stupid -.-

**Comment by rye761** [comment]
Tree-view automatically arranges your files alphabetically.
