### ISSUE TITLE
show on right side has no effect when using tree view with 1.18.0

### ISSUE THREAD

**Issue by sudhindra-glooko** [atom/tree-view#1150]
show on right side has no effect when using tree view with 1.18.0

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762?u=wliu

**Comment by sudhindra-glooko** [comment]
Thanks @50Wliu that worked.
Maybe the 'show on right side' option should be removed then.

**Comment by 50Wliu** [comment]
New installations will not receive the option.  However, there is no mechanism to remove existing config options (the settings are read directly from `~/.atom/config.cson`, so if it was previously set then it'll remain there until you manually remove it).
