### ISSUE TITLE
Tree View captures all keys

### ISSUE THREAD

**Issue by wyqydsyq** [atom/tree-view#1151]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Using OpenSUSE Linux, after a recent update my tree view has been capturing all keyboard events:

![image](https://user-images.githubusercontent.com/621277/28451453-b3be80e4-6e30-11e7-9beb-6525d54bb769.png)

In the example above, I tried typing "d" into the text buffer, but the event was intercepted by Tree-view.

So essentially Tree-view renders the rest of Atom unusable for me.

### Steps to Reproduce

1. Enable Tree view
2. Attempt to enter values into text buffer

**Expected behavior:** Values appear in text buffer

**Actual behavior:** Tree view intercepts the keyboard events

**Reproduces how often:** 100%

### Versions
```
 atom --version                                
aAtom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version                                                 
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.2

```

OpenSUSE Tumbleweed x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
@wyqydsyq your screenshot doesn't look like it was taken in safe mode.  Are you certain that you launched Atom in safe mode?

**Comment by denesalmasi** [comment]
I had the same issue but the keyboard focus was correct in safe mode. (i.e. it worked). So I launched in non-safe mode and started turning off plugins one by one until it started working.

To me the Synced-Sidebar package was causing this issue: https://github.com/TheSpyder/SyncedSideBar

**Comment by jonayreyes** [comment]
I ran into this issue and I was able to solve it by disabling (the now deprecated) synced-sidebar

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/1151#issuecomment-317024112. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
