### ISSUE TITLE
Feature request : File tags in the file tree

### ISSUE THREAD

**Issue by Aarbel** [atom/tree-view#1160]
Hi everybody ! 

I'm working on our file architecture, i need color tags to work faster
Do you know a tree-view plugin that looks like osx tags or any files tags system ?

Here an example :
![image](https://user-images.githubusercontent.com/25119847/29211237-27cf56b2-7e98-11e7-8ec7-8ea23feb2d09.png)

![image](https://user-images.githubusercontent.com/25119847/29211244-33d1f758-7e98-11e7-8d29-2306979f87de.png)

**Comment by 50Wliu** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package. For that reason, I'm going to close this. It sounds like a great idea for an Atom package though. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom :+1:
