### ISSUE TITLE
Files/directories multiple selection by Shift+Click @featurerequest 

### ISSUE THREAD

**Issue by sartatpdev999** [atom/tree-view#1164]
Moved from [#15375](https://github.com/atom/atom/issues/15375)

Hi. It's able to select multiple files/directories by Ctrl+Click. But it's unavailable to select multiple items by Shift+Click. Seems to be useful to release this feature.

Thanks.

**Comment by 50Wliu** [comment]
I cannot reproduce - shift+clicking to select multiple consecutive entries is working fine for me on Atom 1.21.0-dev-962bbd509, Windows 10 x64.

If you are able to reproduce this on the latest version of Atom, then please open a new issue and completely fill out the [issue template](https://raw.githubusercontent.com/atom/tree-view/master/ISSUE_TEMPLATE.md).  Thanks! 🙇

**Comment by sartatpdev999** [comment]
I'm sorry. It's a problem of [remote-ftp package](https://github.com/icetee/remote-ftp/)
