### ISSUE TITLE
When deleting directory with the same name as file (minus extension) file closes in editor.

### ISSUE THREAD

**Issue by sftd** [atom/tree-view#1185]
### Description

When deleting directory with the same name as file (`test-name` and `test-name.js`) file in editor closes (probably thinks it was also deleted).

### Steps to Reproduce

![atom-bug-1](https://user-images.githubusercontent.com/3073859/30801689-564ac6b0-a1e4-11e7-8571-472dbba8ebea.gif)

1. Open directory in atom.
2. Create directory with name `test`.
3. Create file with name `test.js`
4. Open file in editor.
5. Delete directory from tree-view.

**Expected behavior:** Directory gets deleted, file stays open.

**Actual behavior:** Directory is deleted, file is closed.

**Reproduces how often:** Always.

### Versions

Windows 10, 64bit
Atom 1.19.2 x64
Tree-view 0.217.2

### Additional Information

I'm guessing it's a `tree-view` issue not atoms, but might be wrong.

**Comment by 50Wliu** [comment]
This was fixed in #1182 and will be released in Atom 1.22.0.
