### ISSUE TITLE
Toggle tree side does not change sides

### ISSUE THREAD

**Issue by captainbarbosa** [atom/tree-view#1186]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Selecting `Packages > Tree View > Toggle Tree Side` does not cause the tree view to switch to the opposite side.

### Steps to Reproduce

1. In the Atom menu, select `Packages > Tree View > Toggle Tree Side`.
2. Observe the tree view remaining on the original side.

**Expected behavior:** [What you expect to happen]

The tree view should switch to the opposite side.

**Actual behavior:** [What actually happens]

The tree view does not switch to the opposite side.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
$ atom --version
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1
```

MacOS version 10.12.6

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762

**Comment by captainbarbosa** [comment]
@50Wliu thanks for the clarification. Would it makes sense to remove this option in the package's menu bar then? I've also submitted a PR to clarify this in the README file here: https://github.com/atom/tree-view/pull/1187

**Comment by 50Wliu** [comment]
It has been removed, but settings-view will display anything that is already in your config.cson, even if it doesn't match with a known setting.
