### ISSUE TITLE
Renaming a file also renames open files that are similarly named

### ISSUE THREAD

**Issue by jasonrosendale** [atom/tree-view#1188]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you right-click a file in the tree view and select "rename", it will also rename any currently opened files whose paths start with the original file's name.  For example, renaming "lib/foo" to "lib/XXX" will also rename "lib/foo_builder.rb" to "lib/XXX_builder.rb" and "lib/foo/readme.txt" to "lib/XXX/readme.txt".

### Steps to Reproduce

1. Open any project, new or already-existing
2. Choose any arbitrary directory and create three files in it: "foo-file1.txt", "foo-dir/file2.rb", and "foo". Save them.
3. Make sure that the "foo-file1.txt" and "foo-dir/file2.rb" are open in Atom.
4. Rename "foo" to "RENAMED"

**Expected behavior:** 
I expect "foo" to be renamed to "RENAMED", and for the other files to remain unchanged

**Actual behavior:** 
"foo" is renamed to "RENAMED",
"foo-file1.txt" is renamed to "RENAMED-file1.txt",
"foo-dir/file2.rb" is renamed to "RENAMED-dir/file2.rb"

**Reproduces how often:** 
This can be reproduced every time.

### Versions
$ atom --version
apAtom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.12.2
tree-view@0.217.7

### Additional Information
* I was able to reproduce this under tree-view@0.218.0.
* The error also happens if you right-click the file's tab and select "rename"
* This doesn't immediately rename the files on disk. But if you try to close the file it will prompt you to save, and if you save it does rename the file on disk.
* Animated gif of the issue: https://gifyu.com/image/Mq3Y

I was able to fix it locally by changing https://github.com/atom/tree-view/blob/master/lib/helpers.coffee#L30 from 
```
    if filePath?.startsWith(oldPath)
```
to
```
    if filePath?.startsWith(oldPath + path.sep) or filePath? == oldPath
```
but I'm not familiar enough with the codebase to anticipate possible side-effects of this change. I also don't know javascript.

**Comment by rsese** [comment]
Thanks for the report and for digging into the code - I can reproduce on macOS 10.12.6 and Atom `1.22.0-dev-596fe5fae` - we'll ask the team to take a look.

**Comment by 50Wliu** [comment]
I can handle this.  I've fixed two similar instances of this already I believe.

**Comment by iolsen** [comment]
@50Wliu we'd like to get this fixed before the next release. Are you still working on it?

**Comment by 50Wliu** [comment]
I was out until today, but I can look at this next!  Just finishing up the HTML snippets issue.
