### ISSUE TITLE
Tree-View ignores "Show on Right Side" setting

### ISSUE THREAD

**Issue by bazzilic** [atom/tree-view#1199]
### Description
Toggling "Show on Right Side" does nothing.

![image](https://user-images.githubusercontent.com/1805832/32498168-d9ea4c60-c409-11e7-81e4-8ada407e7db2.png)

### Versions
OS: Windows 10 Pro x64 (Fall Creator update)

```
# atom --version

Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
# apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 3.6.3
git 2.15.0.windows.1
visual studio 2015
```

**Comment by 50Wliu** [comment]
Please see the FAQ:
https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762?u=wliu

**Comment by bazzilic** [comment]
Why do I still have the option in the menu then?
Also, I sync the setting between several computers and this particular setting does not seem to sync, i.e., it is likely not stored in the `ATOM_HOME` (because I just sync the whole folder)

**Comment by 50Wliu** [comment]
> Why do I still have the option in the menu then?

Atom does not have a way of knowing which keys in `config.cson` are valid; therefore it renders all of them.

Unfortunately, I don't believe there's a way to sync this new behavior across computers.
