### ISSUE TITLE
Crashing Windows test: when the project is a .git folder it does not create the tree view

### ISSUE THREAD

**Issue by 50Wliu** [atom/tree-view#1203]
https://ci.appveyor.com/project/Atom/tree-view/build/444

Can be reproduced with the following three lines only, assuming that the Tree View is enabled and visible:
```coffee
dotGit = path.join(temp.mkdirSync('repo'), '.git')
fs.makeTreeSync(dotGit)
atom.project.setPaths([dotGit])
```
I can't repro in a normal Atom window though.

**Comment by 50Wliu** [comment]
Ok, the issue specifically appears to be the `temp.cleanup()` call that happens in the `afterEach` hook.

**Comment by 50Wliu** [comment]
...which is async.  `temp.cleanupSync()`, however, fails with `ENOTEMPTY` errors.

**Comment by BinaryMuse** [comment]
This (the crashing) will be resolved by https://github.com/bruce/node-temp/pull/69 (and a dependency bump), but @50Wliu brings up some good points:

> Also two other questions regarding that. 1) Should we be using `temp.cleanupSync()`? and 2) why isn't cleanupSync called when the spec window exits?

**Comment by 50Wliu** [comment]
`temp.cleanupSync()` is automatically called on `process.exit`.  However it looks like closing the graphical spec runner doesn't fire that event.

**Comment by iolsen** [comment]
We need to get the tree-view tests passing. Putting this at the top of the prioritized list.

**Comment by daviwil** [comment]
On it!

**Comment by daviwil** [comment]
I'm seeing a few issues related to using rimraf to delete paths that are being watched using chokidar or other watchers like pathwatcher:

- https://github.com/johnagan/clean-webpack-plugin/issues/38
- https://github.com/johnagan/clean-webpack-plugin/issues/59
- https://github.com/isaacs/rimraf/issues/119
- https://github.com/isaacs/rimraf/commit/d53235de863cfb00f691456288fcf3abbced7f6c

**Comment by daviwil** [comment]
Reassinging to @50Wliu since he's already working on a fix.
