### ISSUE TITLE
'Hide VCS Ingored Paths' not being applied to Tree-View

### ISSUE THREAD

**Issue by gskerry** [atom/tree-view#1204]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode
    * Followed all applicable steps in the debugging guide
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed
    * Checked that there is not already an Atom package that provides the described functionality

### Description
Tree-View does not appear to be applying the 'Hide VCS Ignored Paths' setting

![atom-tree-view-ignore](https://user-images.githubusercontent.com/8867156/32747217-eb3a2dd4-c86c-11e7-8ff7-b691783c72f7.jpg)

### Steps to Reproduce
1. Activate 'Hide VCS Ignored Paths' within Tree-View package settings
2. Open project with git/gitignore that excludes certain directories

**Expected behavior:**
Expect *not* to see node_modules in project tree-view

**Actual behavior:**
VCS-ignored directories still shown.

**Reproduces how often:** 
100%

### Versions
1.22.0 x64
macOS 10.13.1 (17B48)

### Additional Information
This is after clean reinstall of app and in safe-mode.

**Comment by dbismut** [comment]
Hey @gskerry if you actually have a .git repository tree-view does hide the files as intended.

**Comment by gskerry** [comment]
Hi @dbismut,
Sorry for the delayed follow up. Yes, I see what you mean. Must have been errant copy of the folder at some point that was without the git history. Could have sworn I initially saw this behavior in an initialized repo. But have not been able to replicate. 

As you mentioned, the Tree-view only reflects the .gitignore options if the repo is actually initialized with git: 
![image](https://user-images.githubusercontent.com/8867156/34754840-343458d6-f575-11e7-8a5f-b6b351308787.png)


Imagine that is sufficient to close. Thanks for your patience.
