### ISSUE TITLE
.o files not ignored in tree-view

### ISSUE THREAD

**Issue by azimex** [atom/tree-view#1206]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tree view is not ignoring .o files although I listed as one of the extensions to ignore in the core settings under "Ignored Names"

### Steps to Reproduce

1. Create simple C++ program
2. Make and build the program
3. Build will produce .o files
4. Open the folder in Atom and those .o file will be shown on the side

**Expected behavior:** No .o files in the tree view
**Actual behavior:** .o files are shown in the tree view

**Reproduces how often:** Every time

### Versions
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
I have attached two images which shows I have listed .o as the first in the Ignored Names List.
I have also enabled "Hide Ignored Labels" in the tree view settings

![screen shot 2017-11-30 at 8 22 40 pm](https://user-images.githubusercontent.com/31452507/33463593-7481e08a-d60c-11e7-887d-4a4822359d04.png)
![screen shot 2017-11-30 at 8 23 33 pm](https://user-images.githubusercontent.com/31452507/33463594-74905e58-d60c-11e7-8c71-858ed874317c.png)

**Comment by rsese** [comment]
Thanks for the report!  Without a wildcard like `*`, adding `.o` will ignore a file or directory literally named `.o` - go ahead and change it to `*.o` and that should work.

**Comment by azimex** [comment]
Worked like a charm
