### ISSUE TITLE
Tree View creation races with deserialization

### ISSUE THREAD

**Issue by 50Wliu** [atom/tree-view#1210]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It appears that when adding a new project folder when there is no Tree View (i.e. 0 project folders), there is a race condition between Tree View creating the pane item due to a project being added and Atom core deserializing the existing Tree View associated with the project.  If the Tree View package manages to create and open the TreeView instance before deserialization does, an uncaught error is thrown (`Error: The workspace can only contain one instance of item [object Object]`).  It looks like in practice deserialization has always managed to finish before Tree View opens the item, but that isn't guaranteed.

### Steps to Reproduce

1. Add a `debugger` statement to https://github.com/atom/tree-view/blob/10a979ca29bdb66919c547d11e96e30be375b3b9/lib/tree-view-package.js#L67
2. Restart Atom to pick up on the modified Tree View package (or open a new window)
3. Remove all project folders so that the Tree View disappears
4. Open developer tools
5. Add a project folder
6. Resume script execution every time the breakpoint is activated

**Expected behavior:** The new project folder you added to be visible in the Tree View

**Actual behavior:** The Tree View disappears and the uncaught error appears in the console

**Reproduces how often:** 100%

The first time the breakpoint is triggered is due to Tree View receiving the `did-change-paths` event and attempting to open a new pane item.  The second is Atom core attempting to deserialize the existing Tree View for the project folder.

### Versions

```
Atom    : 1.25.0-dev-b7258bdc8
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by 50Wliu** [comment]
@BinaryMuse @kuychaco I believe this is caused by the work done in atom/atom#13963, where `restoreStateIntoThisEnvironment` attempts to deserialize the entire workspace including the existing Tree View.  While that seems like the correct behavior, I don't know how to prevent Tree View from attempting to create its _own_ instance and adding it to the workspace as well.

**Comment by daviwil** [comment]
Hey @50Wliu, I might have fixed this issue with PR #16610.  When you have a chance, can you try out the changes on master and see if you still run into the issue?

**Comment by daviwil** [comment]
I'll admit, the fix I made is slightly naive since it merely gets around the error.  I definitely observed the same behavior that you mentioned, that a TreeView pane item was being created before project deserialization happened, causing the error.  It seemed like project deserialization was _always_ recreating the Pane for the TreeView regardless of what was already there, but the PaneContainer's ItemRegistry wasn't getting cleared when that happened, thus the error.

**Comment by 50Wliu** [comment]
Yes, this seems to be fixed.
