### ISSUE TITLE
Delete file not working, error "Is gvfs-trash installed?"

### ISSUE THREAD

**Issue by daaru00** [atom/tree-view#1213]
### Prerequisites

* Ubuntu 17.10
* `gvfs-trash` is installed.
* `~/.local/share/Trash/files/` directory is present and writable, currently used by the system
* `/.Trash-1000` directory is present and writable by the current logged user

### Description

When I try to delete a file or folder an error is shown: 
`The following file couldn't be moved to the trash.`
`Is gvfs-trash installed?`

### Versions

```
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

Additionally, in Ubuntu 17.10 `gvfs-trash` is deprecated:
```
This tool has been deprecated, use 'gio trash' instead.
See 'gio help trash' for more info.
```

**Comment by daaru00** [comment]
I found a workaround, the problem was I installed Atom using `snap` maybe that version is not correctly build for Ubuntu 17.10, the solution is:

Remove the snap package
```bash
sudo snap remove atom
```
Add  WebUp8 PPA repositories
```bash
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
```
Then install atom
```
sudo apt install atom
```

**Comment by chambead** [comment]
Issue for me was trash location didn't exist:

```
user@system /var/www/html $ gvfs-trash /var/www/html/some.file.php
Error deleting file: Unable to find or create wastebasket directory
```

Solution is simply to create the trash directory:

```
sudo mkdir -p /.Trash-1000/{expunged,files,info}
sudo chown -R $USER /.Trash-1000
```

**Comment by rsese** [comment]
> I found a workaround, the problem was I installed Atom using snap maybe that version is not correctly build for Ubuntu 17.10, the solution is:
...
> Add WebUp8 PPA repositories

Glad you found a workaround but just wanted to mention that neither of these methods is officially supported - the 2 official installations are with the .deb and and official Linux package repositories (recently-ish introduced), see the Flight Manual for details:

https://flight-manual.atom.io/getting-started/sections/installing-atom/

Also, as of Atom 1.25 `gio` is supported /cc https://github.com/atom/atom/issues/15949#issuecomment-378088175

**Comment by gustawdaniel** [comment]
@daaru00 your method does not work.
