### ISSUE TITLE
Allow disabling hide/show arrow or always show tree-view etc

### ISSUE THREAD

**Issue by adamkdean** [atom/tree-view#1214]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hiding/showing tree view is a frustrating feature. The arrow to hide/show does not match the rest of atom's style, and it's animation is too attention grabbing, often appearing when it's not needed. Disabling the arrow with CSS causes inconvenience when opening new projects as the tree view is hidden. There should be an option in tree-view to simply always show the tree-view and hide the arrow.

### Steps to Reproduce

1. Hover over tree view (arrow appears)

**Expected behavior:** Arrow only to appear when I want it to, or to be a static arrow at the bottom etc.

**Actual behavior:** Arrow appears regardless, grabbing attention on every tree-view action.

**Reproduces how often:** 100%

### Versions

1.22.1

**Comment by 50Wliu** [comment]
We are reconsidering how docks should be displayed.  Please feel free to subscribe to https://github.com/atom/atom/issues/16116 for updates, or to comment on it with your thoughts.

**Comment by Skwerl23** [comment]
I second this, i would like the arrow to not be there, or be a permanent arrow next to the top or bottom (inside the window) sort of like how adobe has it on their windows...
