### ISSUE TITLE
Dock handle not showing; can't drag and drop to right side

### ISSUE THREAD

**Issue by kiyominox** [atom/tree-view#1216]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am trying to put the dock on the right side. Everywhere I look it says to drag it but when I do, nothing happens. I think the problem is the handle isn't showing up properly so I'm dragging the body of the dock.  I've tried full screen, half screen, random dimensions, so on, and I can't make it appear.

### Steps to Reproduce

1. Toggle tree-view
2. Drag dock

**Expected behavior:** [What you expect to happen]
Dock switches sides

**Actual behavior:** [What actually happens]
Dock does not switch sides

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python
git 2.15.1.windows.2
visual studio

Windows 10 Pro
Version 1709
OS Build 16299.125

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

![image](https://user-images.githubusercontent.com/14790272/34756244-ae5e144c-f586-11e7-94a4-a3fdc4a71bd3.png)

**Comment by 50Wliu** [comment]
I noticed that your screenshot isn't in safe mode.  Can you confirm that you tried dragging the Tree View to the right-hand side in safe mode (`atom --safe`) and that it still didn't work?

**Comment by alxtz** [comment]
@50Wliu 
That's interesting, I'm also facing the same issue while not in safe mode.
Does that mean it might be the conflict between packages?

**Comment by 50Wliu** [comment]
@alxtz so I'm understanding your comment correctly, did you try safe mode and did it work in safe mode?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/1216#issuecomment-356822671. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
