### ISSUE TITLE
selecting last item in file pane.

### ISSUE THREAD

**Issue by rsese** [atom/tree-view#1229]
_From @kentdlee on February 28, 2018 4:0_

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you open a series of directories in the left pane (what is called the "Project" pane) and the directories fill the pane from top to bottom, you cannot select the last directory to open it and look at its contents with the mouse or trackpad. You can open the directory by using the arrow keys to move the selection to the last directory and then pressing "Enter". 

The same goes for the last file in a series of files in the  "Project" pane. You cannot click on the last file in the pane if it goes all the way to the bottom.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

_Copied from original issue: atom/atom#16856_

**Comment by rsese** [comment]
Thanks for the report @kentdlee:

> If you open a series of directories in the left pane (what is called the "Project" pane) and the directories fill the pane from top to bottom, you cannot select the last directory to open it and look at its contents with the mouse or trackpad. You can open the directory by using the arrow keys to move the selection to the last directory and then pressing "Enter".

Hmmm, can you share a GIF/screencast that shows this behavior just so we're on the same page?

And can you share the information requested in the `Versions` section of the issue template?

**Comment by kentdlee** [comment]
The problem occurs in the Project pane when the directories and filenames are wider than the  project pane (a scrollbar may be interfering with selection) on Mac OS X version of Atom.
In the window in the screen shot I cannot select the CH2ReviewQs.odt file in the project window. Sometimes I have trouble opening the folder above it as well. If I click right on the odt file it just doesn't select the file at all. When I scroll right or left in the project pane the scroll bar appears to cover more than half the vertical height of the odt file's name. But when I am clicking on the filename the scroll bar is not visible.

I can get around this by selecting a line above this and using the cursor keys on the keyboard to move down to the last file or directory.

![screenshot](https://user-images.githubusercontent.com/1702731/36827317-7a7a6e86-1cd8-11e8-9ed8-6be5671086a1.png)

**Comment by rsese** [comment]
Thanks for the extra details - I was unable to reproduce on macOS 10.12.6 with Atom 1.24.0.  I created 30 directories with long directory names so the tree view had a horizontal scrollbar and the file listed after all the directories was clickable for me.

What specific version of macOS are you running and what version of Atom (`atom -v`)?

Also, was there any difference running in safe mode (`atom --safe`)?  And lastly, can you confirm what themes you're using and if you have any custom styles in your [styles.less file](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks)?

**Comment by kentdlee** [comment]
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

Mac OS 10.13.3 High Sierra

If could not get it to recur every time either. But I just did it again with just a list of files this time, not directories. I type "atom ." in the terminal to open the list of files. I dragged the project pane to a width that requires horizontal scrolling. Vertical scrolling was also required. Then I resized the window to bring up the bottom just enough to halfway cover the last file name. Then I clicked on a file higher up in the project window. After doing all this I was unable to select the last file in the project window.

Could it have something to do with the select criteria and the pane vertical size? The pane size may be saying that the last line is not visible if the scroll bar is visible, but when the scroll bar is not visible the last item is visible. I don't know, but it seems to have something to do with the horizontal scrollbar and the visibility of the last line being less than its full height when the scrollbar is visible.

**Comment by Ben3eeE** [comment]
@kentdlee Can you confirm that you see this behavior in safe mode `atom --safe`? The image you shared obscured the safe mode icon in the lower left corner of the Atom window.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/1229#issuecomment-370064490. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
