### ISSUE TITLE
Rename creates a duplicate file

### ISSUE THREAD

**Issue by christianbundy** [atom/tree-view#123]
This is an exact replica of #72, but it's still happening for me consistently with Atom 0.85.0 and Tree View 0.87.0. What steps should I take? Thanks!

**Comment by bucaran** [comment]
Still a lingering bug this seems, it it?

**Comment by thomasjo** [comment]
@bucaran Yes, but it's tracked at https://github.com/atom/autosave/issues/9.

**Comment by bucaran** [comment]
@thomasjo Thanks.
