### ISSUE TITLE
Crossing pane toggle control while dragging and dropping breaks tree view pane positioning

### ISSUE THREAD

**Issue by Mootly** [atom/tree-view#1233]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: Attempted. None of the directions to enter safe mode or attempts to work around them worked. Might because this computer is running beta.
    * Followed all applicable steps in the debugging guide: 
    * Checked the FAQs on the message board for common solutions: N/A
    * Checked that your issue isn't already filed: None found.
    * Checked that there is not already an Atom package that provides the described functionality: N/A

### Description

Dragging a file from the finder so the mouse path crosses the tree-view pane control of a closed tree-view pane triggers the tree view pane toggle, but does not redraw the rest of the window to accommodate the pop-out.

### Steps to Reproduce

(Note: I have vertical tabs enabled.)
1. With Atom open and the tree-view pane closed, open file manager/finder to the left of the window.
2. Drag a file from the file manager/finder to the Atom window so it crosses the toggle control on the closed pane.

**Expected behavior:** [What you expect to happen]
File appears in new tab with no other events triggered.

**Actual behavior:** [What actually happens]
The tree-view pane opens, but the rest of the window does not redraw to accommodate it. The offset, with the pane atop the vertical tabs and the left side of the edit window persists as the tree-view pane is open and closed after that point.

Only resolved by restarting Atom.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
Only occurs when dragging and dropping. Just dragging over the window with the left button pressed and nothing selected has no effect.

### Versions
Consistent since the release of the toggle-able tree view pane in both Mac (beta) and multiple Windows boxes (current non-beta and older standalone).

### Additional Information
Maybe the toggle is looking for a mouse event without checking whether the event occurred over the toggle or entered the toggle after occurring elsewhere?

**Comment by Mootly** [comment]
The more I poke. This is probably a dock issue, not a tree-view issue. So closing it.

**Comment by Arcanemagus** [comment]
For reference, this was refiled over in https://github.com/atom/atom/issues/16933, thanks! 😉
