### ISSUE TITLE
[Feature request] NPM package.json and node_modules highlight

### ISSUE THREAD

**Issue by senyaak** [atom/tree-view#1238]
I have always problem when I work with node - the number of direktoies in node_modules are too large and its very hard to find things you need. 
It would be nice if the packages from the package.json would be highlighted. Or even better hignlighted and placed on top :)

**Comment by 50Wliu** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package. For that reason, I'm going to close this. It sounds like a great idea for an Atom package though. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom :+1:
