### ISSUE TITLE
"Hide VCS Ignored Files" option is being reset from time to time

### ISSUE THREAD

**Issue by ZuBB** [atom/tree-view#1239]
I constantly get next issue:  "Hide VCS Ignored Files" option becomes turned off. I am pretty sure I have do not turn it off by myself. however it still happens somehow. for now I do not have any guess what can trigger this behaviour.. :(

**Expected behavior:** options remains turned on
**Actual behavior:** options becomes turned off
**Reproduces how often:** it repeats smth like ~every 2 weeks. 

### Versions
```shell
vzuzyak@mbp16 ~/work/cad/ui-advanced-tv|develop⚡?
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.10
git 2.16.1
vzuzyak@mbp16 ~/work/cad/ui-advanced-tv|develop⚡?
$ sw_vers -productVersion
10.13.3
vzuzyak@mbp16 ~/work/cad/ui-advanced-tv|develop⚡?
```
### Additional Information

I have set up sync of my atom settings. option is turned of locally and in remote it is on (I know it is not a 100% proof)

<img width="976" alt="screen shot 2018-03-28 at 16 21 16" src="https://user-images.githubusercontent.com/597016/38031847-dfd088a6-32a4-11e8-9c5b-71ce3e6bad0d.png">
<img width="659" alt="screen shot 2018-03-28 at 16 20 57" src="https://user-images.githubusercontent.com/597016/38031849-dfec47c6-32a4-11e8-9883-7d42c70c1877.png">

**Comment by ZuBB** [comment]
may be related/duplicated to https://github.com/atom/tree-view/issues/1181

**Comment by rsese** [comment]
Thanks for the report!  I was unable to reproduce, this is what I tried:

1. Install Atom 1.25.0
2. Check `Settings > Packages > tree-view > Hide VCS Ignored Files`
3. Run `Application: About` and install the update.

Expected and actual behavior is that after Atom updates to 1.25.1, `Settings > Packages > tree-view > Hide VCS Ignored Files` is still checked.

Can you reproduce if you try these steps?

**Comment by ZuBB** [comment]
Hi @rsese!

do you assume that checkbox becomes unchecked during upgrade? I do not have any observations on that but my guess is that it is not related

I am sorry I am quite busy now and I can't walk through steps you provided. I will try to track that with next major update after I come from vacation

thanks for your answer

**Comment by rsese** [comment]
> do you assume that checkbox becomes unchecked during upgrade? I do not have any observations on that but my guess is that it is not related

Oh sorry, I read the other issue you linked to and must have had that in my head.

> I am sorry I am quite busy now and I can't walk through steps you provided. I will try to track that with next major update after I come from vacation

:+1:

**Comment by u2g-tg** [comment]
I too am getting this issue, have had the 'Ignore VCS' enabling itself multiple times over the last couple of months. 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Pop!_OS 17.10 (Artful Aardvark)"
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
Linux *** 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ZuBB** [comment]
@rsese I have passed update procedure and did not faced this issue. however I would not consider it as passed away/fixed. lets keep this opened for some time

**Comment by u2g-tg** [comment]
Happened again for me just now

**Comment by 50Wliu** [comment]
This is most likely due to accidentally pressing <kbd>i</kbd> while the Tree View is focused, which toggles the Ignore VCS Files option.

If you are positive that that is not what is happening, please let us know!
