### ISSUE TITLE
Tree-view doesn't hide gitignored binary

### ISSUE THREAD

**Issue by dusatvoj** [atom/tree-view#1242]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I hide .gitignore files, so binary files (included in .gitignore) are still shown and green (new file, not commited on git)

![image](https://user-images.githubusercontent.com/11560794/38524322-7b59bf24-3c4e-11e8-9c3d-e28ab528cdb2.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
I expect that binaries will be hidden

**Actual behavior:** [What actually happens]
Binaries are still shown

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.14
git 2.14.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by belzebub40k** [comment]
I came across a similar problem today in one of my projects and it looks like it is related to the double asterisks (`**`) in the ignore patterns. For example `**.pyc` doesn't work but `*.pyc` does.

**Comment by rsese** [comment]
Thanks for the report @dusatvoj - exact steps to reproduce are always helpful but based on the screenshot, I think you're running into https://github.com/atom/tree-view/issues/196 so you can subscribe there if you'd like.  

@belzebub40k - if you think your issue is different, please open a new issue and fill out the issue template and we'll take a look.
