### ISSUE TITLE
Collapse Java-style empty hierarchies

### ISSUE THREAD

**Issue by lee-dohm** [atom/tree-view#125]
I occasionally have to work on Java projects for work. Java essentially requires project hierarchies like the following:

```
\project
    \src
        \com
            \example
                \project
                    \app
                        source1.java
                        source2.java
                        source3.java
                    \library-foo
                        source1.java
                        source2.java
                        source3.java
```

Java IDEs have a feature in their tree-view controls to collapse directories that only have one entry in them underneath `src`. So the above would look like this:

```
\project
    \src
        \com.example.project
            \app
                source1.java
                source2.java
                source3.java
            \library-foo
                source1.java
                source2.java
                source3.java
```

I'd like to see Atom tree-view support this feature as well on an opt-in basis.

**Comment by lee-dohm** [comment]
@lloeki points out that the GitHub website now offers this feature. I'm not picky on the visual representation, just think it would be great if the option was available.

**Comment by lloeki** [comment]
Just tossing an idea in the air, as the feature here might be slightly different. There is a case to be made for *simple grouping* and one for *logical grouping*. Here:

```
\src
    \com
        \example
            \project1
            \project2
```

Simple grouping would result in

```
\src
    \com.example
        \project1
        \project2
```

whereas logical grouping would result in:

```
\src
    \com.example.project1
    \com.example.project2
```

This example takes Java and the above notation as an example, but I'm not too fond of the dot as a separator. Here's why.

Go also has a similar structure in its workspace (output of tree(1), note the dots in the dir names):

```
src
├── code.google.com
│   └── p
│       └── go.tools
├── github.com
│   ├── codegangsta
│   │   └── negroni
│   ├── gorilla
│   │   ├── context
│   │   └── mux
│   ├── nsf
│   │   └── gocode
│   └── yosssi
│       └── ace
└── gopkg.in
    └── yaml.v2
```

Here simple grouping would output:

```
src
├── code.google.com
│   └── p / go.tools
├── github.com
│   ├── codegangsta / negroni
│   ├── gorilla
│   │   ├── context
│   │   └── mux
│   ├── nsf / gocode
│   └── yosssi / ace
└── gopkg.in / yaml.v2
```

An arguably more balanced logical grouping would give:

```
src
├── code.google.com / p / go.tools
├── github.com / codegangsta / negroni
├── github.com / gorilla / context
├── github.com / gorilla / mux
├── github.com / nsf / gocode
├── github.com / yosssi / ace
└── gopkg.in / yaml.v2
```

Maybe a threshold (default: 1) of number of children could give us something interesting (in the latter case it'd be at least 5 for `github.com` not to collapse). The alternative would be to have Atom recognise typical project layouts and do true logical mapping, and in that case it'd indeed map directories to Java package names, as hinted by the slash-to-dot conversion.

Regarding the separator, the argument for keeping slash is more obvious here (I actually used Unicode's DIVISION BAR in my original issue). Also, whitespace between slashes and names may hint at and allow for each name to be independently selectable regardless of collapsing, allowing for right-click action (possibly wanting to create a subdir or a new file halfway through the collapsed hierarchy).

**Comment by billbonney** [comment]
:+1: For this feature. I started working on android and java projects and this woudl be a great feature. I'd suggest 

```
\src
    \com
        \example
            \project1
            \project2
```
would become
```
\src\com\example
                 \project1
                 \project2
```
you could colorize the \com\example to highlight it's collapsed. Using . ie 'period' would confuse directories names /com.mycompany.stuff/ which i also have to deal with from time to time.

**Comment by qayshp** [comment]
:+1:

**Comment by geoffnin** [comment]
:+1:

**Comment by lachy-xe** [comment]
:+1:

**Comment by DDoS** [comment]
:+1:

**Comment by ZetaHunter** [comment]
:+1:

**Comment by NicoTravassos** [comment]
Can you please implement auto resize #6634

**Comment by Reyncor** [comment]
:+1: Reference to the Gedit feature request... I almost need this feature more then Linux retina support.

https://bugzilla.gnome.org/show_bug.cgi?id=750707

**Comment by sandokandias** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by jonasws** [comment]
:+1: Would be cool to have. Maybe it would be easier if this package exported a service that other packages could make use of to add such a feature? Seems to me that it would be in spirit with the whole "seperation of concerns into packages" paradigm that the community seems to embrace :smile:

**Comment by Reyncor** [comment]
never have I once thought to myself "Oh, I wish the tree's were bigger and more expanded, so that I may scroll more" It's a bit of an essential feature for many projects and too many addons I depend on are half baked and frequently push buggy updates.

In other words, it makes more sense to make Java style empty hierarchies default.

**Comment by cebor** [comment]
:+1:

**Comment by flyisland** [comment]
+1

**Comment by arkadiyt** [comment]
:+1:

**Comment by chrissphinx** [comment]
:+1:

**Comment by dabbeg** [comment]
+1

**Comment by AndreFlakowski** [comment]
One of the issues that keeps me from using Atom on bigger Java projects and use a much heavier IDE instead, so +1

**Comment by leesei** [comment]
:+1:

**Comment by dinesh-v** [comment]
For those who are still searching on how to collapse directory,

1. Open Package settings of tree-view
2. Go to Settings and enable Collapse directories

This is not enabled by default, which it should have been.

**Comment by lee-dohm** [comment]
> This is not enabled by default, which it should have been.

@dinesh-v Thanks for the feedback. There are still edge-case bugs caused by the feature as implemented (such as #670 and #1015, among others). Perhaps you would like to help make the feature bullet proof so that turning the feature on by default is an option? At this stage, we may still opt to leave it off by default but we certainly aren't going to enable it by default as the feature is currently implemented.

**Comment by MartinTrubelik** [comment]
Still have problem with .DS_Store files 😔 Why the "ignored files" option is not ignored by the Collapse directories?

**Comment by 50Wliu** [comment]
@MartinTrubelik please open a new issue and we'll take a look 🙇.
