### ISSUE TITLE
Moving selection up using keyboard skips entries when sibling above has multiple levels of expanded children

### ISSUE THREAD

**Issue by JK-mber** [atom/tree-view#1261]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using the keyboard for navigating the tree structure, some selections are skipped when moving up. This happens specifically when the sibling above the current selection has more than 1 level of expanded children.

### Steps to Reproduce

1. Have a workspace with following (or similar) folder structure (all expanded):
> A
>> B
>>> C

> D
2. Select folder D with mouse or keyboard
3. Press keyboard 'Up' (or invoke Core: Move Up)

**Expected behavior:**
Selection moves to folder C

**Actual behavior:** 
Selection moves to folder B

**Reproduces how often:**
Every time

### Versions

$ atom --version
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.13
git 2.15.2

### Additional Information
See comment below for my 2 cents on a simple fix

**Comment by JK-mber** [comment]
I'm no coffee script developer, but I would guess lines 424-426 in https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee would need to be enclosed in a while loop ("while another child is expanded, select the last child"):
from:
``` CoffeeScript
        @selectEntry(previousEntry)
        if previousEntry.classList.contains('directory')
          @selectEntry(_.last(previousEntry.entries.children))
```
to:

``` CoffeeScript
        @selectEntry(previousEntry)
        while @selectedEntry().classList.contains('directory') # No idea if this is the right syntax..
          @selectEntry(_.last(@selectedEntry().entries.children)) # No idea if this is the right syntax..
```

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce on macOS 10.12.6 with Atom 1.28.0.

And thanks for the extra details about where the issue might be, if you wanted to submit a pull request, I could ask the team to take a look.

**Comment by rsese** [comment]
Just noticed https://github.com/atom/tree-view/pull/1069, I'll ask folks to take a look at that.

**Comment by synthetiv** [comment]
Haven't thought about that one in a while! I'll take a look when I get a chance to see if anything needs to be refreshed for the latest versions of Atom & tree-view.
