### ISSUE TITLE
Opening + Copying Existing Pane While Focused on Tree View Causes Total Breakdown

### ISSUE THREAD

**Issue by ilrein** [atom/tree-view#1274]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Open tree view and use a hotkey shortcut to copy current pane over to a new direction (eg right)

2. You will see a new pane open with no content as it attempts to copy the tree view

Spamming this command opens uncloseable panes that eventually take over the entire screen, making it impossible to use any features

**Expected behavior:** Tree view should not be "paneable"

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

1.29

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

A screenshot of atom when you can't access any of the UI (with keyboard shortcuts or otherwise)

Any additional information, configuration or data that might be necessary to reproduce the issue.
![screen shot 2018-08-02 at 1 07 24 pm](https://user-images.githubusercontent.com/5523014/43599263-0f894268-9655-11e8-9c67-2c06447e9956.png)

**Comment by 50Wliu** [comment]
Thanks for the issue!  Just a few questions to help us triage it:

> hotkey shortcut to copy current pane over to a new direction (eg right)

Can you list the exact command you're using?

I also noticed that you didn't check the box indicating that you followed all the prerequisites.  To double check, is this issue reproducible in safe mode (`atom --safe`)?

Thanks!

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/1274#issuecomment-410062181. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
