### ISSUE TITLE
[Feature request] Project bookmarks

### ISSUE THREAD

**Issue by senyaak** [atom/tree-view#1275]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Often the Projects have too much directories/files so you easily lose whole picture of what you doing. It would be nice to be able to add folder/files to bookmarks so the are displayed after project folder.
### Usecase

1. You have some project with a lot of directories. For example some web application.
2. There are server client and database main directories 
3. Deep inside there folders which contains files related to UserSuperSecretInfo part of the app. For example it make together 10 files.
4. If you open all files it is too hard to navigate.
5. So we could just add 3 folders to bookmarks and the would be displayed after project folder(see screebshot)

![screenshot from 2018-08-09 15-38-08](https://user-images.githubusercontent.com/15360093/43902417-559ee70e-9bea-11e8-9c32-5e6e38295170.png)

**Comment by rsese** [comment]
Sorry, sent that comment too early accidentally!  I do want to thank you for the suggestion but also add that this functionality seems like a good idea for a separate package.  For example, see https://atom.io/packages/file-bookmark as an example.
