### ISSUE TITLE
No error message when you cut/paste a file to a directory where a file with the same name exists

### ISSUE THREAD

**Issue by mrfelipenoronha** [atom/tree-view#1303]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The editor don't show any kind of dialog/warning when trying to move a file to a folder that already has a file with the same name.

### Steps to Reproduce

1. Create a file 'tet.c' (*);
2. Create a empty folder;
3. Create another file 'tet.c' inside the folder;
4. Try to cut the tet.c (*) and paste it inside the created folder;
5. Nothing happens, no dialog shown.

**Expected behavior:** A messageBox or something from the kind saying "File already exists!".

**Actual behavior:** Nothing happens.

**Reproduces how often:** All the time

### Versions

Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.1
python 3.7.1
git 2.17.1

Ubuntu 18.04.2 LTS

**Comment by rsese** [comment]
Thanks for opening a new issue for this @mrfelipenoronha :+1:  Just a side note that Atom does show an error with the drag and drop version of this but otherwise with cut/paste, reproduced with 1.35.1 on macOS 10.12.6.
