### ISSUE TITLE
Atom 1.37.0 does not properly track (grey out) `**` in .gitignore

### ISSUE THREAD

**Issue by hehnope** [atom/tree-view#1317]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.37.0 on Linux no longer "greys" out certain `.gitignore` items; they are tracked as new files.

### Steps to Reproduce

*Edit by @rsese to add repro steps*

1. Create and initialize a Git repo.
2. Create and commit a .gitignore with this content:

```
**.log
```

3. Create a file called `test.log`

See screenshots in https://github.com/atom/tree-view/issues/1317#issuecomment-494948138 (see `test.log` in the tree view).

---

See screenshot below:

![380a](https://user-images.githubusercontent.com/24252625/58201465-aed2de00-7cc4-11e9-89e7-e1e82932f3bb.png)

Sample .gitignore:

```
**.log
.vagrant
```

Atom is properly detecting `.vagrant` is not tracked, but anything `**.log` is considered tracked. This was not a bug in a previous release.

**Expected behavior:**

I expect atom to detect `**` globs properly like in previous releases.

**Actual behavior:**

Atom is not detecting `**` globs.

**Reproduces how often:**

100% of the time

### Versions

```
$ atom --version
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by rsese** [comment]
Thanks for the report!  Reproduced with 1.37.0 on macOS 10.12.6:

![ignore-1 37 0](https://user-images.githubusercontent.com/734194/58204562-20e5fb80-7ca2-11e9-86e7-ac2ea421d3be.png)

And with 1.36.1:

![ignore-1 36 1](https://user-images.githubusercontent.com/734194/58204593-2f341780-7ca2-11e9-8cce-536ca3a44601.png)

**Comment by nathansobo** [comment]
This seems to be caused by a regression in libgit2 introduced via an upgrade in https://github.com/atom/git-utils/pull/91.

For now, there is a workaround. Instead of `**.log`, use `**/*.log` instead. Honestly, that makes more sense, but you're right that Git command line tools seem to support `**.log` whereas libgit2 currently doesn't.

**Comment by nathansobo** [comment]
In fact, I think that the syntax you're using is accepted by Git, but is somewhat incorrect. I think you're following into this bucket (from the `man gitignore`):

```
o   Other consecutive asterisks are considered regular asterisks and will match according to the previous rules.
```

So I think you could also replace `**.log` with `*.log` and get the same effect.

**Comment by nathansobo** [comment]
I've reported the issue in https://github.com/libgit2/libgit2/issues/5093.
