### ISSUE TITLE
Scrolling with pg-up/down should move the selection cursor

### ISSUE THREAD

**Issue by qwc** [atom/tree-view#132]
It is possible to scroll through large directories using the pg-up/pg-down keys, but the selection cursor stays where it is. So when you want to select a file on the current view, you get back to the location where the selection cursor resides.

Really annoying with big directories and a lot of not hidden hidden-files on your linux home directory for example. For a partly solution see #128 to hide unix hidden-files starting with a dot, it would help in my example.

(ArchLinux, KDE)

**Comment by 50Wliu** [comment]
Closing in favor of #1021.
