### ISSUE TITLE
Refresh tree view on commit

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [atom/tree-view#1325]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Tree view shown files as new or changed even after commit.

### Steps to Reproduce

1. Add new file or change file content to highlight as new / changed in tree view
2. Commit changes

**Expected behavior:**

Tree view should refresh immediatly after commit and remove the highlight from files whichs commited.

**Actual behavior:**

Tree view does not refresh after commit and shown files as new or changed.
A window focus event trigger need to refresh it.

**Reproduces how often:**

100%

### Versions

Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
OS      : Debian 10

**Comment by rsese** [comment]
Thanks for the report - I think this is the same issue as reports like https://github.com/atom/atom/issues/19606 and https://github.com/atom/tree-view/issues/1322.  Can you try increasing the number of [inotify watchers](https://github.com/atom/tree-view/issues/1322#issuecomment-514322652) setting on your system and see if that helps?

**Comment by AmirHosseinKarimi** [comment]
Hi @rsese ,
Thanks for your reply, I have changed inotify watchers to 524288 but the problem is still available and not fixed.

**Comment by rsese** [comment]
Do you see this issue with any repository, even a simple test repository with only 1 file?
