### ISSUE TITLE
A config to disable always show tree view

### ISSUE THREAD

**Issue by ThatXliner** [atom/tree-view#1374]
## Summary

Add an option to disable new features introduced by https://github.com/atom/tree-view/pull/1315

## Motivation

https://github.com/atom/atom/issues/21849 was opened because of https://github.com/atom/tree-view/pull/1315

**Comment by mortar-and-pestle** [comment]
Yes I completely agree. I've had to hide the tree view 20 times today. Please give us an to option to hide it upon open.

**Comment by ThatXliner** [comment]
Hmm this issue seems to be a duplicate of #1370

I’m going to close this and all further conversation should be redirected there
