### ISSUE TITLE
Focus file after selecting it

### ISSUE THREAD

**Issue by LinusU** [atom/tree-view#140]
When opening a file by clicking it in the tree-view, it would be great if focus could also be moved to the newly opened file. This makes it possible to click a file, ⌘+A, ⌘+C, click another file, ⌘+V. I tend to do this quite often.

Even more useful is that it allows clicking a file and start typing in it directly.

**Comment by brkattk** [comment]
If there is no "preview" mode for files, why would you need to click twice to focus on the editor? As far as I can tell, the only difference between single- and double-clicking a file in the tree-view is where the focus ends up. It's not at all intuitive, especially when using the keyboard to navigate and pressing `Enter` switches focus to the file in the editor.
