### ISSUE TITLE
Add tree view commands to the Command Pallete 

### ISSUE THREAD

**Issue by douglascamata** [atom/tree-view#169]
Tree view doesn't provide its command to the Command Pallete. I find pretty useful to delete a file by simply opening it and calling a "delete file" or "remove file" from the command pallete instead of finding the file in the tree view itself, right clicking, etc...

**Comment by MattKunze** [comment]
I still don't see delete file in the command palette, that seems to be one of the more useful commands

**Comment by MattKunze** [comment]
Never mind, I see that its "Remove" in the command palette instead of "Delete" like in the context menu
