### ISSUE TITLE
[request] keyboard shortcut to hide/show Vcs ignored files

### ISSUE THREAD

**Issue by kuatsure** [atom/tree-view#170]
Often times I find myself wanting to look at a `dist` or `bower_components` directory and since I ignore them by default, I have to go into the tree view settings and click the checkmark to show/hide them. Is it possible to have a keyboard shortcut to accomplish this?

http://d.pr/i/9CAW

OSX 10.9.2
Atom v0.104.0

**Comment by YashGulati** [comment]
This feature is very nice.
Good Work friends!

**Comment by gcphost** [comment]
Most annoying feature ever.
