### ISSUE TITLE
Add Delete options

### ISSUE THREAD

**Issue by gerardroche** [atom/tree-view#173]
> Re: https://github.com/atom/tree-view/issues/172

Add the following delete options:
- Ask before deleting files `default=true`
- Include a Delete command that bypasses the Rubbish Bin `default=false`

e.g. Gnome 3.10, Nautilus 3.10:

![nautilus-delete-options](https://cloud.githubusercontent.com/assets/44148/3360703/ae41f3f0-faf5-11e3-8d4c-3b53505d2d54.png)

In the Menu?
- `Move to the Rubbish Bin`
- `Delete` (if _Include a Delete command that bypasses the Rubbish Bin_ is enabled) 

In Nautilus, there is no prompt when you select to `Move to the Rubbish Bin`. Makes sense. I think this is good. The prompt is just friction. 

However, when you have `Include a Delete command that bypasses the Rubbish Bin` enabled and press `Delete` you get a prompt:

![delete-prompt](https://cloud.githubusercontent.com/assets/44148/3360837/533b2dda-faf7-11e3-855c-09ec5fb1a18b.png)

**Comment by 50Wliu** [comment]
This has been discussed in separate issues and is not a feature that the Atom team will be adding to tree-view.
