### ISSUE TITLE
Directory gets incorrectly marked "orange / modified" permanently.

### ISSUE THREAD

**Issue by while1eq1** [atom/tree-view#177]
In short:

if you add a submodule, commit, then rm -rfv submodule/\* then recommit. the parent dir of the submodule will forever be highlighted orange by tree-view.

Steps to replicate.

cd ~/repodir
git submodule add git://github.com/someone/somerepo.git
git add .
git commit -m "added submodule"
cd submodule
rm -rfv \*     (but leave the submodule dir itself)
git rm *
cd ..
git add .
git commit -m "removed contents of submodule's dir but left the dir"

The parent dir of the submodule dir will now be permanently marked orange "modified", even tho the working directory is clean.

Tested on: Atom Version 0.106.0 / OS X 10.9.3 (13D65)

**Comment by maxheld83** [comment]
+1

**Comment by michaelmcandrew** [comment]
I don't think you "properly" removed the submodule.

Try removing relevant the .git/modules file and seeing if the issue persists. In your example, that would be `~/repodir/.git/modules/somerepo.`

That fixed the problem for me. See https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule/21211232#21211232 for a bit more info...

**Comment by michaelmcandrew** [comment]
In other words, maybe this issue is outside the scope of tree-view / closable.
