### ISSUE TITLE
Change root directory

### ISSUE THREAD

**Issue by kebertx** [atom/tree-view#185]
I'm looking for a way to change the root directory of the tree view. I can right click on a folder and open that directory in a new window, but that's sort of slow and clumsy when I essentially just want to `cd` to that directory in atom.

When I freshly open atom from an applications menu it starts in my home directory, and I need to open another instance of atom in my project's directory to get to it. I feel like that should be easier!

**Comment by Dashed** [comment]
@lazychino Have you looked into this?

**Comment by lazychino** [comment]
@Dashed have not, my bad I've been busy.

**Comment by MrLeeh** [comment]
I would appreciate this feature as well. Would make working with the Tree View much more useful.

**Comment by mcortinas** [comment]
+1

**Comment by 50Wliu** [comment]
Is this essentially #404 or atom/atom#770?

**Comment by yaojingguo** [comment]
+1

**Comment by cganterh** [comment]
+1

**Comment by xjones** [comment]
+1

**Comment by kevinsawicki** [comment]
I believe this is the same as https://github.com/atom/atom/issues/770 as @50Wliu mentioned which is now supported and released.

You can now add/remove folders in an Atom window.

**Comment by hugollm** [comment]
I don't think [atom/atom#770](https://github.com/atom/atom/issues/770) is exactly this same functionality. I would very much enjoy some way to "enter" a directory, temporarily hiding everything else. It would be a great functionality when working with large trees.

**Comment by donkeypagoda** [comment]
+1

**Comment by toremielck** [comment]
+1

**Comment by jaceee** [comment]
+1

**Comment by tonybengue** [comment]
+1
