### ISSUE TITLE
[Windows] Ctrl + Shift selects files/folders outside of desired scope

### ISSUE THREAD

**Issue by JLoppert** [atom/tree-view#187]
Reproduction steps:
1. Select file inside nested folder
2. Shift click second file in nested folder
3. Ctrl click third file in directory above files from 1-2
4. Ctrl Shift click fourth file in same directory as 3

![croppercapture 6](https://cloud.githubusercontent.com/assets/1620641/3580239/eb5010ce-0bd0-11e4-8f20-50db7be34f1b.Gif)

Edit: Windows 7, Atom Version 0.115.0

**Comment by 50Wliu** [comment]
Can no longer reproduce.
