### ISSUE TITLE
Reveal in tree view does not highlight file if project folder is collapsed

### ISSUE THREAD

**Issue by JLoppert** [atom/tree-view#188]
### Repro steps:
1. Open the `image-view` repository in safe mode `atom --safe`
1. Open the `spec/fixtures` folder
1. Open `binary-file.png`
1. Collapse the `spec` folder
1. Collapse the root folder (`image-view`)
1. Right click on the image and select `Reveal in Tree View` from the context menu

**Expected:**
`binary-file.png` to be highlighted because it was revealed

**Actual:**
The `spec` folder is expanded but the file is not selected

![reveal root](https://cloud.githubusercontent.com/assets/1058982/19150598/f7c24948-8bc7-11e6-838e-fba97de42127.gif)

----

Repro Steps:
1. Open file inside a folder that visible in the tree view
2. Collapse folder with file
3. In file, right click and select Reveal in Tree View

The desired behavior is that the file is highlighted and not the parent folder. The desired behavior happens if the folder is expanded. 

![croppercapture 1](https://cloud.githubusercontent.com/assets/1620641/3587219/1f4d0fba-0c37-11e4-9416-89d406ae7046.Gif)

Windows 7, Atom Version 0.115.0

**Comment by 50Wliu** [comment]
Also apparently happens under Mac.

**Comment by benogle** [comment]
I am unable to reproduce on latest master

**Comment by Ben3eeE** [comment]
I can still reproduce this if the project folder is collapsed. With all other folders it seems that this bug has been fixed.

I am on Windows 7, Atom 1.10.2

![reveal root](https://cloud.githubusercontent.com/assets/1058982/19150598/f7c24948-8bc7-11e6-838e-fba97de42127.gif)
