### ISSUE TITLE
tree view automatically opens the file i click on. how to disable?

### ISSUE THREAD

**Issue by ninjajs** [atom/tree-view#199]
tree view automatically opens the file i click on. how do I disable this? i only want files to open when i double click.

**Comment by liquidvisual** [comment]
This is what you need: [https://atom.io/packages/chary-tree-view](Charity Tree View package)

**Comment by janmarek** [comment]
:+1:

**Comment by jbosse** [comment]
Yes, this frustrates me a great deal. I cannot find an option to disable this behavior. +1

**Comment by ceyhunkerti** [comment]
+1

**Comment by arielpontes** [comment]
:+1:  I agree. This should totally be "disableable".

**Comment by Mothil93** [comment]
I'm joining this: +1!
It's quite frustrating to look at some files and end up with 10 open ones, when the only thing I wanted to do was to check them out. Making them only respond to double click would be so nice.

**Comment by janmarek** [comment]
@Mothil93 It helps but it's not the same. Normal behavior is to select the file in tree view and do nothing else.

**Comment by Mothil93** [comment]
@janmarek I agree. I didn't notice until after I edited it, but still... It's a lot better. Ideally it should be as you explained, though.

**Comment by rondonjon** [comment]
+1 for a settings option to change the default behaviour.
I would prefer to "select" on single click and "open" on double click.

**Comment by liquidvisual** [comment]
Agree +1

**Comment by andela-anandaa** [comment]
Sure, will be nice to have it as preview (`Sublime Text` way), but not opening the file. +1 this!

**Comment by erik-landvall** [comment]
+1

**Comment by andrewnester** [comment]
+1

**Comment by victor-torres** [comment]
Hey, you should try to configure sublime-tabs plugin, which seems to be installed by default in recent Atom builds.

1. Settings
2. Packages
3. Installed Packages
4. Search for 'tabs' - it's a core package
5. In its settings check 'Use preview tabs'

**Comment by mattfrey** [comment]
+1 Terrible feature, makes the editor a huge PITA for performing file system operations - creating new files, folders, deleting files/folders etc. All these things become multi-step processes including closing a window, and in the case of deleting my db files between iterations, having to dismiss a 'large file may be slow in preview...' dialog.

**Comment by Zireael07** [comment]
@mattfrey, did you see the tabs -> use preview tabs option?

**Comment by mattfrey** [comment]
I did, it was disabled for me by default actually but still functioning as has been described, not sure why. I did install chary-tree-view though and this has alleviated the headache for now. Still have to re-open directory branches that get auto-collapsed when I click on the directory to initiate a 'new file', but this isn't nearly as frustrating. Was just throwing in my vote for this to be made an option or to change the default behavior.

**Comment by mattsfrey** [comment]
If anyone is interested, I forked chary-tree-view and made a quick modification to disable all single-click operations. So with this package installed you need to double click to not only open files, but also to expand / collapse directory views. 

https://github.com/mattsfrey/atom-double-click-tree-view

**Comment by tiagofreres** [comment]
@victor-torres Thanks! That worked perfectly.

**Comment by victor-torres** [comment]
@tiagofreres :smile:

**Comment by kyleschaeffer** [comment]
There is no need to install an additional package. Edit the settings of the `Tabs` core package and enable the **Use Preview Tabs** option.

**Comment by rondonjon** [comment]
Haven't you read the previous posts, or am I missing something in yours?

**Comment by kyleschaeffer** [comment]
Hah, I see it now @rondonjon. I'm a notorious skimmer. Thanks.

**Comment by soundtina** [comment]
thanks @kyleschaeffer !
it just works ! haha

**Comment by njwangchuan** [comment]
Thanks @kyleschaeffer，you are superman！

**Comment by lee-dohm** [comment]
Between the preview tabs option (which is migrating to a Core setting in v1.6.0) and the community packages, I believe this is solved. Please let me know if this isn't the case!

**Comment by surdu** [comment]
I don't manage to find the preview tabs option anymore (neither in the Tabs package nor in the core settings).

Will the Preview tabs option prevent opening a new tab at all, or to just have one tab opened every time you single click a file ?

This new feature of opening a tab when you single-click a file, and use the same tab for every file you single click, is even more confusing. Took me a wile to understand: 
1. Why is this tab title in italic text
2. Where the tab that I just had opened go (after clicking on another file) ?

In this case I believe it would be best to copy existing, well known behaviour than reinvent the wheel. Or at least provide an option to disable the new behaviour.

**Comment by jrdnbwmn** [comment]
+1 for @surdu comment

**Comment by lee-dohm** [comment]
@surdu There is a setting to disable the new behavior. Uncheck "Allow Pending Pane Items" in the Core Settings in Settings View:

<img width="741" alt="screen shot 2016-03-20 at 10 32 45 pm" src="https://cloud.githubusercontent.com/assets/1038121/13963808/20247cca-f024-11e5-9064-24d6bba7d8d8.png">

**Comment by vemv** [comment]
Thanks @lee-dohm. Whenever a feature clearly can confuse users or break their usual workflow, please consider introducing them disabled by default.

**Comment by surdu** [comment]
@lee-dohm Thanks for pointing me towards the option, the text of the option is very unintuitive :(. But maybe that is a topic for another issue.

I uncheck that option you go back to the old atom tree behaviour. 

What I, and I think also the OP was expecting, is an option that will allow an user to go back to the well-established behaviour of every editor before atom: when you select a file in the tree, you just select a file in the tree in order to do future actions on it (delete, rename, etc). In order to open it, you'll have to double click it.

**Comment by lee-dohm** [comment]
> Whenever a feature clearly can confuse users or break their usual workflow, please consider introducing them disabled by default.

The Atom team is discussing internally what we want to do for future default behavior changes. We hear you and, trust me, I feel your pain and I'm doing my best to communicate it back to the team :grinning:

**Comment by vemv** [comment]
Awesome to hear @lee-dohm!

**Comment by lee-dohm** [comment]
@surdu There's a conversation with the developers about this on https://github.com/atom/tree-view/issues/749. Check it out and add your ideas there :grinning:

**Comment by DonkeyAfterDark** [comment]
How can I get the "Single Click" to open files in a new tab function back?

**Comment by lee-dohm** [comment]
> How can I get the "Single Click" to open files in a new tab function back?

There is a package that @olmokramer created called [single-click-open](https://atom.io/packages/single-click-open) that can be used to have single-click-to-open with "Allow Pending Pane Items" disabled.

**Comment by quyin** [comment]
Unchecking the "Allow Pending Pane Items" option did solve the issue with files.

However, single clicking on a folder still expands / collapses it in the tree view, which is annoying in some cases, e.g. when you just want to select the folder for renaming or other operations.

The double-click-tree-view package solves all these issues (life savor @mattsfrey !).

But I still hope this can be incorporated into core settings, to serve different people's needs.

Just my two cents.

**Comment by benpptung** [comment]
+1, please completely disable "single click to open", it is VERY annoying! Double click to open is very good.

**Comment by andre-alforque-zoro** [comment]
atom-chary-tree-view package still works. Tree view is an option within the package's settings. (Unable to get double-click-tree-view to work)

**Comment by yubaoquan** [comment]
@lee-dohm I think "double click on folder to expand/collapses  it" should be in core features. Like what @quyin said.

**Comment by lee-dohm** [comment]
We've discussed, at some length, the variants in how people want to click to select and activate items in the tree view. We understand that some people want it to work differently than we have chosen. Adding options in click to select and activate increases the complexity of the tree-view package exponentially, complexity that we simply don't have the manpower to support. For these reasons, no, we aren't going to be expanding the methods available in core to click to select and activate items in the tree-view. Community packages are more than welcome to modify things though.

**Comment by surdu** [comment]
@Cethy of course it's not in the core config, @lee-dohm clearly stated they won't be ...

**Comment by jbosse** [comment]
> It's still not in core config in 2019 and `double-click-tree-view` does not work.
> `tree-view-click` works & offer the option single/double click for directories & files separately.

@Cethy VSCode has a `"workbench.list.openMode": "doubleClick",` setting. Plus so much more.

**Comment by Arcanemagus** [comment]
Locking this issue since the behavior it originally discussed doesn't exist any more, and further options to change how `tree-view` works are not going to be implemented [as previously stated](https://github.com/atom/tree-view/issues/199#issuecomment-319443181).

There are several community packages that re-implement parts of tree-view to work in many different ways, most of which are already mentioned in this thread 😉.
