### ISSUE TITLE
Vertical scrollbar too thin to catch with mouse

### ISSUE THREAD

**Issue by m1ga** [atom/tree-view#201]
Version 0.121.08dffb45 (git)
System: Fedora linux KDE

I have the tree view open and try to scroll by dragging down the scrollbar. But I have to be 1-2px left of the scrollbar to actually drag it up or down. As soon as I'm over the scrollbar it changes to the left/right resize mode. If I'm 3px away to the left side it will select the folder. 2px is a very small space to catch the scrollbar and it should stay in "scroll-mode" when I'm over the scrollbar

**Comment by izuzak** [comment]
@m1ga Are you seeing the same behavior in the latest version of Atom? (in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode))

**Comment by m1ga** [comment]
The behavior is still the same but the scrollhandle is bigger so its easier to pick it.

KDE Dolphin for example has a separate scrollbar and resize border:
![kde](https://cloud.githubusercontent.com/assets/4334997/6156202/6b631f14-b238-11e4-8fde-b709d64308f7.jpg)
right next to the scrollbar is the resize border. In the treeview there is only one thing to catch and its half drag and half resize (like in the picture above).

**Comment by nathansobo** [comment]
@izuzak I don't recall that but it's possible. Seems like we just need to make explicit room for the drag handle and push the scrollbar over.

**Comment by simurai** [comment]
@izuzak Maybe it was this: https://github.com/atom/tree-view/issues/255

Currently the resize handle overlaps the scrollbar (red) a bit:

![scrollbar](https://cloud.githubusercontent.com/assets/378023/6180657/8e83a0f2-b36b-11e4-86b8-af19b3c5dc39.gif)

So, yeah, by default the scrollbar could have some margin on the right so it doesn't overlap anymore or even a visible border.

**Comment by izuzak** [comment]
@simurai Ahhh, totally possible -- thanks for looking! :bow:

**Comment by m1ga** [comment]
@simurai :+1: 
wasn't able to capture the mouse cursor, I always had the normal pointer.

**Comment by nathansobo** [comment]
@izuzak So where are we at on this? I'm a bit confused.

**Comment by izuzak** [comment]
> @izuzak So where are we at on this? I'm a bit confused.

@simurai assigned this to himself.

**Comment by simurai** [comment]
Ok, I tried doing this:

```less
.tree-view-resizer {
  padding-right: 5px; // leaves room for the tree-view-resize-handle
}
```

Which would work, but I'm not sure if it should go into Core. It would break all themes. Not really break, but alter their current appearance by adding a gap. Here Atom dark:

![screen shot 2015-02-14 at 11 36 46 am](https://cloud.githubusercontent.com/assets/378023/6198355/3057dfd2-b43f-11e4-88df-48d66afc5d24.png)

@m1ga How do you feel about using the above snippet in your `styles.less` file? Or making an issue for the theme that you're using?

**Comment by m1ga** [comment]
@simurai awesome. That feels way better! I'm using the default theme. I've added it to my styles, thanks
