### ISSUE TITLE
can't toggle tree view by any method

### ISSUE THREAD

**Issue by hihell** [atom/tree-view#212]
I have tried click Packages -> Tree View -> Toggle Tree View and short cut "command" + "\". Neither will open the file tree view.

did I do it wrong? or may be I need to install some package first?

version: 0.124.0
osx: 10.9.4

**Comment by dgrcode** [comment]
This issue is actually not a duplicate. #68 is about showing the file tree when there is no files/folders. This issue is about not being able to open the file tree, having files/folders in the project.

**Comment by tgrrr** [comment]
Just putting this here for people that disable Nuclide: https://github.com/atom/atom/issues/5837#issuecomment-294350843
