### ISSUE TITLE
[Windows] Tree View: Reveal Active File not working as expected

### ISSUE THREAD

**Issue by sir4ur0n** [atom/tree-view#224]
I don't know if this is intentional or not, but the "Tree View: Reveal Active File" functionality does not work as expected for me.

If I open Atom for one file named File1, then the Tree View displays correctly.
Say I open a second file File2 in another folder in the same Atom window, then the Tree View still displays the tree of File1, and there is no way to display the one of File2.

By default I would expect the Tree View to switch whenever you switch between files. And if not, at least when I use the "Tree View: Reveal Active File" feature I expect it to refresh with the current file.

You choose if this is a bug or enhancement :D

**Comment by pierregodard** [comment]
@kevinsawicki  it's been closed a long time ago but i still have an issue very similar to what @Sir4ur0n pointed out. If I open a file living outside of the folder(s) currently added to the `tree-view` in an Atom window, i would like to be able to easily add the tree of that file to the `tree-view`. I don't see how to do that without manually adding it to the `tree-view` via `Add Project Folder`.  I don't see how [#63](https://github.com/atom/tree-view/issues/63) and more recently [#368](https://github.com/atom/tree-view/pull/368) address that. Am I missing something?

**Comment by macmadness86** [comment]
I do not see why this is closed. I am running 1.11.2 on Windows 7 and I don't see my tree changing directories when doing what is demonstrated in the gif in comment: @burabure commented on Oct 18, 2014

**Comment by Ben3eeE** [comment]
@macmadness86 I believe https://github.com/atom/tree-view/issues/946 is what you are looking for.
