### ISSUE TITLE
Move multiple files.

### ISSUE THREAD

**Issue by lukasoppermann** [atom/tree-view#232]
I would like to see the possibility to move multiple files at once.

I think it could work like this:
1. Select multiple files in the tree view
2. press m (default move command)
3. The prompt asks you for a new folder (just like now, but obviously without the file name, since you are moving multiple files).
4. All selected files are move to your chosen directory.

**Comment by Tyriar** [comment]
Some things that need to be figured out for this:
- What is the suggested directory?
- What happens when there are multiple files over multiple directories? How does this impact the suggested directory?
- Are files and directories handled the same?

**Comment by deiga** [comment]
@Tyriar Here are my thoughts
* We suggest the lowest common ancestor directory
* See above
* Yes, why wouldn't they be?

**Comment by thomdixon** [comment]
@deiga I started working on this using your changes from a year ago here: https://github.com/thomdixon/tree-view/tree/feature/move-multiple-selections

I implemented the `lowestCommonAncestor` helper (albeit, it needs to be refactored to work properly on Windows) to aid in determining the correct path based on your suggestions.

Would be happy to collaborate on this :)

**Comment by thomdixon** [comment]
I have multi-selection-moving with the move dialog working in my branch above. The linter has no complaints and all existing tests pass. I just need to find the time to write some meaningful tests (or if someone was willing to write them, I would be most appreciative).

**Comment by thomdixon** [comment]
Finished the tests and opened a PR. The PR only resolves this issue (using the move dialog) and doesn't yet implement drag-and-drop moves.

**Comment by alias1** [comment]
#793 seems related to solving this (for drag/drop/etc)

**Comment by thomdixon** [comment]
@alias1 It's only been 15 months. Like good wine, apparently PRs have to mature over time.

![1gc9fb](https://cloud.githubusercontent.com/assets/461514/21376582/f7898762-c6ea-11e6-813f-e8e4d80244ed.jpg)

**Comment by andyfleming** [comment]
With #793 / #1179, this command-based approach doesn't seem as necessary.

**Comment by thomdixon** [comment]
If Atom still supports `m`, then it should still support command-based multi-move. Considering my PR is 2+ years old, the code should probably use whatever #1179 uses instead of what I did back then.

**Comment by adamreisnz** [comment]
Moving multiple files with just the mouse doesn't work either. E.g. you can select multiple files, but then when you drag-drop them into another folder, only one of the files is moved. Should I raise a separate issue for that or can that be tackled as a part of this issue?
