### ISSUE TITLE
Unable to delete or rename folder contaning non empty sub folder

### ISSUE THREAD

**Issue by ujjwalwahi** [atom/tree-view#243]
If I try to delete folder which contains non empty folder, folder do not get deleted.

![delete](https://cloud.githubusercontent.com/assets/1370255/4664327/1f4693c4-5543-11e4-8f76-b92c047661e9.gif)

In case of rename

![rename](https://cloud.githubusercontent.com/assets/1370255/4664340/3be23f88-5543-11e4-9f88-5f99aaa07137.gif)

Atom Vesion: 0.135.0
OS: Windows 7

**Comment by batjko** [comment]
Does this still exist for anyone?
I can't replicate it anymore.

**Comment by 50Wliu** [comment]
Can't reproduce; assuming fixed.
