### ISSUE TITLE
ctrl-0 clashes with hotkey for reset font size

### ISSUE THREAD

**Issue by CheeseSucker** [atom/tree-view#251]
The tree view seems to take precedence, so this is only a minor inconvenience when you want to reset font size. There are of course workarounds:

1) Use mousewheel or ctrl + and ctrl - to find appropriate size
2) Use command palette
3) Rebind on user level

**Comment by jlogar** [comment]
Binding he key <kbd>ctrl</kbd>+<kbd>0</kbd> to 'window:reset-font-size' doesn't seem to cut it in version 0.179.0. Using windows. It just focuses the tree view.

**Comment by bentolor** [comment]
Also stumbled over this issue: Atom Menu announces Ctrl-0 under "View > Reset Font Size". 

I think the shortcut is more widely used to reset font-size than focusing parts of the UI (IMHO Alt-1..9 are common shortcuts for that)

**Comment by ardrigh** [comment]
Is this being worked on? It's still an issue in 0.290.0 on Windows.

I use CTRL+0 to reset my fonts in a number of apps, but it is broken in Atom due to the tree view focus overriding it.

**Comment by mnquintana** [comment]
I just fixed this in https://github.com/atom/tree-view/pull/479, but I'm not sure about the keybinding – I changed it to <kbd>Alt-0</kbd> – what do people think about that for switching focus?

**Comment by awayken** [comment]
:+1: That works for me, @mnquintana.
