### ISSUE TITLE
No way to close root folder

### ISSUE THREAD

**Issue by yazilliclick** [atom/tree-view#267]
Could be I'm missing something, sorry if so.  I opened file in folder which auto loaded folder in tree view.  After doing so and some work I've closed that file and now want to remove the folder it was in but this is now locked in OS (Windows 7) as it's considered still open/in-use by tree view.

Only way I could find to be able to delete the folder was either disable tree view package or close atom both of which are not ideal.

Also can't delete the root folder as that's been disabled https://github.com/atom/tree-view/pull/176

**Comment by kevinsawicki** [comment]
This is now possible since multi-folder projects are supported. There is a `Remove Project Folder` option in the context menu now to do this.
