### ISSUE TITLE
Autofocus to search field in "Search in directory"

### ISSUE THREAD

**Issue by benogle** [atom/tree-view#269]
From https://github.com/atom/atom/issues/4447 cc @Andreyco

After right click on any folder and selecting "Search in directory" search panel pops out.
It would be great if "Find in project" field gets focus automatically.

Triggering "Find in project" by Cmd+Shift+F keystroke focuses to this field as expected.

**Comment by izuzak** [comment]
Seems like this was fixed -- the "Find in project" is autofocused after "Search in directory" is selected:

![search](https://cloud.githubusercontent.com/assets/38924/6492678/9fff9062-c2b5-11e4-9d0b-efe6282e0963.gif)

@Andreyco can you still reproduce this?

**Comment by Andreyco** [comment]
The issue seams to be resolved.
Focus is gained as expected.

**Comment by izuzak** [comment]
Great -- thanks for confirming, going to close this out. :tada:
