### ISSUE TITLE
Tree view is Disabled Each time I start Atom

### ISSUE THREAD

**Issue by demisx** [atom/tree-view#277]
**Atom**: 0.157
**Tree View**: 0.137.0

Each time I start Atom, the `Tree View` package shows up as `Disabled` in the package settings window. I can enable it manually, but then it goes back to `Disabled` next time I restart the editor.

**Comment by bigamasta** [comment]
I've just faced the same issue. 

The problem was, that tree-view was conflicting with [Nuclide](https://atom.io/packages/nuclide) package (possibly file tree)

**Comment by matteocng** [comment]
Similar issue on every startup (`Atom` _1.19.0-beta5_, `Nuclide` _0.242.0_). `Nuclide` added `Atom` `tree-view` to `disabledPackages` in the config file, but it didn't toggle its custom `tree-view`.

```yaml
disabledPackages: [
  ...
  "tree-view"
]
```

I had to open the `Atom` [Command Palette](https://atom.io/packages/command-palette) and execute `Nuclide File Tree: Toggle`.
