### ISSUE TITLE
Hide Ignored names & Hide Vcs Ignored Files settings uncheck themselves

### ISSUE THREAD

**Issue by kmdavis** [atom/tree-view#279]
I keep having to recheck these 2 settings every few hours, as they apparently unset themselves.

**Comment by izuzak** [comment]
@kmdavis Let us know if you can reproduce this in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode) in the latest version of Atom -- closing this for now. :koala:
