### ISSUE TITLE
Smart Tabs

### ISSUE THREAD

**Issue by mattgraham** [atom/tree-view#3]
One of the features I miss in Atom is the 'smart tabs' concept. In sublime when you click on an item in the file tree, unless you start modifying it, or double click on the file, it previews the file without opening the tab completely. Therefore if you click on another file without officially opening it it doesn't stay open. 

![](http://c.gr4m.com/image/1Y3P1F2n2j23/image)

You'll see I browse through a few files, make a change and the tab opens and shows changes have been made in the tab color. Later in the gif I double click on the file and it opens it officially in a tab. 

Would love to see how we can add this into Atom

**Comment by edrex** [comment]
From atom/atom#3683 there seems to be support from the Atom core team for getting this into the default plugins. The wrapping approach taken by @ddavison in his plugin, while well-crafted, is vulnerable to breakages due to changes in the behavior of the plugins it wraps (tree-view and tabs). It would be much less awkward if the needed functionality were supported in the core plugins. I +1 reopening this issue.

**Comment by 50Wliu** [comment]
I'm going to open this-I'm not aware of any reasons for this to be closed if so many people want it in core.

**Comment by brkattk** [comment]
Is there anything I can do to help make this happen?

**Comment by Arbitel** [comment]
It's 2015 and its still not available in the core? :-1:

**Comment by Fridus** [comment]
I use https://github.com/ddavison/sublime-tabs :)

**Comment by ahanriat** [comment]
Works perfect ! Thank you Fridus ;)

**Comment by Kleagleguo** [comment]
This feature is really important to me, has it been resolved?

**Comment by ildoc** [comment]
sublime-tabs has problems with open-last-project package...
and both have issues with treeview and tabs core packages

**Comment by Platzer** [comment]
+1

**Comment by karim-interlaced** [comment]
+1

**Comment by AlexandruBusila** [comment]
+1

**Comment by mtowers** [comment]
+1

**Comment by maletor** [comment]
:+1:

**Comment by lexicalunit** [comment]
:+1:

**Comment by mattwagl** [comment]
+1

**Comment by tasmo** [comment]
+1

**Comment by GeertJohan** [comment]
+42

**Comment by Fridus** [comment]
[Sublime tabs](https://github.com/ddavison/sublime-tabs) works perfectly for me ;)

**Comment by kankaristo** [comment]
:+1:

**Comment by oiahoon** [comment]
+1
I am confused by these tabs opend by preview ~~

**Comment by Stanzilla** [comment]
+1

**Comment by macah1** [comment]
+1

**Comment by NeoFelipeAS** [comment]
+1

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! We'd really love for this to happen, but unfortunately the core team and maintainers don't quite have the bandwidth to take this on right now. However, we are always open to pull requests, and worst case scenario, one of us will get around to implementing this eventually. To keep this issue from getting too noisy I'm going to lock this for now.

**Comment by 50Wliu** [comment]
This has been implemented thanks to @carlosingles in atom/tabs#145, and it'll be available to use starting in 0.206.0.  However, Preview Tabs will be disabled by default for a while in order to catch potential bugs and get some user feedback before enabling it by default.

Once 0.206.0 comes out, here's how to enable preview tabs:
1. Open the Settings View (<kbd>Cmd+,</kbd> or <kbd>Ctrl+,</kbd>)
2. Go to the Packages sidebar
3. Search for "Tabs"
4. Click the Tabs package's Settings button
5. Find the "Use Preview Tabs" option and enable it
6. :tada:

**Comment by entr** [comment]
Thank you, really nice.

**Comment by dhnaranjo** [comment]
A big improvement, but currently the preview is only switching files on mouseclick, not if using keyboard navigation. I would definitely prefer that I don't have to click on each individual file to preview it.

Thanks much.

**Comment by mrbedo** [comment]
+1

**Comment by FrankM1** [comment]
Just what I was looking for +1

**Comment by aliuk2012** [comment]
+1

**Comment by mnquintana** [comment]
Please don't +1 this issue - this feature has been available for some time as a config option in the settings for the `tabs` package.

<img width="431" alt="settings_-__users_machistequintana_github_-_atom" src="https://cloud.githubusercontent.com/assets/823545/8940655/0b214e94-3539-11e5-84e7-f620ab6b033c.png">

**Comment by ddavison** [comment]
(lock the thread)

**Comment by dhnaranjo** [comment]
mnquintana, if you check out my comment from June 7th where I mentioned the Preview Tabs functionality only working on mouse click, not on keyboard based navigation. I believe this change is the thing that the users below me were +1'ing.

**Comment by mnquintana** [comment]
@dhnaranjo Would you mind opening a new issue for that?

**Comment by Zorgatone** [comment]
:+1:

**Comment by wprater** [comment]
is there a new issue for https://github.com/atom/tree-view/issues/3#issuecomment-126482900

**Comment by maahd** [comment]
+1

**Comment by 50Wliu** [comment]
> +1

This feature is already implemented.  What are you +1ing?

**Comment by maahd** [comment]
@50Wliu you are right. Sorry my bad. I didn't read the thread properly. I will remove my previous comment.

**Comment by dqisme** [comment]
@wprater  Not yet, I search this issue everywhere but I don't find it out. And have @mnquintana committed a new issue for that? We will follow it...

**Comment by deronsizemore** [comment]
I have turned on the Smart Tabs option and it seems that it's still opening a new tab when I single-click on a file name in the tree view. From that first click, it doesn't open a new tab each time I click on a new file; it just opens each file in that same tab (I guess it's a preview tab?) The setting says that tabs will only stay open if the file is double-clicked on which doesn't seem to exactly be the case here? Is this working correctly and is there a way to force Atom to act just as Sublime Text does in that it doesn't open any tabs at all when a file is single-clicked?

**Comment by adambrenecki** [comment]
@deronsizemore I just had a look at Sublime (Build 3083 on Linux), and the behaviour you're describing is exactly how Sublime acts. When you single-click on a file you get a temporary preview tab (with the tab title italicised), double-clicking the file or editing the buffer turns it into a regular tab.

**Comment by deronsizemore** [comment]
@adambrenecki Interesting. I'm still using SublimeText 2 on my machine which doesn't act in that way. In that version, it shows you a preview of files you click on but no new preview tab opens that you then need to close if you don't end up doing anything with the preview tab. It's not a huge deal; just seemed like one more tab that needs to be closed when I have no intention of using that preview tab, i.e, just wanted to peek at something inside another file real quick.

**Comment by ikrauchanka** [comment]
thank you guys!

**Comment by WakeupTsai** [comment]
thank you!

**Comment by erikjansson** [comment]
Thanks for this! However I totally agree with @deronsizemore. The "preview tab" isn't temporary since it doesn't go away if you execute an action such as clicking on another tab.

I also come from ST2, and if indeed the behavior is different in ST3, I don't see the benefit. The point of the feature (in my book), is to eliminate having to close tabs you didn't actively choose to open.

**Comment by pietrosld** [comment]
totally agree with @erikjansson that totally agree with @deronsizemore

**Comment by Anon-Penguin** [comment]
It seems to be default behavior. Is there a way to disable this, as I've gotten used to Atom acting on opening on one click?

**Comment by carlosingles** [comment]
@Anon-Penguin You should be able to change this in Settings:

![image](https://cloud.githubusercontent.com/assets/1631343/13942532/741f2f82-f047-11e5-8a7a-56c1f3f84a8c.png)

**Comment by Anon-Penguin** [comment]
Thanks @carlosingles!

**Comment by deronsizemore** [comment]
@carlosingles I'm not sure what the point of that "all pending pane items" option is?

Mine is currently checked which should allow items to be previewed without adding them to the pane permanently yet when I click on a file from tree-view, it still opens a new tab and the tab stays in the pane until I manually close it. Looks like the only difference that I can see is that with that option checked, the new file name in the pane is in italics and they are not in italics when that option is unchecked. 

What am I missing?

**Comment by carlosingles** [comment]
@deronsizemore The behaviour should be that you select a file and it opens a tab which is in italics (pending pane), when you select another file, that pending pane should get replaced with whatever file you clicked.

To make the pending pane a persistent tab, you can double click the file, edit the file or double click the tab title.

**Comment by k00ni** [comment]
Did you make the feature default, so that new files will be opened all in the same tab? 

I updated to Atom 1.6 yesterday and got confused due that "change", because before a new file gets opened in a new tab. Furthermore, in my opinion moving such setting into the tabs package is confusing, because i would expect such in the settings view.

**Comment by mkov88** [comment]
I'm guessing they recently made smart tabs default. ITS DRIVING ME UP A WALL!!!!!! can someone PLEASE tell me how to disable this? I want the old way of click any file and it stays open; No double clicking, no needing to change it.

**Comment by rorykoehler** [comment]
@mkov88 it's in settings.. see @carlosingles post a few posts up

**Comment by deronsizemore** [comment]
@carlosingles Thanks. Seems to be working as intended then on my end. It was just a misunderstanding on my part for how I assumed it was supposed to work. I just wish the pending tab would go away once I click into another file (like SublimeText 2). Just seems pointless to me to have a preview tab that that I have to manually close once I'm done previewing it. But, it's not a huge deal.

**Comment by andreaferretti** [comment]
I have unset `Allow Pending Pane Items`, but the end result is that whenever I click an item in the tree view, nothing happens.

Is there a way to restore the old behaviour, whereby a single click on a file opens it permanently? I don't care for clutter, I will close files I don't want to see open anymore, but it is maddening to open files to view them and then not being able to find them a few clicks later (because they were in a temporary pane and have been replaced)

**Comment by 50Wliu** [comment]
@andreaferretti Yes, you can install the [single-click-open](https://atom.io/packages/single-click-open) package.

**Comment by lilinjn** [comment]
An extreme version of this might be called "Atom No Tabs" which avoids creating any tabs at all (but splitting a large work area to allow side by side file editing, etc is fully supported).  While it might seem counter intuitive why this could be better, the feature is available in jetbrains editors (as well as being the way emacs and vim work), and is actually quite easy to use once a shortcut is provided ("shift-shift" is the default in the jetbrains case) to quickly show a list of recent files.  The result is a cleaner workspace and very easy navigation.

**Comment by nathansobo** [comment]
@lilinjn You should be able to get pretty close by just disabling the `tabs` package.

**Comment by lilinjn** [comment]
@nathansobo  thanks -- I will give that a try

**Comment by Xe** [comment]
Can you turn this behavior off?

**Comment by 50Wliu** [comment]
@Xe yep!  https://discuss.atom.io/t/i-cant-open-a-second-file-opening-a-second-file-makes-the-first-disappear/27266 has a section describing how to disable the feature.
