### ISSUE TITLE
Open in new split pane

### ISSUE THREAD

**Issue by johngeorgewright** [atom/tree-view#304]
Any thoughts on opening files from tree-view into new or existing split panes? If there's already a way to do it, can you point me in the direction?

**Comment by kevinsawicki** [comment]
> If there's already a way to do it, can you point me in the direction?

You could implement it in a custom package but there isn't built-in support for it currently.

**Comment by johngeorgewright** [comment]
OK. I'll have a go.

Would you be opposed to accepting a pull request so it's part of "tree-view", or is it preferable to have as a separate package?

**Comment by kevinsawicki** [comment]
> Would you be opposed to accepting a pull request so it's part of "tree-view"?

Yes, the fuzzy finder has support for opening into splits so this would make it consistent with that flow.

**Comment by johngeorgewright** [comment]
Ideal. I was just about to get started, however, when I stumbled on a problem already. How does one develop on this project? I cloned it, "linked" it, but on opening atom it says they contains "native modules that aren't compatible with this version of Atom". Do I need a different version of Atom, other than the current stable version?

**Comment by johngeorgewright** [comment]
Found the problem. The version of pathfinder need to be locked to patch updates only.

**Comment by johngeorgewright** [comment]
Hey there.

Functionally I've got it working. At the moment you can open the selected file in a new split by using: `ctrl-[left|right|up|down]`. And you can open a selected file in to an existing split by using `ctrl-[1-9]` where the number is the pane index.

I'd like to further improve it by displaying the panes' numbers when holding `ctrl`. But that could be a later improvement.

I'm also having some serious problems writing tests for "opening files in existing panes". I've been stuck for a couple of days and was wondering if anyone had a little time to maybe give me an idea how I can do it?

**Comment by johngeorgewright** [comment]
Actually... I might as well just start the pull request process at this point.

**Comment by francoiscabrol** [comment]
Thank you I would like to have this feature! I think that to add the vim keys is a good idea, since a lot of users (as me) are familiar with. But ctrl-right/left is already use under MacOS to switch between virtual desktops. More, using the atom core "pane:split-*" default keybindings would be easier, no?

**Comment by johngeorgewright** [comment]
Ah. Yes, I was weighing up weather to use the `ctrl-k [direction]` combo. Now I understand why it's there. Easy change.

**Comment by johngeorgewright** [comment]
What about opening in existing panes? Should that also be `ctrl-k [pane-number]`?

**Comment by francoiscabrol** [comment]
Oh yes it is a good idea indeed. The most important thing is to avoid conflit and keep the consistency with the other features. After installed, each one user can set his own key mappings. The perfection should be to define the vim keys for the tree view in the vim-mode package.

**Comment by johngeorgewright** [comment]
This has now been added and will *hopefully* be available in the forthcoming release.
