### ISSUE TITLE
Crashing when adding new folder/file in tree view

### ISSUE THREAD

**Issue by stramel** [atom/tree-view#310]
**OS:** Ubuntu 14.04
**Atom:** 0.167.0-6abe05b
**Tree-View:** 0.147.0

Crash log when running in `--safe` mode posted here: http://pastebin.com/GLeyxqAw

### Steps to Reproduce

1. Open a folder (project)
2. Navigate down tree (I did 4 folders deep)
3. Right click and select 'Add Folder' or 'Add File'

**UPDATE 1:** Found 'Add File' also causes a crash. Adding folder and file through OS works and properly renders in atom.
**UPDATE 2:** Found 'Reveal in Tree View' also causes a crash. Right-clicking on tab and selecting 'Reveal in Tree View'.

**Comment by stramel** [comment]
I assume this is also tied to atom/atom#4892. The crash dumps seem to be showing similar issues.

**Comment by lee-dohm** [comment]
Closing this in favor of the main issue atom/atom#4892 since they're all related.
