### ISSUE TITLE
Weird node text overlay when losing and regaining focus

### ISSUE THREAD

**Issue by DinisCruz** [atom/tree-view#323]
I was not able to reproduce the exact steps to get to the image below, but I get it consistently (after not using Atom for a while)

![image](https://cloud.githubusercontent.com/assets/656739/5710301/e0406790-9a98-11e4-83a6-4969782da740.png)

**Comment by kevinsawicki** [comment]
There is a core issue for this since it is a rendering issue from the Chrome 39 upgrade, https://github.com/atom/atom/issues/4924

**Comment by DinisCruz** [comment]
Thanks, I tried to find an issue that was mentioning this issue, but clearly failed at it :)
