### ISSUE TITLE
Remove Project from Tree View

### ISSUE THREAD

**Issue by TeckniX** [atom/tree-view#330]
Although it seems simple, it would be nice to have a 'Remove Project' from the Right-Click dropdown menu or the actual Package menu.

Sublime has it ;)

**Comment by maxbrunsfeld** [comment]
@TeckniX have you seen the `Remove Root Folder` item in the context menu, added in Atom v0.182.0? It may do what you're looking for.

**Comment by izuzak** [comment]
Yep, I think that's covered now. @TeckniX let us know if that's not what you were thinking of.

**Comment by TeckniX** [comment]
Sorry for the late reply - Yup the `Remove Root Folder` did the trick.
Thanks everyone!
