### ISSUE TITLE
Tree View doesn't scale gracefully

### ISSUE THREAD

**Issue by karai17** [atom/tree-view#334]
I installed atom-build and when I maximize the build window, Tree View gets scrunched. When I minimize it again, it gets very blurry as if it were stretching out the scrunched image. Clicking on Tree View seems to fix it, but that also moves where I am in my code.

More graceful scaling would be appreciated.

**Comment by izuzak** [comment]
@karai17 I'm having trouble reproducing this on the latest Atom. Here's a gif:

![build](https://cloud.githubusercontent.com/assets/38924/6155405/4bc43080-b233-11e4-9b0f-ea16c16ec072.gif)

Can you clarify which version of Atom you're using and on which OS, explain what you're doing differently than I am in the gif and share some screenshots or a gif (I'm not really sure what "scrunched" means)?

**Comment by karai17** [comment]
Hey, thanks for looking at this. Somehow I posted this issue in the wrong add-on, this was meant for Minimap (which has since fixed it). Sorry for the confusion!

**Comment by izuzak** [comment]
No problem, thanks for letting us know! :apple:
