### ISSUE TITLE
A tree view, file color transformation

### ISSUE THREAD

**Issue by deibydcruz** [atom/tree-view#340]
Hi, i found this, i think is a bug, the problem is when i make a click over a file in the tree view it turns green and in old atom versions this didn't happen and also not in windows. I attached a screenshot.
Pd: Actually i'm using Mac Os X 10.9.5 and the pre-install themes without pluings.

![captura de pantalla 2015-01-26 a la s 13 24 35](https://cloud.githubusercontent.com/assets/9937814/5906755/c68c4040-a55f-11e4-9f25-e22e232ea922.png)

**Comment by philipgiuliani** [comment]
Its not a bug, its a feature. Its because you are inside of a Git repository and this files are newly added but not yet commited..

**Comment by deibydcruz** [comment]
OHHH!!! Was that, thanks a million, but how i can change this to the original form???

**Comment by philipgiuliani** [comment]
You have to delete the hidden .git repository.

```
cd projects/your_folder
rm -rf .git
```

Than the it shouldntn be a it repo anymore.

**Comment by philipgiuliani** [comment]
There is a PR open which will add a Setting if you would like to keep the repository. https://github.com/atom/tree-view/pull/306

**Comment by deibydcruz** [comment]
Really thank you i will try it

**Comment by deibydcruz** [comment]
It get fix, really thanks.

**Comment by julioest** [comment]
@philipgiuliani you are a god ..
