### ISSUE TITLE
Sort files by modification date

### ISSUE THREAD

**Issue by damiendr** [atom/tree-view#343]
An option to sort the files by modification date would be nice. My use case is note-taking, where it is convenient to display the most recently updated notes at the top (like in Notational Velocity).

**Comment by ObviouslyGreen** [comment]
Also an option to sort by file type would be nice too, being able to navigate through code for a large project folder with a bunch of header files, source code files, resources, etc. You could just select and open only the desired files in atom, but then you lose the ability to see all the other files and folders in the project.

**Comment by guiraldelli** [comment]
> Also an option to sort by file type would be nice too
:+1: 

Actually, it is impressive the lack of sorting options. The ideal situations would be something like

    tree-view.sortList = [
        filetype
        modified
        alphabetically
    ]

and it sort the files by file type, modification date or alphabetically, for example.

**Comment by vjpr** [comment]
+1

**Comment by pawelkuras** [comment]
+1

**Comment by Michael-Thibault** [comment]
+1 bajillion There really ought to be a way to sort the tree view however the heck one wants. Or at least a clear way to add the extra functionality yourself.

**Comment by lukelamar** [comment]
+1

**Comment by piascikj** [comment]
+1

**Comment by standyro** [comment]
:+1:

**Comment by Sporky023** [comment]
+1

**Comment by jigargosar** [comment]
+1

**Comment by petonic** [comment]
+1

**Comment by jwhitmarsh** [comment]
+1 if we could sort by 'tag' too this would be great for people using https://github.com/davej/john

**Comment by luisaceituno** [comment]
+1

**Comment by vjpr** [comment]
Until this is implemented, you can use https://atom.io/packages/tree-view-finder.

**Comment by xu4wang** [comment]
＋1

**Comment by d-max** [comment]
+1

**Comment by jonathan-dejong** [comment]
+1

**Comment by andromedarabbit** [comment]
+1 also

**Comment by Draghi** [comment]
+1 Desperately need sort by filetype too.

**Comment by LeoStaley** [comment]
+1 

The [tree-view-finder package](https://atom.io/packages/tree-view-finder) hasn't been updated in 2 years, and is severely lacking in features. Sorting by date should be a core part of the tree-view package. 

I'm not a programmer, but a writer, so I can't do anything to improve it, but if this feature won't be added to the core, could someone fork tree-view-finder to add the needed features?

**Comment by sevenam** [comment]
+1

**Comment by miguelcg** [comment]
is this something in the roadmap @lee-dohm?

**Comment by ObviouslyGreen** [comment]
I'm interested in working on this. Anyone have any advice on starting this? Any specific reason the first PR wasn't merged besides lacking tests / organization?

**Comment by 50Wliu** [comment]
> Any specific reason the first PR wasn't merged besides lacking tests / organization?

It didn't pass linting or come with specs.  I'm unsure though if this is something we'd like to include in tree-view; let me get back to you before giving you advice.

**Comment by norpan** [comment]
There is a setting for this. Put this in your ```~/.atom/config.cson``` file:

```cson
  "tree-view":
    sortFoldersBeforeFiles: false
```

**Comment by lee-dohm** [comment]
Thanks everyone for your feedback on this.

On further review with the team, additional sort orders in the tree-view isn't something that we want to support.

**Comment by djoaquing** [comment]
Erm, i think it's kinda basic.

**Comment by autonome** [comment]
I took the original patch in @jkgeyti's pr #598, un-bitrotted and applied against latest tree-view and packaged it:

https://atom.io/packages/tree-view-sortable

**Comment by jkgeyti** [comment]
Awesome - I had completely forgotten I was the originator of the original patch, so I was just sitting here hoping someone would implement this functionality some day 😂 

I'll try and find some time to look through the package, as I seem to recall there were a fair few limitations to the approach I took. At any rate, thanks for doing the hard work of packaging it up!
