### ISSUE TITLE
Cannot see non-ignored files in an otherwise-ignored folder

### ISSUE THREAD

**Issue by 50Wliu** [atom/tree-view#349]
So this is a pretty complex issue and may just be that my gitignoring skills are too low (I'm fairly certain there's a much easier way to get all these rules in but I didn't write it and I'd prefer not to touch it ;P).

Let's say that I have set `.gitignore` to ignore all files under `configs/` like so: `addons/sourcemod/configs/**`.  I then *un-ignore* files that are in `configs/freak_fortress_2/`: `!addons/sourcemod/configs/freak_fortress_2/**`.

So basically I have a directory structure as follows:
```
addons
\-sourcemod
    \-configs
        \-freak_fortress_2
            |-non_ignored_file
            |-also_a_non_ignored_file
        |-ignored_file
```

Now the problem is that if I check `Hide VCS Ignored Files` in the Tree View settings I can still view the `configs` folder but I **cannot** see anything inside of it.  Clicking the little arrow thing really does nothing other than change the icon from `>` to `v`.  I therefore can't access any of the `freak_fortress_2` files.

[Full `.gitignore` file](https://raw.githubusercontent.com/50DKP/FF2-Official/stable/.gitignore)

While we're at it, I also have the opposite issue with a different folder.  I already commented about this in a different issue (that I can no longer find), but basically everything in a folder is showing up as newly added even though Git does not try to add them.  Relevant lines are `addons/sourcemod/scripting/**`, followed by `addons/sourcemod/scripting/include/**`, followed by `!addons/sourcemod/scripting/include/`, and finally followed by `!addons/sourcemod/scripting/include/freak_fortress_2*.inc`.  This results in the following:
```
addons
\-sourcemod
    \-scripting
        \-include
            |-falsely_added_file
            |-freak_fortress_2.inc (properly detected)
            |-yet_another_falsely_added_file
        |-correctly_detected_file
````
If this is an entirely different issue, let me know and I'll open up another issue for this.

**Comment by kevinsawicki** [comment]
This seems similar to https://github.com/atom/tree-view/issues/196

**Comment by 50Wliu** [comment]
Oh hey, found my comment!  :P  I'll close this for now unless you want to keep it open.
Also, the Fuzzy Finder does not pick up the files located in `freak_fortress_2`.

**Comment by kevinsawicki** [comment]
Closing sounds good, yeah, this is such a weird issue and I keep hoping it goes away each time we upgrade libgit2 versions.
