### ISSUE TITLE
Missing icons on mac

### ISSUE THREAD

**Issue by dwt** [atom/tree-view#350]
![bildschirmfoto 2015-02-03 um 10 37 35](https://cloud.githubusercontent.com/assets/57199/6017686/b5215e58-ab90-11e4-9b85-af550c05f022.png)

It just shows none - and there doesn't seem to be a setting to enable disable it - so I presume it's a bug.

**Comment by dwt** [comment]
Oh, and it does show icons on linux.

**Comment by lee-dohm** [comment]
Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by dwt** [comment]
Atom: Version 0.176.0 (0.176.0)
OS X: 10.10.2 (14C109)

atom --safe shows some icons. Still not the OS icons, but at least some.

**Comment by dwt** [comment]
![bildschirmfoto 2015-02-03 um 13 54 21](https://cloud.githubusercontent.com/assets/57199/6020439/2ee344c0-abac-11e4-9fca-752a38843120.png)

**Comment by 50Wliu** [comment]
What theme are you using?  Some themes disable icons from showing.

**Comment by lee-dohm** [comment]
I agree with @50Wliu, it appears that you're using a theme that disables the icons since you're seeing the correct icon set when you run using `atom --safe`.

**Comment by dwt** [comment]
> I agree with @50Wliu <https://github.com/50Wliu>, it appears that you're using a theme that disables the icons since you're seeing the correct icon set when you run using atom —safe.
> 
Right, then it’s a bug in the theme.

Thanks!
