### ISSUE TITLE
Text glitch

### ISSUE THREAD

**Issue by iclanzan** [atom/tree-view#351]
Sometimes parts of filenames are rendered a second time underneath the original. I can’t figure out what is triggering this glitch, but it is happening a lot. This is how it looks like:

![screen shot 2015-02-03 at 11 09 58 am](https://cloud.githubusercontent.com/assets/1806943/6029559/73a848c4-ab95-11e4-8712-a202cc9a0dcd.png)

I am using Atom on OS X with One Dark UI theme, but it is happening with other themes as well.

**Comment by kevinsawicki** [comment]
There is a core bug for this, https://github.com/atom/atom/issues/4924
