### ISSUE TITLE
Folders no longer at top of hierarchy

### ISSUE THREAD

**Issue by flynfish** [atom/tree-view#352]
After upgrading to atom 0.177.0, the folders in tree view are sorted in alphabetical order along with files, rather than being at the top.

Is there a way to get the old functionality back so folders are listed before files?

![screen shot 2015-02-06 at 12 58 54 pm](https://cloud.githubusercontent.com/assets/253936/6086581/4bf53db0-ae00-11e4-8615-7c405ad3bce2.png)

**Comment by kevinsawicki** [comment]
This was a new option added but the default behavior should have stayed the same, you can change from the Settings view, the "Sort Folders Before Files" option (which should default to true).

![screen shot 2015-02-06 at 12 49 29 pm](https://cloud.githubusercontent.com/assets/671378/6087305/a456cdd6-adfe-11e4-9fa3-18bc1b118c95.png)

**Comment by flynfish** [comment]
Thanks for the tip! The tree-view package was disabled for me because I had another package that was duplicating tree view functionality. Once I enabled again it gave me the option to select it.
