### ISSUE TITLE
When opening a project from command line, tree view is disabled each time

### ISSUE THREAD

**Issue by erikdonohoo** [atom/tree-view#365]
If I open a project tree-view is disabled every single time atom starts.  I have to manually renenable it.

After re-enabling it:
![screenshot 2015-02-11 08 32 53](https://cloud.githubusercontent.com/assets/1730681/6149833/ba13854c-b1c8-11e4-9764-15d77807b79a.png)

If I close the project, and open it again from the command line, it is immediately disabled

After reopening:
![screenshot 2015-02-11 08 33 15](https://cloud.githubusercontent.com/assets/1730681/6149838/c70c7222-b1c8-11e4-8d8a-f9dc02bfd8f5.png)

**Comment by lee-dohm** [comment]
I'm not sure why it would be showing on the left if it is disabled when Atom starts. Also, generally packages don't add anything to startup time when they are disabled. Can you reproduce the issue after completely exiting all instances of Atom and starting it with the command `atom --safe`?

**Comment by erikdonohoo** [comment]
Exited all instances, restarted with `atom --safe`.  Now tree view is showing enabled but there is no tree view to actually see.

![screenshot 2015-02-11 08 52 31](https://cloud.githubusercontent.com/assets/1730681/6150231/6a26aade-b1cb-11e4-8c8d-873ca7271827.png)

**Comment by erikdonohoo** [comment]
Maybe this issue isn't purely tree-view because my tabs package is also disabled when I start atom.

![screenshot 2015-02-11 08 55 05](https://cloud.githubusercontent.com/assets/1730681/6150302/bd9cd9d6-b1cb-11e4-8721-84f18b9a537a.png)


However, when I enable tabs, I see this...

![screenshot 2015-02-11 08 55 13](https://cloud.githubusercontent.com/assets/1730681/6150307/c1b2f73a-b1cb-11e4-8ae7-1505e26a91b9.png)

**Comment by erikdonohoo** [comment]
I just re-installed atom and the problem seems to have gone away.  I will slowly add back in the packages I was using and see if that reintroduces the problem
