### ISSUE TITLE
Is there a api/documentation for Tree-view

### ISSUE THREAD

**Issue by skandasoft** [atom/tree-view#367]
Is there a api/documentation for Tree-view

**Comment by bradleyflood** [comment]
+1 -- I'm looking for that too.

**Comment by lee-dohm** [comment]
There isn't a documented API for the Tree View. What is it you're trying to do?

**Comment by bradleyflood** [comment]
Me I was actually trying to find out how to move my Tree View from the right side back to the left. This was surprisingly difficult to find! No shortcuts or options in the package settings for this, no instructions easily found on Google, ended up finding it tucked away in the Package menu -- doh!

**Comment by lee-dohm** [comment]
Yeah, they used to be a little easier to find, but work is being done to make the individual package settings more accessible again.

**Comment by sgwill** [comment]
:+1:  on this. I'd love to be able to programmatically ask the tree view what the current folder is. Right now I'm having to check left and right panes, etc.

**Comment by 50Wliu** [comment]
API documentation is now available at https://github.com/atom/tree-view#api.  Please file separate issue requests for things you want added to the API.
