### ISSUE TITLE
Dependency on `shell` not declared.

### ISSUE THREAD

**Issue by bolinfest** [atom/tree-view#372]
This package uses `shell`, but does not declare it as a dependency in `package.json`. The use of `shell` was introduced in https://github.com/atom/tree-view/commit/e6cb60eecc761302e896e2d1f04419ae0e81e00c. At that time, `package.cson` was used instead of `package.json`.

It looks like when the conversion to `package.json` was made, dependencies were not included initially: https://github.com/atom/tree-view/commit/18d9c835ca872623d4a4c7edaab1cd929438c311.

I'm not even sure how this code works given that the dependency is not declared.

**Comment by bolinfest** [comment]
Ah, I guess it's because it's a built-in:

https://github.com/atom/atom/blob/97e0ddf15d7c3652dd142a4aaea0ca97c4f66831/src/module-cache.coffee#L206

Sneaky.

**Comment by oclbdk** [comment]
I guess there's still a bug though -- packages can't `require()` dependencies whose names collide with these built-in libraries (e.g. https://www.npmjs.com/package/shell)

**Comment by kevinsawicki** [comment]
Yup, shell is one of the many Atom Shell built-in modules similar to node's built-ins for fs, path, etc.
