### ISSUE TITLE
Collapse single-childed directory chains

### ISSUE THREAD

**Issue by lloeki** [atom/tree-view#374]
Say I have:

```
foo
└── bar
    └── baz
        └── qux.txt
```
It'd be nice it the tree view could optionally collapse single-childed directory chains, resulting in this:

```
foo ∕ bar ∕ baz
└── qux.txt
```

GitHub does this, and that's really useful e.g when you have some namespaced/nested thingies in Rails.

**Comment by lee-dohm** [comment]
This is a duplicate of #125, just a different separator character in the resulting collapsed view. I think your title is better though.
