### ISSUE TITLE
"repoForPath is not defined" when duplicating a file

### ISSUE THREAD

**Issue by postcasio** [atom/tree-view#382]
Atom 0.182.0, safe mode.

1. Right click a file in the tree view and select "Duplicate"
2. Enter any name
3. Hit enter

The message "repoForPath is not defined" is momentarily shown in the dialog before it is dismissed. The file is still duplicated successfully.

**Comment by maxbrunsfeld** [comment]
Thanks so much for catching this @postcasio.
