### ISSUE TITLE
Search in Directory searches in wrong root folder

### ISSUE THREAD

**Issue by 1j01** [atom/tree-view#384]
1. Open a project folder
2. Open another folder
3. Right click the second folder and say Search in Directory

**Expected**: Results show up from files in the folder you selected
**Actual**: Results show up from files in the original folder

**Comment by izuzak** [comment]
I can reproduce this. When you select Search in Directory on a root folder, all root folders are search (as far as I can tell) 

cc @maxbrunsfeld

**Comment by izuzak** [comment]
This issue was moved to atom/find-and-replace#355
