### ISSUE TITLE
tree showing Downloads and Trasmit folders

### ISSUE THREAD

**Issue by Cipa** [atom/tree-view#386]
From the last update the tree started showing folders it should not show.
I usually open my local files by going into a directory and clicking index.php and the tree only shows the parent folder, in my case startup

Starting today probably because of the latest update it started showing 2 more folders. This happens even if I run atom in termial on the startup folder

Mac 10.10.2
Version 0.184.0 (0.184.0)

![screen shot 2015-02-26 at 2 03 11 pm](https://cloud.githubusercontent.com/assets/293377/6399460/98b48258-bdc0-11e4-8f28-f2b924d17336.png)

**Comment by maxbrunsfeld** [comment]
What packages do you have installed? Also, does this still happen if you clear your `~/.atom/storage` directory and restart Atom?

**Comment by Cipa** [comment]
atom --safe and clearing the storage doesn't help :(

Is there a way I can query the list of packages and send them to you?

**Comment by maxbrunsfeld** [comment]
Yeah, `apm list`. Also, this is definitely a bug, but just FYI you can remove those folders from the tree-view by right clicking on them and selecting `Remove Root Folder`.

**Comment by Cipa** [comment]
Built-in Atom packages (84)
├── archive-view@0.50.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.47.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.44.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.23.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.71.0
├── command-palette@0.34.0
├── deprecation-cop@0.37.0
├── dev-live-reload@0.41.0
├── encoding-selector@0.18.0
├── exception-reporting@0.24.0
├── find-and-replace@0.158.0
├── fuzzy-finder@0.68.0
├── git-diff@0.54.0
├── go-to-line@0.30.0
├── grammar-selector@0.45.0
├── image-view@0.49.0
├── incompatible-packages@0.22.0
├── keybinding-resolver@0.29.0
├── language-c@0.41.0
├── language-clojure@0.13.0
├── language-coffee-script@0.39.0
├── language-csharp@0.5.0
├── language-css@0.28.0
├── language-gfm@0.64.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.29.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.59.0
├── language-json@0.12.0
├── language-less@0.25.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.10.0
├── language-php@0.20.0
├── language-property-list@0.8.0
├── language-python@0.32.0
├── language-ruby@0.48.0
├── language-ruby-on-rails@0.19.0
├── language-sass@0.34.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.16.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.137.0
├── metrics@0.45.0
├── notifications@0.28.0
├── one-dark-syntax@0.3.0
├── one-dark-ui@0.5.0
├── one-light-syntax@0.4.0
├── one-light-ui@0.4.0
├── open-on-github@0.32.0
├── package-generator@0.38.0
├── release-notes@0.51.0
├── settings-view@0.183.0
├── snippets@0.76.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.55.0
├── status-bar@0.60.0
├── styleguide@0.44.0
├── symbols-view@0.84.0
├── tabs@0.67.0
├── timecop@0.31.0
├── tree-view@0.162.0
├── update-package-dependencies@0.8.0
├── welcome@0.24.0
├── whitespace@0.29.0
└── wrap-guide@0.31.0

/Users/ciMac/.atom/packages (27)
├── .bin
├── SFTP-deployment@0.5.0
├── Sublime-Style-Column-Selection@1.2.3
├── atom-beautify@0.21.3
├── atom-ctags@2.6.0
├── atom-html-preview@0.1.3
├── autoclose-html@0.15.0
├── autoprefixer@2.2.1
├── close-tags@0.2.0
├── emmet@2.3.3
├── highlight-css-color@1.3.0
├── highlight-selected@0.9.0
├── html-entities@0.3.1
├── key-peek@0.2.5
├── less-autocompile@0.3.3
├── linter@0.12.0
├── linter-csslint@0.0.11
├── linter-jshint@0.1.0
├── linter-less@0.3.1
├── linter-php@0.0.11
├── monokai@0.12.0
├── preview@0.13.4
├── red-wavy-underline@0.2.4
├── sort-lines@0.10.0
├── todo-show@0.8.0
├── white-cursor@0.5.2
└── zenburn@2.0.1

**Comment by Cipa** [comment]
Weird, after I did Remove Root Folder they stopped appearing even if I restart. Same goes for different folders/projects. Maybe it was just me

**Comment by maxbrunsfeld** [comment]
OK, please report if folders unexpectedly get added to the tree view again. I suspect they got added to the project due to a bug in an earlier version of Atom, which is now fixed, and they only became visible due to tree-view upgrades in 0.184.

**Comment by maxbrunsfeld** [comment]
I'll reopen if you see any further problems.
