### ISSUE TITLE
sql file not showing?

### ISSUE THREAD

**Issue by flynfish** [atom/tree-view#388]
I have a sql file that doesn't show up in tree view when the git repo is added as a root folder. If I add the repo's parent folder as the root folder, then it shows up correctly. .sql is not in my gitignore either. 

![screen shot 2015-02-27 at 10 49 46 am](https://cloud.githubusercontent.com/assets/253936/6418067/4853f21c-be6f-11e4-9f88-a13f37aa1809.png)
![screen shot 2015-02-27 at 10 52 25 am](https://cloud.githubusercontent.com/assets/253936/6418068/4856e7ce-be6f-11e4-8585-2e76f0e92963.png)

**Comment by maxbrunsfeld** [comment]
In the state when it doesn't show up in the tree-view, does the fuzzy-finder (`Fuzzy Finder: Toggle File Finder` command) show `applications_view.sql`? Can you share the contents of your `.gitignore`?

**Comment by flynfish** [comment]
The file is not found via Find File. Here is the .gitignore

```
# See http://help.github.com/ignore-files/ for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile ~/.gitignore_global

# Ignore bundler config
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3

.sass-cache

# Ignore all logfiles and tempfiles.
/log/*.log
/tmp
/public/uploads
.project
/config/*.yml
/config/initializers/setup_mail.rb
/config/initializers/stripe.rb
/config/initializers/docusign_rest.rb
/config/stripe.rb
/config/unicorn.rb
/config/coverband.rb
/coverage
*.rb.old

.env

*.DS_Store
.rvmrc

# ignore IDE stuff
/.idea

# old revs of docs
/doc/*.rev.doc

# ignore bower and node modules
/node_modules
/bower_components
```

**Comment by flynfish** [comment]
Sorry about this, after more research my global git ignore had *.sql in it.
