### ISSUE TITLE
TreeView should be able to hide files based on some criteria

### ISSUE THREAD

**Issue by karai17** [atom/tree-view#389]
A recent pet peeve of mine has been that there is seemingly no way to hide unnecessary files. After switching from Dropbox to Google Drive, I've become quite annoyed with the slew of "desktop.ini" files. I've added desktop.ini to my .gitignore file so it's not a practical issue, but I would also like to avoid seeing hidden files in Atom, or even better have a config file where I can specify files based on criteria such as:

* `desktop.ini`
* `*.ini`
* `desk*.ini`

**Comment by lee-dohm** [comment]
The Tree View can already do this:

If you check "Hide Ignored Names" in the Tree View settings:

![hide-ignored-names](https://cloud.githubusercontent.com/assets/1038121/6424021/fdd1b874-bea4-11e4-977b-9f19ba59877a.png)

And then add your criteria to the Ignored Names setting on the Core Settings screen:

![ignored-names](https://cloud.githubusercontent.com/assets/1038121/6424035/291d900c-bea5-11e4-8e76-afe88cb99504.png)

It will do what you want.

**Comment by karai17** [comment]
Oh wow, I totally missed that. Thanks!
