### ISSUE TITLE
Rename Changes File's Root Folder

### ISSUE THREAD

**Issue by eviljoe** [atom/tree-view#394]
When renaming a file while atom has two root folders open, the file will be moved to the first root folder.

To Recreate:
 1. Create two directories: `dir1`, `dir2`
 1. Add a file (`file.txt`) to `dir2`
 1. Add `dir1` as a root folder to atom (this folder needs to be added first)
 1. add `dir2` as a second root folder to atom
 1. Right click and rename `file.txt` to `file-renamed.txt`
  * The file will be renamed, but it will also be moved into `dir1`

I have seen this problem in Windows.  I have not tested this in Linux or OSX.

**Comment by 50Wliu** [comment]
What version of Atom is this?  If it isn't 0.184.0, could you please try reproducing on that version in safe mode (`atom --safe`)?

**Comment by eviljoe** [comment]
I am using v0.182.0.  It is still happening when I start in safe mode.

**Comment by eviljoe** [comment]
After I upgraded to v0.186.0, this is no longer happening.  I can now rename files without having their root folder changed.
