### ISSUE TITLE
Filenames render incorrectly sometimes

### ISSUE THREAD

**Issue by donutmonger** [atom/tree-view#410]
![filename_bug](https://cloud.githubusercontent.com/assets/3676616/6851890/43a22a8e-d3a7-11e4-839d-7635b7eecc4b.png)

Using Atom 0.188.0 on Mac OSX 10.10.2

I have not been able to find a way to consistently reproduce the bug, it just pops up periodically. Closing, and then re expanding the top level project folder is a temporary fix.

**Comment by kevinsawicki** [comment]
This is being tracked in https://github.com/atom/atom/issues/4924
