### ISSUE TITLE
Creating Tree View Context-Menu Commands

### ISSUE THREAD

**Issue by francoislaberge** [atom/tree-view#428]
hi,

How would I create a custom tree view command in my own package that adds support for other commands. Specifically I'm trying to add a ```Open as JSON``` command, so that files we have that open a custom editor can still opt into using the standard text-editor.

Any help would be appreciated. I got stuck on getting access to what is selected when the context-menu command fires.

Francois

**Comment by kevinsawicki** [comment]
Add a file at `menus/menu.cson` to your package with something like:

```coffee
'context-menu':
  '.tree-view .file .name[data-name$=\\.json]':
    [{label: 'Open as JSON', command:  'your-package:open-as-json'}]
```

Then in your package's main module:

```coffee
activate: ->
  atom.commands.add '.tree-view .file .name[data-name$=\\.json]', 'your-package:open-as-json', ({target}) ->
  console.log(target.dataset.path) # Logs the path of the seleted item
```

**Comment by francoislaberge** [comment]
Thanks, I'd figured out a way, but this works better.

:+1:

**Comment by ArtemGovorov** [comment]
This was working for me up until some recent update:
```
'context-menu':
  '.tree-view .file .name':
  ...
```
It looks like the selector is broken by some recent changes.

P.S. this works:
```
'context-menu':
  '.tree-view .file':
  ...
```
but obviously targets an `li` not the nested `span` with data-*.
