### ISSUE TITLE
Doesn't respond to font-weight property

### ISSUE THREAD

**Issue by krainboltgreene** [atom/tree-view#429]
``` sass
.tree-view {
  font-size: @ui-font-size;
  font-family: "Fira Sans";
  font-weight: 200;
  -webkit-font-smoothing: antialiased;
}
```

This is what I have, but the font-weight property doesn't seem to reflect in treeview. Works everywhere else.

**Comment by chrismcleod** [comment]
Also doesn't work with roboto font

**Comment by 50Wliu** [comment]
The One UI themes override the `.tree-view { font-weight: 200; }` selector with a more specific one and sets it to normal.  I suspect this is a theme issue, not a Tree View issue.
