### ISSUE TITLE
[feature request] can you add a shortcut for rename like add when focus on a treenode?

### ISSUE THREAD

**Issue by dfang** [atom/tree-view#434]
can you add a shortcut for rename(r) like add(a,A) when focus on a treenode?

thanks !

**Comment by lee-dohm** [comment]
The Tree View already has this feature. <kbd>M</kbd> or <kbd>F2</kbd> will activate the `tree-view:move` command.

https://github.com/atom/tree-view/blob/ec7c56ae5f3a56f0d4c8162ee11bae530976f440/keymaps/tree-view.cson#L72-L73

Let us know if you have any other questions or suggestions! :grinning:

**Comment by dfang** [comment]
👍
