### ISSUE TITLE
Right-click doesn't select the right item until after the context menu is closed

### ISSUE THREAD

**Issue by oclbdk** [atom/tree-view#435]
1. Right click an unselected file in the tree-view
2. The clicked file remains unselected
3. Hit `<esc>`
4. The clicked file becomes selected

I expect the file to be selected right after right-clicking it

**Comment by jportela** [comment]
I think this is a duplicate of https://github.com/atom/atom/issues/2991 
Are you seeing this behaviour on Mac OS?

**Comment by izuzak** [comment]
Thanks @jportela -- looks like a duplicate of https://github.com/atom/atom/issues/2991 to me too. I'm going to close this, and @oclbdk please subscribe to that other issue for updates (and let us know if we misunderstood your report). :v:
