### ISSUE TITLE
onDidChangePaths not triggered

### ISSUE THREAD

**Issue by basarat** [atom/tree-view#437]
Perhaps I am using this wrong but as per my understanding (https://github.com/atom/tree-view/issues/433#issuecomment-96995549) this should be triggered if you rename / move files / folders from the tree view. 

# Steps to reproduce
open the developer console and run the following code: 

```js
atom.project.onDidChangePaths(function(){console.log(arguments)});
```

Now in the tree view rename a file (or a folder). You will not see anything logged to the console. 

/cc @thomasjo

**Comment by thomasjo** [comment]
I'm afraid I misunderstood the callback—I should have looked more closely. `Project::onDidChangePaths` only gets emitted when projects themselves get added, removed or renamed, not for files or folders within a project.

**Comment by thomasjo** [comment]
So looks like perhaps you should re-open #433 for the time being, and close this one.
Sorry about the confusion!

**Comment by basarat** [comment]
> Sorry about the confusion

no worries. Thanks for your attention :rose: :heart:
