### ISSUE TITLE
Add ability to dock, hide, and change position of the Tree View

### ISSUE THREAD

**Issue by di48l069** [atom/tree-view#440]
Hi there can you guys a feature where can dock, hide and change position of the tree-view like visual studio
![capture](https://cloud.githubusercontent.com/assets/7794777/7467879/9aaec624-f301-11e4-8ac7-672b8dd4e865.PNG)

**Comment by mnquintana** [comment]
@NicoTravassos You can already change the position of the Tree View with `Tree View: Toggle Side` which will switch between the Tree View being docked to the left and right sides, and you can hide the Tree View with View > Toggle Tree View (or <kbd>Ctrl-\</kbd>). Does that about cover what you're looking for?

**Comment by NicoTravassos** [comment]
@mnquintana Thank you did not know those features were available but is it not possible to hide it on the side of the screen like the image i posted above?

**Comment by lee-dohm** [comment]
There is the [autohide-tree-view package](https://atom.io/packages/autohide-tree-view) that sounds like it does what you want @NicoTravassos.

**Comment by gterzian** [comment]
@mnquintana Sorry I'm a newbie, what do you mean with `Tree View: Toggle Side`?

**Comment by thomasjo** [comment]
@gterzian He is referring to the command `tree-view:toggle-side` which has the humanized name `Tree View: Toggle Side`. You can find it in the *Command Palette* which can be shown by pressing <kbd>cmd</kbd>+</kbd>p</kbd> or <kbd>ctrl</kbd>+<kbd>p</kbd> depending on your operating system

<img width="720" alt="untitled_-_atom" src="https://cloud.githubusercontent.com/assets/3622/9108793/e76806c4-3c30-11e5-87d0-1f2a6a690a57.png">

or via the *Packages* menu

<img width="570" alt="tree_view_and_packages_and_menubar" src="https://cloud.githubusercontent.com/assets/3622/9108797/f9a21190-3c30-11e5-87cb-1d52cbea2179.png">

**Comment by gterzian** [comment]
@thomasjo thanks :+1:

**Comment by izuzak** [comment]
Closing this since most of the things mentioned in the issue are possible, and the auto-hide one is possible via a different package (see https://github.com/atom/tree-view/issues/440#issuecomment-99075572). If there are any improvements you'd like to see related to that package -- I suggest you open them on that package's issue tracker. :v: Thanks for the feedback.
