### ISSUE TITLE
Toggle tree view doesn't work from keyboard

### ISSUE THREAD

**Issue by surdu** [atom/tree-view#441]
I am running Atom v0.196.0 on Windows 7 Professional SP1 and pressing `Ctrl+\` in order to toggle the tree view doesn't work.

When I use Keybinding resolver, it tells me I press `Ctrl+'`. Weird ...

**Comment by 50Wliu** [comment]
Are you using a non-English keyboard?

**Comment by surdu** [comment]
Nope:

![image](https://cloud.githubusercontent.com/assets/11520795/7510070/0e563602-f4a1-11e4-8c9c-ce6b37eba22a.png)

I am using an US Apple keyboard, but with the laptop's keyboard I have the same issue.

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by surdu** [comment]
Yes

**Comment by lee-dohm** [comment]
@surdu What keys do you physically press to type <kbd>Ctrl+\</kbd>? Does it include the <kbd>AltGr</kbd> key?

**Comment by surdu** [comment]
Nope, physically I press the same keys as "virtually?"  : <kbd>Ctrl+\

**Comment by surdu** [comment]
Hmmm... I just discovered that if I press <kbd>Ctrl+~ (on the mac keyboard is on the right of <kbd>Z ) it acts like <kbd>Ctrl+\ on windows. I never realized before today that this 2 keys have the same output on windows.

I guess it is a keyboard layout issue, though I don't understand why with the laptop's keyboard I have the same issue ...
