### ISSUE TITLE
new atom windows start with tree-view disabled

### ISSUE THREAD

**Issue by mgenev** [atom/tree-view#450]
So I have to enable them every time...

**Comment by lee-dohm** [comment]
If you start Atom from the command line and you start it with `atom .` it should enable the tree view. If you start it from the icon, it should open the last project you had open ... which if you closed it with the tree view open, should have the tree view open.

Is that not what you're seeing?

Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?

**Comment by romabysen** [comment]
The same thing happened for me too when upgrading from 0.198.0 to 0.199.0. With 0.199.0 the tree view does not show on start and it can't be toggled or shown. Downgrading to 0.198.0 fixes the problem so it seems likely it's a regression in 0.199.0.
I'm using Ubuntu 14.10.

**Comment by mnquintana** [comment]
@romabysen @mgenev Can you reproduce this in safe mode? (`atom --safe`)

**Comment by romabysen** [comment]
Yes, it's also missing in safe mode and it can't be shown or toggled.

**Comment by mnquintana** [comment]
Is that the case in every directory? Have you tried this with multiple different project directories?

**Comment by romabysen** [comment]
And then it starts working for me. That's odd. It seems something has changed in 0.199.0 in terms of how the atom command works. "atom ." in a directory now does what "atom" previously did. "atom" now opens the last open project and not the one in the current directory. I guess that was what confused me and made me think there was an issue. Still, I like the previous behaviour better but I guess it's just something one has to get used to.

**Comment by 50Wliu** [comment]
You could always alias `atom` to `atom .` :)
