### ISSUE TITLE
Add Project Folder when a folder is dropped in the Tree View

### ISSUE THREAD

**Issue by rgl** [atom/tree-view#458]
It would be nice to be able to Add Project Folder when a folder is dropped in the Tree View.

**Comment by billybonks** [comment]
https://github.com/atom/tree-view/issues/480 does this issue suffice your use case @rgl?

**Comment by rgl** [comment]
@billybonks it will!

**Comment by billybonks** [comment]
cool so you can close this issue and we will manage it from the one i linked.
