### ISSUE TITLE
Files with certain special characters are colored as new files

### ISSUE THREAD

**Issue by codyhazelwood** [atom/tree-view#460]
Tree view currently colorizes certain files incorrectly as new files if they have special characters in the filename.  I see this issue on ñ, but oddly Japanese characters don't cause the issue.

Doing a git status shows the working directory as clean.  This issue has persisted since at least Atom v.0.198.0.  Possibly related to issue #213, however I'm not running on a network drive.

OS X 10.10.3, Atom v0.204.0, tree-view v0.171.0.

![screen shot 2015-06-01 at 11 41 44 am](https://cloud.githubusercontent.com/assets/2680679/7917914/5ebcc80c-0853-11e5-8372-98bba69cfb2f.png)

**Comment by izuzak** [comment]
Yeah, it's not just the tree view -- it's the status bar as well. There's already an issue for this, but on the main atom/atom repository since it affects several things: https://github.com/atom/atom/issues/1890. I'm closing this in favor that issue -- thanks for the report. :bow:
