### ISSUE TITLE
Updated to latest atom master and Treeview is Reaped :D

### ISSUE THREAD

**Issue by v3ss0n** [atom/tree-view#466]
I just updated to lastest master https://github.com/atom/atom/commit/65831f1a4dff9dbcf68dbaf9b1d78b2617ed229a and now Atom Consider treeview is depreciated and sadly not allowed me to enable it :(

Rest in pieces Tree , i will make a table out of you :x: :grin:

**Comment by 50Wliu** [comment]
See https://github.com/atom/atom/blob/master/build/deprecated-packages.json#L1548-L1552.  It's still loading for me though :confused:.

**Comment by v3ss0n** [comment]
Thanks  now its fixed!
