### ISSUE TITLE
How to get sublime style tabs?

### ISSUE THREAD

**Issue by rdasxy** [atom/tree-view#475]
I read that the sublime tabs package was ended because tree-view started supporting it, however, I'm not sure how I can turn it on to use it.

It's not on by default.

Here's what I see when I go to settings:
![screen shot 2015-06-11 at 6 22 45 pm](https://cloud.githubusercontent.com/assets/1630626/8120644/1ef2f05e-1067-11e5-9e43-e3078a93c18d.png)

**Comment by mnquintana** [comment]
The option is in Tabs > Use Preview Tabs.

**Comment by 50Wliu** [comment]
Hi @rdasxy, it looks like you're either on a version of Atom that doesn't yet have the Preview Tabs option (please make sure you have at least 0.206.0 installed), or you have installed the Tabs package manually.

**Comment by rdasxy** [comment]
Thanks all! This is helpful.
