### ISSUE TITLE
Modified status (VCS) not updated for directories when repo is symlink

### ISSUE THREAD

**Issue by acontreras89** [atom/tree-view#484]
*Modified* status (VCS) is not updated for directories when the project is a symbolic link. Steps to reproduce:
* Launch Atom from inside a symbolic link to a repository
* Modify a file inside a directory with no VCS status
* Use command `Core: Save`

... Directory's VCS status should be set, but it is not...
* Use command `Windows: Reload`
* Modify the file again as to clear its VCS status (manually undo the changes)

... Directory's VCS status should be cleared, but again, it is not.

System info:
* Ubuntu 14.04 LTS
* Atom 0.210.0
* tree-view 0.172.0

**Comment by acontreras89** [comment]
@mnquintana, @benogle, can you guys take a look at this?
I also created https://github.com/atom/tree-view/pull/487 which solved the problem for me.

**Comment by izuzak** [comment]
This is semi-related to https://github.com/atom/tree-view/issues/69, see https://github.com/atom/tree-view/issues/69#issuecomment-59159891

**Comment by kankaristo** [comment]
I'm able to reproduce this, and as @acontreras89 said, this could be related to https://github.com/atom/tabs/issues/182.
