### ISSUE TITLE
After changing selectors, keymaps stop working

### ISSUE THREAD

**Issue by arielnoname** [atom/tree-view#486]
I had this:

'.platform-darwin .workspace .editor':

For several keymappings.
Because of the deprecation message, I changed them to 

'.platform-darwin .atom-workspace .atom-editor':

Now the keymappings don't work.

**Comment by 50Wliu** [comment]
Try `'.platform-darwin atom-workspace atom-editor':`

**Comment by arielnoname** [comment]
Nope =(
I've just updated to 0.210.0

**Comment by 50Wliu** [comment]
My apologies, I meant `'.platform-darwin atom-workspace atom-text-editor':`.  That should definitely work.

**Comment by arielnoname** [comment]
Like a charm
Thanks man

**Comment by 50Wliu** [comment]
Glad to hear it! :smile:
