### ISSUE TITLE
Git status colouring not showing for repos within a non-repo parent directory

### ISSUE THREAD

**Issue by robhawkes** [atom/tree-view#488]
I just noticed that when I open a directory in Atom that contains child directories that are Git repos, the status colouring in the tree and in the gutter fails to kick in. If I open one of the child repo directories on its own then everything is ok.

Will there be support for multiple, separate repo directories that are contained with a parent (non-repo) directory? I tend to open most of my projects this way as it means I don't need a separate window for each tiny module repo that I'm working on.

**Comment by izuzak** [comment]
Yeah, I agree that would be neat -- there's already an issue to track that request: https://github.com/atom/atom/issues/2203, so I'm going to close this in favor of that issue. :v:

> I tend to open most of my projects this way as it means I don't need a separate window for each tiny module repo that I'm working on.

One thing that might help here is the "Add project folder" option when you right-click in the tree view. That allows you to add multiple "root" folders to the tree view.

**Comment by robhawkes** [comment]
Awesome, thank you! I'll track that other issue. And in the meantime, I'll look into the Add Project Folder option.
