### ISSUE TITLE
Ignored names ignored when there is no .git directory in the project.

### ISSUE THREAD

**Issue by envygeeks** [atom/tree-view#489]
Often we use ignored names on local projects not ready for git just to hide files that will be cleaned, are temporary or otherwise not needed for the project by default, but ignored names is ignored when there is no .git directory inside of the project folder.

It would be nice if this weren't the case or if it's meant to be the case allow us to disable that requirement.

**Comment by denis-sokolov** [comment]
Perhaps you’re looking for the “Ignore Hidden Names” setting?
![image](https://user-images.githubusercontent.com/113721/40542306-53802d5a-6028-11e8-8741-514ddf169fd3.png)
