### ISSUE TITLE
When I expand a directory with a lot of files in it (200+) Atom takes a while to display the files

### ISSUE THREAD

**Issue by john-sparwasser** [atom/tree-view#491]
Looking at the profiler it looks like the file names may be hitting an edge case in the naturalSort function. The directory that is giving me problems is my database migrations folder, and all of the filenames start with a snakecase date, a unique identifier, then the name of the migration, eg: 2015_06_23_123456_create_users_table.php

**Comment by Soleone** [comment]
for what it's worth in my rails project (40000+ files) tree-view added 3000ms to start up time

**Comment by kieranklaassen** [comment]
+1

**Comment by john-sparwasser** [comment]
![Slow directory opening profile] (http://i.imgur.com/M4c7HUK.png)

Here is a screenshot of the profiler during the directory expansion.

**Comment by john-sparwasser** [comment]
Looks like the culprit may be: https://github.com/Bill4Time/javascript-natural-sort
Maybe there could be an option to turn on / off natural sorting?

**Comment by billybonks** [comment]
can you close this issue, fixed it with my previous pr @nathansobo

**Comment by john-sparwasser** [comment]
Thanks for looking into it further @billybonks.
