### ISSUE TITLE
reveal-active-file not always bringing the file into the viewport

### ISSUE THREAD

**Issue by Soleone** [atom/tree-view#496]
I use `tree-view:reveal-active-file` heavily and regularly the file does not actually appear in the viewport, i have to scroll (and find the right direction) to make it show on the screen. i have a feeling it happens when there are a _lot_ of files in the directory that's already open, it just stays at the current position instead of properly scrolling up or down.

**Comment by 50Wliu** [comment]
Hi @Soleone, what Atom version is this?  The bug you're describing should have been fixed by 1.0.0.

**Comment by Soleone** [comment]
Hm it is indeed `Version 1.0.0` i am using. Let me know if you want me to provide any more info.

**Comment by 50Wliu** [comment]
Can you see if this still happens in safe mode (`atom --safe`)?
/cc @viddo

**Comment by mnquintana** [comment]
@50Wliu It was fixed, but [tree-view wasn't updated on master till today.](https://github.com/atom/atom/pull/7573)

@Soleone The fix will be in the next version of Atom.
