### ISSUE TITLE
How ignore files pyc, pyo in side pane (tree files)

### ISSUE THREAD

**Issue by marioidival** [atom/tree-view#50]
![captura de tela 2014-02-27 as 22 40 52](https://f.cloud.github.com/assets/1129263/2290327/23c1342e-a01a-11e3-8782-a0c5e692fd8b.png)
![captura de tela 2014-02-27 as 22 46 17](https://f.cloud.github.com/assets/1129263/2290328/2821092c-a01a-11e3-8ba5-c2c054cad1f9.png)

Don't work

**Comment by marioidival** [comment]
This issue exist yet.

I tried with *.pyc, .pyc...

https://www.dropbox.com/s/p1kc7jy5jroyjj6/Captura%20de%20tela%202015-04-24%2000.07.33.png?dl=0

**Comment by netoxico** [comment]
@marioidival I just tried with `*.pyc` and worked fine

![calculator comunicaciongm com mx - atom 2015-05-06 14-36-56](https://cloud.githubusercontent.com/assets/540956/7501936/a71ea58a-f3fd-11e4-9564-38593051ab9f.png)

**Comment by slhck** [comment]
Any reason why this wouldn't be working?

![image](https://cloud.githubusercontent.com/assets/582444/8646341/53f70ece-294f-11e5-97b5-0a5dd0f684ca.png)

![image](https://cloud.githubusercontent.com/assets/582444/8646350/5da82a48-294f-11e5-9b66-e6d8b4e83095.png)

It's still showing `.pyc` files in the tree view, even after restarting.

Using version 1.0.2 on Windows 7.

**Comment by splashx** [comment]
errr.. how to edit the list of ignored files? can't see that options o.O

**Comment by slhck** [comment]
@splashx You just click in there, and type whatever names you want to ignore.

**Comment by splashx** [comment]
Right - I was so centered on the package settings. Thanks!

**Comment by raul1991** [comment]
The names that we type in ignoredNames are meant to disappear from the fuzzyFinder not from the treeView.. The title of this issue should be changed i guess..

Looking into this guide confirms this thing....

https://atom.io/docs/v0.186.0/customizing-atom

**Comment by slhck** [comment]
@raul1991 They are supposed to disappear from TreeView if you check "Hide ignored names" in the TreeView settings.

**Comment by raul1991** [comment]
I could not find this setting..Can you guide me ?

**Comment by slhck** [comment]
@raul1991 Go to *Settings » Packages*, search for `tree-view`, and click *Settings* on the `tree-view` package (under *Core Packages*).

There, you will find *Hide Ignored Names* under *Settings*.

**Comment by raul1991** [comment]
Okay here it is...I forgot everything is a package :-D ...

Thanks..
