### ISSUE TITLE
Adding folder to the project does not work properly in Ubuntu 12.04.5

### ISSUE THREAD

**Issue by romarcg** [atom/tree-view#502]
Every time I use the option Add Project Folder, it adds the entire home folder. After that, when I tried to add another folder, it does nothing else. I guess as it added the entire folder it does not duplicate it afterwards.

The problem is that I cannot add something properly. It always add the home folder no matter what I select.

I asked in the forum and they told me to add an issue to this repository.

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?  In addition, what Atom version is this?

**Comment by romarcg** [comment]
I have tried using `atom --safe` and the issue persists. I'm using atom 1.0.0. 

I have also cloned the repository and build the source code. The issue persists.  Before reinstalling, I have deleted the configuration files in my home directory (`.cache/Atom, .config/Atom, .atom`).

**Comment by romarcg** [comment]
I have tried using the same atom version in Ubuntu 14.04.1 and there this feature works properly. Do you think it has something to do with some library versions?

**Comment by wheleph** [comment]
I experience the same issue in Ubuntu 12.04. I would add that not only `Add Project Folder` does not work properly but also `Open folder...` with the same effect described by the reporter.

I found a workaround though. If you launch atom from terminal and provide the directory name(s) as a command line arguments then those directories are opened properly in the editor:
```
atom <dir 1> <dir 2>
```

**Comment by DSchalla** [comment]
Can confirm this issue under Ubuntu 12.04. Thanks for the hotfix, @wheleph 

Anything one can provide to debug it easier for you?

**Comment by rlarge** [comment]
Me too, must be something with 12.04 ubuntu.

**Comment by 50Wliu** [comment]
No reports since 2015 - if this issue still exists, please let us know!
