### ISSUE TITLE
reveal in treeview not highlight the corresponding file at first time

### ISSUE THREAD

**Issue by wayou** [atom/tree-view#504]
step to reproduce:
1. open a project in atom
2. open a file within this project
3. collapse the project in the treeview
4. right click within the opened file and select `reveal in treeview`
5. the project folder expanded but the corresponding file is not selected(or highlighted) in the treeview
6. repeat step 4 one more time, the file now is selected.

im using atom 1.0 on windows 7

**Comment by 50Wliu** [comment]
This will be fixed in the next Atom version, 1.0.1.
