### ISSUE TITLE
Copying folder content into one of its sub-folders

### ISSUE THREAD

**Issue by mhsallam** [atom/tree-view#509]
In the Files Tree View, when coping folder "A" into one of its sub-folders "A/B"; Atom gets into an infinity loop in which the same content  of the main folder "A" will be duplicated in the target sub-folder "A/B/A" (the first time is as desired) then again copies itself into the newly created sub-sub-folder (A/B/A/"B").. and goes on and on...

E.g: Coping folder FONTS/ into FONTS/FA will produce: "FONTS/FA/FONTS/FA/FONTS/FA/FONTS/FA/FONTS/FA/..." and will not stop until you close Atom.

**Comment by ungb** [comment]
I can still repro this. 

```
atom --version
Atom    : 1.15.0-dev-81e8ccc
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
I get a warning: 

ENAMETOOLONG: name too long, mkdir '/Users/bungdonuts/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a'

**Comment by rayfoss** [comment]
I get something similar with Symlinks, might be a different bug though

Given
```
$ ls -laht
this-dir -> ../
```

Trying duplicate that will crash Atom... when what I really want is just a copy of the folder with the symlink... I don't want to deep copy the resolved symlink which may take a while, crash and error out

![screen shot 2018-06-08 at 9 47 45 am](https://user-images.githubusercontent.com/876076/41164617-39649a6c-6b01-11e8-8237-8d721eef1a65.png)
