### ISSUE TITLE
'Tree View: Reveal Active File' doesn't scroll up

### ISSUE THREAD

**Issue by eboracus** [atom/tree-view#511]
Currently the `Tree View: Reveal Active File` command doesn't seem to scroll *up* the tree-view. Everything works going down, but when I try to jump to a file further up the tree the view goes down further (by a small amount).

Here is an illustration of this in safe mode:
![breadcrumb_treeview_scroll_up](https://cloud.githubusercontent.com/assets/11758299/8578790/bbef7d40-25a8-11e5-9a7b-5ec947f1a561.gif)

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.0.1-if you still see this after updating,  please comment!
