### ISSUE TITLE
request: add tree-view config item: "initial width"

### ISSUE THREAD

**Issue by pgnd** [atom/tree-view#520]
tree-view's initial width appears to be set to 200 px

``` less
    //styles/tree-view.less                                                                                                                           
        @import "ui-variables";

        .tree-view-resizer {
          position: relative;
          height: 100%;
          overflow: hidden;
          cursor: default;
          -webkit-user-select: none;
          min-width: 100px;
>>        width: 200px;
          z-index: 2;
```

It shows up in page style as

``` html
<div class="tree-view-resizer tool-panel" data-show-on-right-side="false" is="space-pen-div" style="width: 200px; display: block;">
```

the element.style width varies with click&drag on the scroller width, but can't be simply overridden/set in atom stylesheet with

``` less
    .tree-view-resizer {
      width:     300px;
    }
```

as the element-style appears to override that

For screens with large horizontal width, & in cases where default font-size has been increase, this is limiting, requiring a frequent, every-time-you-open, manual resize of the width

it'd be useful to have an "initial width" config option for tree-view, set to current default = 200px, which can be overridden on data entry

**Comment by pgnd** [comment]
Just fyi, nuclide's tree-view has an interesting approach (I'm not sure I do/don't prefer it ...), which is to init/open the tree to the maximum extent of the widest open folder/file path displayed.

It also auto-scales with closing/opening parents/children.

I think the init-width is a simple(r) 1st add; auto-scale might be a toggle-able 'nice to have'

**Comment by andruschka** [comment]
Did you try 
.tree-view-resizer {
     width:     300px!important;
}

**Comment by aioue** [comment]
@pgnd if you double click the divider it will auto-scale. IMHO this is better than resizing the left hand pane. With tree-view on the right and coding in a left-to-right language, auto-scale makes more sense as it does not move the line-number margin.

**Comment by pgnd** [comment]
@aioue 

I disagree.

'Your' solution requires a dubl-click at every window open.  Annoying and inefficient at best ...

'Mine', otoh, can be set once to my preference, and no longer requires any user interaction.

**Comment by bitmanic** [comment]
@andruschka That works, but you could also just set the `max-width` (without declaring `!important`) instead of the `width` property, like so: 

```css
.tree-view-resizer {
  min-width: 300px;
}
```

If you're implicitly overriding the `width` property, you might also want to hide the tree resizer handle from view: 

```css
.tree-view-resize-handle {
  display: none;
}
```
