### ISSUE TITLE
Add a "Copy Relative Path" item?

### ISSUE THREAD

**Issue by jpetitcolas** [atom/tree-view#523]
When right-clicking on a file, we already have:
- Copy Full Path
- Copy Project Path

What about adding a `Copy Relative Path` item, which would copy a path relative to current open file? For instance, with the following tree:

```
src/
    services/
        foo/
            Bar.js
    controllers/
        QuzController.js
```

If I am in the `QuzController` file, clicking on this item would put in the clipboard the string `../services/foo/Bar.js`. It would be especially useful as I often count the dot-dot-slash, wasting some development time. :)

**Comment by lee-dohm** [comment]
Sounds like a good idea for a package, personally.

**Comment by vladimir-tikhonov** [comment]
Just wrote a [package](https://atom.io/packages/tree-view-copy-relative-path) for that :smile:

**Comment by lee-dohm** [comment]
Awesome! Thanks @vladimir-tikhonov :grinning:

**Comment by stevemao** [comment]
Can this be closed :)

**Comment by jpetitcolas** [comment]
Sure, seems the previous package fits perfectly this need. Will give it a try. Thanks @vladimir-tikhonov. :)

**Comment by shulmanbrent** [comment]
This is amazing thank you
