### ISSUE TITLE
Put focus on filename input field when creating new file

### ISSUE THREAD

**Issue by adambuczynski** [atom/tree-view#531]
If the Atom window doesn't have focus, right clicking on a folder and selecting "New file" should put focus on the filename input field. Currently, this doesn't happen, so if your focus is in another window (e.g. browser), and you select "New file" and start typing, you'll actually still be typing in that other window, which is a bit odd since the mouse operation should bring focus back to Atom.

**Comment by adambuczynski** [comment]
Seems fixed in the latest Atom versions

**Comment by plonko** [comment]
I used keyboard shortcut 'a' instead of right-click > New file, and it focuses on the input. Awesome!
