### ISSUE TITLE
Performance Problem when expanding a folder with a lot of modules (e.g. "node_modules" with "npm@3")

### ISSUE THREAD

**Issue by serapath** [atom/tree-view#540]
`npm@3` flattens `node_modules` and now on most of the projects i'm working with, i can't really open that folder because my atoms performance just crumbles.

I guess, if the `tree-view` would just show the files/folders that currently fit into the visible area of the `tree-view`, that would speed up everything a lot.

**Comment by izuzak** [comment]
Thanks for the feedback, @serapath -- I think we can close this in favor of https://github.com/atom/tree-view/issues/449. If you'd like, please feel free to leave a comment there or just subscribe for updates. :pager:
