### ISSUE TITLE
Tree-view doesn't show some folders without any consistency.

### ISSUE THREAD

**Issue by YoungxHelsinki** [atom/tree-view#544]
(The issue is moved from https://github.com/atom/atom/issues/8016)

Hi all,

Before I begin, thank you for the great text editor :)

I'm using Mac OS 10.10.4 and Atom 1.0.2.
In one Django project, I have a path like ..../project/static/lib/bootstrap.....
Atom wouldn't show the lib folder at all. I checked the Atom setting whether I accidentally included that folder but I didn't.
I opened another Django project which also has lib folder. Atom shows that folder in this case.
![screen shot 2015-07-22 at 10 08 44 am](https://cloud.githubusercontent.com/assets/5738363/8815852/0be7088e-305a-11e5-8e11-467aee9e2990.png)

I thought it was weird but I decided to move on until I found another behavior.
I created /static/icon/ and it didn't show that folder either. 
![screen shot 2015-07-22 at 10 08 04 am](https://cloud.githubusercontent.com/assets/5738363/8815853/0be763f6-305a-11e5-918a-eaadb2a69f78.png)

Then I changed the folder name to 'icons' then it showed!!! I changed '/lib/' to '/libs/' then it also showed. I experimented with '/images/' but that folder always appeared in any case.

![screen shot 2015-07-22 at 10 08 26 am](https://cloud.githubusercontent.com/assets/5738363/8815854/0be7bbbc-305a-11e5-9bd5-45a15a45ac4e.png)

I think this is not an intended behavior. Any ideas?

**Comment by 50Wliu** [comment]
Can you please share the contents of `.gitignore` here?
Also, while the Tree View is focused, does pressing `i` show the hidden files?

**Comment by YoungxHelsinki** [comment]
Thanks for the quick reply. Here's my full .gitignore content.
```
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]

# C extensions
*.so

# Distribution / packaging
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*,cover

# Translations
*.mo
*.pot

# Django stuff:
*.log

# Sphinx documentation
docs/_build/

# PyBuilder
target/
```

I tried hitting ```i``` and it now shows the lib folder as hidden.
![screen shot 2015-07-31 at 12 21 52 pm](https://cloud.githubusercontent.com/assets/5738363/9000223/e21b962e-377e-11e5-9d19-4ee887a4c866.png)

**Comment by YoungxHelsinki** [comment]
Sorry guys.. This is embarrassing. I copied the .gitignore from someone else and lib was in the .gitignore.
