### ISSUE TITLE
Performance when other processes change files

### ISSUE THREAD

**Issue by deprint** [atom/tree-view#546]
I have a project folder which contains a few video files and a few normal text files (~250 total in ~20 subfolders). It's not like I have thousands of files so Atom's performance is pretty good, but there is one scenario where Atom becomes really unresponsive:
Sometimes I want to convert one of those video files in the background and it seems the changing file size triggers some sort of reload event:
![tree-view-performance](https://cloud.githubusercontent.com/assets/7817714/9099625/9a6d0684-3bd2-11e5-8573-9a69f5aef287.png)
![tree-view-performance2](https://cloud.githubusercontent.com/assets/7817714/9099628/9c118da2-3bd2-11e5-903c-5857e2a6c5e4.png)
It takes ~3 seconds just to scroll the tree-view without any files open and although the lag decreases when I reduce the number of files it is still very noticeable.

**Comment by glangford** [comment]
Is this fixed by #616 ?

**Comment by deprint** [comment]
Can confirm, #616 fixed it for me :+1:
