### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by devongovett** [atom/tree-view#55]
Would be awesome to be able to drag and drop files between folders in the file tree right in Atom. I like the text-based rename feature that lets you move files between folders, but drag and drop feels more natural to me having gotten used to it in TextMate.

**Comment by davidagraf** [comment]
+1

**Comment by mjrev** [comment]
+1

**Comment by SgtPooki** [comment]
I have moved back to sublime text as I've noticed too many issues with Atom and don't think it's ready for the prime-time yet, so hopefully someone else can pick this up and improve usage for both the expert and novice.

**Comment by xterr** [comment]
+1

**Comment by oleynikd** [comment]
+1

**Comment by wsargent** [comment]
+1

**Comment by shogoland** [comment]
+1

**Comment by itadakimas** [comment]
+1

**Comment by Jacajack** [comment]
I discovered that if I drag color from gpick to atom, atom crashes. I'm using Ubuntu 14.04.02 LTS 32bit.

**Comment by echantigny** [comment]
One of the things I miss a lot from other editors is the drag and drop into the code pane to create associated tags.  IE:  Create an img tag when an image is dragged in the code with correct relative path to the code file.  Is this something that could be part of this endeavor, another one or did I miss one that already exists?

**Comment by Wardrop** [comment]
+1

**Comment by jlphelps** [comment]
+1

**Comment by Glavin001** [comment]
+1 I can't believe this feature is not in Atom yet. I remember seeing this pull request a year ago and thinking "Sweet! Glad to know that feature will be coming soon!". Wow, was I wrong...

**Comment by chalisegrogan** [comment]
+1

**Comment by asleepinglion** [comment]
+1

**Comment by Adiel-Sharabi** [comment]
1+

**Comment by YvesMerl** [comment]
+1 :)

**Comment by alindsay55661** [comment]
+1

**Comment by mfoman** [comment]
+1

**Comment by markusbergh** [comment]
+1

@Wardrop As for that issue with Atom opening every file you could use this package for the moment: https://atom.io/packages/sublime-tabs

**Comment by garedean** [comment]
+1

**Comment by rubberbird** [comment]
+1

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! We can see that a lot of people want drag and drop in the Tree View (I do too!), but unfortunately the core team and maintainers don't quite have the bandwidth to take this on right now. However, we are always open to pull requests, and worst case scenario, one of us will get around to implementing this eventually. To keep this issue from getting too noisy I'm going to lock this for now.

**Comment by izuzak** [comment]
Basic drag and drop support was added back in [Atom 1.0.7](https://github.com/atom/atom/releases/tag/v1.0.7) (see https://github.com/atom/tree-view/pull/543 which implemented this) so I'm going to close this and unlock the thread. For bug reports and improvement suggestions about this drag and drop feature -- please open new issues. Thanks!

**Comment by joel** [comment]
Can we deactivate this feature?

**Comment by mikestopcontinues** [comment]
+1 for dragging into and out of tree-view. On mac, at least, this doesn't work.

**Comment by willviles** [comment]
Dragging and dropping from Mac to tree view causes this error:

<img width="450" alt="screen shot 2016-01-22 at 09 39 19" src="https://cloud.githubusercontent.com/assets/2046935/12507195/1fdd4006-c0ec-11e5-8b66-7fe5963294e1.png">

I may be going crazy, but I swear for a while I could drag in/out of tree view from the OS. Was this ever a feature?

**Comment by guyca** [comment]
+1

**Comment by logTom** [comment]
+1 .. I'm here and fedora (with nautilus) and get the same error as willviles.

**Comment by benediktdertinger** [comment]
+1

**Comment by mnquintana** [comment]
Since this issue was really just to track dragging and dropping files and folders within tree-view, and not from outside of tree-view or Atom itself, and that was implemented in #543, I'm going to lock this issue. You can subscribe to https://github.com/atom/tree-view/issues/480, or any of [the related drag and drop issues](https://github.com/atom/tree-view/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+drag+in%3Atitle), for updates as the drag and drop experience is refined over time. Thanks!
