### ISSUE TITLE
Expose Rename as a command

### ISSUE THREAD

**Issue by hkdobrev** [atom/tree-view#56]
There is a `Rename` option in the context menu. However it is not an exposed command. There is no exposed shortcut to rename the current file.

---

However I don't think this should be added to this package. The `MoveDialog` class and the Rename/Move command should be extracted to a new package. The `tree-view` package should be just that - a Tree View. It should just present a sidebar with files and connect the UI with the underlying commands for file system manipulation.

That being said other commands like Delete should be extracted as well.
I suggest creating a package enclosing all commands related to the file system.

**Comment by Cerberus** [comment]
On version 0.218.0 , the command exposed as `tree-view:rename`
