### ISSUE TITLE
Project Folders are forgotten

### ISSUE THREAD

**Issue by bobrocke** [atom/tree-view#560]
I can add project folders to the sidebar, but they are not retained over an Atom restart.

**Comment by thomasjo** [comment]
Can you elaborate a little? Some exact steps to reproduce what you're experiencing would be very helpful (including how you launch Atom). It would also be helpful to know if you're able to reproduce the behavior in safe mode (`atom --safe`).

**Comment by bobrocke** [comment]
OK, but nothing all that special. I:

- launched Atom from the command line in safe mode: `atom --safe`
- closed all open windows
- opened a window on `/Users/bob/Dropbox/SyncedSites/vhosts/www.br.dev` using File -> Open
- used the right-click menu to add a project folder at `/Users/bob/Dropbox/SyncedSites/vhosts/www.br.dev/user/pages` and it appeared in the tree view
- closed the window
- opened a window on `/Users/bob/Dropbox/SyncedSites/vhosts/www.br.dev` using File -> Open again
- No `/Users/bob/Dropbox/SyncedSites/vhosts/www.br.dev/user/pages` in the tree view

Did I not do something I needed to?

**Comment by thomasjo** [comment]
I don't think this is currently supported, but it might be a regression. /cc @atom/feedback @maxbrunsfeld

**Comment by bobrocke** [comment]
OK. I hope it's a regression because I love the feature but it's not very helpful if the status is not saved between sessions.

**Comment by maxbrunsfeld** [comment]
@bobrocke What you're describing is the expected behavior. When you explicitly open a single directory, we obey the command: open that directory. And we restore the state of the window from the last time you had *just that directory* open.

What you might want to do instead is open both directories at the same time, by selecting multiple paths in the file picker. Or, from the command line, `atom directory-1 directory-2`.

A third option would be to just quit Atom with your window open. Then, the next time you open Atom, we'll reopen the windows that you had open previously.

**Comment by bobrocke** [comment]
That's a bit ugly. I guess another solution would be an enhancement to Atom to give it a notion of a project and then all the folders associated with that project could be retained. Much like Sublime Text does now.

**Comment by thomasjo** [comment]
That's already available via the [project-manager](https://atom.io/packages/project-manager) package.

**Comment by bobrocke** [comment]
I hadn't tried project-manager until just now. It does part of what I'd like. Part of the problem is that projects can't be opened if no Atom windows are already open. Is that a limitation of Atom - that menus cannot work if no window is open?

**Comment by maxbrunsfeld** [comment]
@bobrocke Yeah, that's a good point. That is a limitation of Atom right now. I'm not sure if there's an issue for that already. Feel free to open one.

**Comment by bobrocke** [comment]
I opened one: https://github.com/atom/atom/issues/8603
