### ISSUE TITLE
Highlight git changes on the level of a project

### ISSUE THREAD

**Issue by jagi** [atom/tree-view#564]
Hi currently Atom is highlighting files in which there are git changes. However when you collapse project tree, a project name isn't highlighted. Because of that I have to unfold each project's directories tree to check whether I've made some changes. I'm working on several connected projects in the same time so that's why I think such feature would be handy. What do you think? :)

It would also be nice to have, next to the project name, an indicator showing how many commits have been made and are waiting to be pushed and what branch I'm currently on. Such feature is present for instance in Eclipse.

![atom](https://cloud.githubusercontent.com/assets/1051229/9665934/94cee2a8-5273-11e5-8cfb-32267f64d59f.png)

**Comment by mertkahyaoglu** [comment]
:+1:

**Comment by subesokun** [comment]
Happily helping out on that one as I've solved it already in my [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package. This way I could move this root node highlighting logic into the tree-view and remove it from my package :)

> It would also be nice to have, next to the project name, an indicator showing how many commits have been made and are waiting to be pushed and what branch I'm currently on. Such feature is present for instance in Eclipse.

Not sure if this logic should be part of the tree-view itself as it will blow up a bit the functionality but feel free to use my [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package as I've implemented it there already :)

**Comment by jagi** [comment]
Thanks! It's exactly what I wanted :)

**Comment by a7madgamal** [comment]
@subesokun life saver, thanks!

**Comment by a7madgamal** [comment]
I still think this should be implemented in this package too

**Comment by bretonics** [comment]
This seems to have already been addressed. I believe this issue should be closed.

**Comment by 50Wliu** [comment]
Yep, I think this is better off in a package.  Thanks for stepping up @subesokun :heart:.
