### ISSUE TITLE
Dragging files from OS into tree view yields error

### ISSUE THREAD

**Issue by rondonjon** [atom/tree-view#570]
I am using Xubuntu 14.04. When I drag a file from my desktop and drop it into a project (sub)folder in the atom treeview, I get the following two error messages ( /home/... is the project (sub)folder which I am dragging to ).

![screen](https://cloud.githubusercontent.com/assets/8258823/9783755/07182c60-57a7-11e5-9d73-ae723fb666ae.png)

**Comment by 50Wliu** [comment]
Are you running Atom 1.0.11?

**Comment by rondonjon** [comment]
yes

**Comment by geekish** [comment]
I get the same on OS X 10.10, also Atom 1.0.11, on any drag... within project or from the OS.

**Comment by james89** [comment]
Same with 1.0.19
