### ISSUE TITLE
Fold transpiled files of Typescript

### ISSUE THREAD

**Issue by betanubark** [atom/tree-view#571]
Hi all
I wonder if it's possible to implement a folding option for TypeScript like [WebStorm's one](https://www.youtube.com/watch?v=Sl1Uk3zT5Fg&t=33) so transpiled files are somehow more navigable and get a cleaner tree view.
Thanks in advance!

**Comment by tebanep** [comment]
This definitely would make Atom the best Editor/IDE for TypeScript!

**Comment by lee-dohm** [comment]
I'm going to mark this as a duplicate of the more comprehensive #572. Please subscribe there for updates.
