### ISSUE TITLE
deleting a file moves focus to project root directory

### ISSUE THREAD

**Issue by shawninder** [atom/tree-view#576]
Repro:

1. Navigate to a file in the tree view using the keyboard: `ctrl+0` + `down`*`x`
2. Delete a file: `backspace`
3. Press down key
4. Expect the file under the now deleted file to be highlighted
5. Observe the project root directory is highlighted

Deleting many files this way is a huge pain because for every file you are sent all the way to the top again.

**Comment by benogle** [comment]
Closing in favor of #60.
