### ISSUE TITLE
Tree-view Toogle keystroke is avoiding the use of  the symbol for  escape character 

### ISSUE THREAD

**Issue by DanielTuga** [atom/tree-view#577]
Tree-view Toogle keystroke is avoiding the use of  the symbol for  escape character. For example for C programming with Atom, I can not be able to use the  new line symbol like "\n" 'cause the following keystroke is executed:

alt-\   tree-view:toggle-focus  Tree View

**Comment by 50Wliu** [comment]
Are you using a non-US keyboard?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/577#issuecomment-141708952. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
