### ISSUE TITLE
Show in File Manager doesn't select the file in Fedora 22, Gnome, Nautilus system.

### ISSUE THREAD

**Issue by diazemiliano** [atom/tree-view#583]
Hi I'm having an uncomfortable bug when I use the `Show in File Manager` option. The file manager opens in the correct folder path but doesn't select or highlight that file.
I'm using Atom 1.0.19 with Fedora 22, GNOME Shell 3.16.3, GNOME nautilus 3.16.2. Thanks!

**Comment by ricardograca** [comment]
According to [this bug report](https://bugzilla.gnome.org/show_bug.cgi?id=632427) that feature is available in Nautilus since 2011. To use it you just open nautilus passing the full path to the selected file as second argument like:

    nautilus /home/user/projects/a_file.js

No idea how tree-view is trying to do it though.

**Comment by ricardograca** [comment]
Found the problem. The file name is purposely being removed on linux: https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee#L454 so that `xdg-open` doesn't try to open the default associated application.
