### ISSUE TITLE
folder indentation

### ISSUE THREAD

**Issue by benzen** [atom/tree-view#59]
it seems to me that the indentation of sub-folder in the tree view is too big.
I thinks it could be reduce of the half without make it difficult to follow the tree

**Comment by nottinhill** [comment]
this only changes padding to border of atom. how to do between arrow icon, folder icon and text ?

**Comment by caiollavos** [comment]
Thanks Man!

**Comment by fendiseptiawan0709** [comment]
For future readers.
You can use [@renz45's answer](https://github.com/atom/tree-view/issues/59#issuecomment-36479779). Here is some step to using it.

1. Click "Edit" in the menu bar. Select "Preferences". You could just using *Ctrl+,* keyboard shortcut.
2. Select "Open Config Folder" in settings menu. It placed in the bottom of settings menu.
3. Once you click, it will open new Atom window. It also show file directory in the tree view.
4. Select file "style.less"
5. Add the [code](https://github.com/atom/tree-view/issues/59#issuecomment-36479779). I'd prefer in the bottom of file.
6. Don't forget to save it.

Tested on : Atom 1.26.1 x64 Ubuntu
