### ISSUE TITLE
Disallow moving project folder

### ISSUE THREAD

**Issue by mnquintana** [atom/tree-view#590]
_From @Kroid on September 30, 2015 12:56_

Drag-ang-drop 'project folder' to another folder - bad feature, because undo is difficult. Maybe do not allow this or use copy instead move?

_Copied from original issue: atom/atom#9008_

**Comment by mnquintana** [comment]
_From @mitchellnemitz on October 7, 2015 17:40_

I quite literally just did this 3 minutes ago and almost paid dearly for it.

+1 please disable drag and drop for folders or enable undo folder move.

**Comment by mnquintana** [comment]
_From @arcticicestudio on October 8, 2015 7:17_

:+1: for avoiding accidentally moved folders or at least adding a setting to disable drag & drop for project folder

**Comment by mnquintana** [comment]
_From @philipgiuliani on October 8, 2015 18:20_

A confirm dialog when moving folders would also be nice! It happened so often to me. Good when you have git at least to see where its gone... :laughing:

**Comment by rozzy** [comment]
+1

it can be useful feature in case if you'll add prompt or undo-feature

**Comment by billybonks** [comment]
related issue information https://github.com/atom/tree-view/issues/566

**Comment by kennblvnp** [comment]
i dont see how this is fixed?
