### ISSUE TITLE
"Copy Project Path" returns a path with '\' on windows

### ISSUE THREAD

**Issue by capaj** [atom/tree-view#591]
I know this is actually right, but it is useless, because if I paste this path into a string in my code, it is not a valid path.
Could we just replace path separators, so we get a unix relative path always no matter which OS? No one uses '\' in paths and no one should. Even when developing on windows.

**Comment by thomasjo** [comment]
I'm sorry, but we are not going to change the current behavior. Even if we were to change this, it would essentially constitute a breaking change and as such would have to be postponed until Atom v2.0.0. Besides, why are you using path separators at all? Why not do be truly platform agnostic by using e.g. `path.join`?

As a workaround though, I propose that you create a custom context menu item via your `init.coffee` (or some such) that invokes the existing command, and replaces all `\` in the resulting path with `/`.

**Comment by capaj** [comment]
> Why not do be truly platform agnostic by using e.g. path.join?

 like you know-when I am writing a long require() parameter, I rather copy it from

> such would have to be postponed until Atom v2.0.0. 

Yes, I don't care if it is in a release 10 years from now. I just care that it ships eventually. Which it never will, because you closed this bug, right? Like you say- I will create my plugin, but this should really be default behaviour, or at least an option.

Yeah, you probably don't develop on Windows, so you don't really care, same with most other Atom contributors. You're basically saying fuck you windows users, get a Mac. Well I think it is kind of shame

**Comment by 50Wliu** [comment]
`require()` isn't the only thing that uses filepaths.  Changing the path separator to always be Unix-style would fix your require statements but break `cmd.exe` and other Windows applications that assume `\`.  The Tree View behavior also matches Windows Explorer, so to change the Tree View would be to make Atom inconsistent with other native Windows applications.  Therefore, the best option would probably still be to use the OS's default path separator.

As an aside, I develop on Windows.

**Comment by goldtreefrog** [comment]
If you paste a path with forward slashes in Windows cmd.exe, Windows handles it JUST FINE. It simply automatically converts all the forward slashes to back slashes. One can also copy and paste a path with forward slashes into Windows Explorer, and again Windows automatically converts all the forward slashes to back slashes.

So if we are keeping back slashes only to avoid breaking Windows, we are not taking into account that back slashes may not be breaking Windows after all. Perhaps somewhere it does, but not in anything I have done (yet) for Web development using a Windows OS (currently Windows 10 but I believe it was true on at least some of the earlier versions of Windows too).

**Comment by 50Wliu** [comment]
> If you paste a path with forward slashes in Windows cmd.exe, Windows handles it JUST FINE.

I don't really want to argue about this as the biggest reason this is not going to be changed is because of https://github.com/atom/tree-view/issues/591#issuecomment-147227588, but unfortunately that is not always the case.  Since `/` signifies arguments in cmd, it is sometimes ambiguous what a forward-slash is referring to.  See https://stackoverflow.com/questions/10523708/why-does-the-cmd-exe-shell-on-windows-fail-with-paths-using-a-forward-slash as one example.
