### ISSUE TITLE
create new file fails when a directory with the same name exists and vice versa

### ISSUE THREAD

**Issue by capaj** [atom/tree-view#593]
if I want to create a file named `a` in a path where I have a folder `a` it fails claiming that the file already exists, which is false.
The same with the folders- if a file `b` exists, creating a folder `b` fails.

**Comment by billybonks** [comment]
confirmed

**Comment by shemerey** [comment]
@capaj @billybonks It's more then just `bug` actually we can't create file with the same name as folder on the same level, it's more about `Unix` Architecture where everything is file and dir as well.

We can't create it in `node` `ruby` etc. So I think it's not bug.

**Comment by capaj** [comment]
@shemerey well surely you can call `fs.stat` and then `if (stats.isFile()) {}' to drive the logic needed here. Don't tell me that is broken as well, because that surely works.

**Comment by billybonks** [comment]
@capaj  what @shemerey  says is correct, you can only do this in windows. and it probably would work. what os are you running

**Comment by 50Wliu** [comment]
@shemerey is correct, this is an OS limitation.  Both Linux and Windows do not support creating files/folders with the same name.  Did a bit of searching and it appears that macOS also does not support this.  Closing as `wontfix`.

**Comment by shemerey** [comment]
👍
