### ISSUE TITLE
Expand filename when too large

### ISSUE THREAD

**Issue by anothergituser** [atom/tree-view#594]
Can the filename overflow to the right, over the editing area when the filename is too large to fit in the list? Something like phpstorm has

**Comment by billybonks** [comment]
this is probably non trivial, because of the way the dom is arranged. but there is a pr that adds a default browser tooltip when you hover over it, does that functionality suffice ? https://github.com/atom/tree-view/pull/609

**Comment by 50Wliu** [comment]
Also closing in favor of #557.
