### ISSUE TITLE
New project folders/files (aka green) are not showing up as new files in git.

### ISSUE THREAD

**Issue by middle8media** [atom/tree-view#597]
`icon` folder and it's files are all new, hence they are green.

![screen shot on 2015-10-14 at 11-21-12](https://cloud.githubusercontent.com/assets/1033332/10488231/b7e66f4c-7265-11e5-93a2-cf937ec3b85b.png)

but, they are not showing up as new committable files in git.

![screen shot on 2015-10-14 at 11-23-01](https://cloud.githubusercontent.com/assets/1033332/10488284/f7f9f37e-7265-11e5-84fa-88319d8dc902.png)

**Comment by glangford** [comment]
In case it is relevant in your situation, see comments in #213

**Comment by middle8media** [comment]
yes, thanks @glangford

**Comment by middle8media** [comment]
I adde `* text=auto` to a `.gitattributes` file and the "green" went away, but they are not being recognized as new files and are not present in the remote repo.

![image](https://cloud.githubusercontent.com/assets/1033332/10851487/c27e1448-7f01-11e5-8813-48059439148a.png)

![image](https://cloud.githubusercontent.com/assets/1033332/10851535/01c6c56e-7f02-11e5-8eec-b17721cce574.png)

**Comment by billybonks** [comment]
Im not sure whats the problem. in your initial message the new files where green but the `git status` didn't show that. that seems bugged.

in your latest screenshots, the files are not green, and  `git status` agrees that they havn't been added.

this sounds more of a git repo issue then an atom issue.

**Comment by abalter** [comment]
I just had this problem, and it turned out I had ignore the error from my last push. I had remote changes I needed to pull first.
