### ISSUE TITLE
Losing highlight focus on deletion of files/folders

### ISSUE THREAD

**Issue by JFickel** [atom/tree-view#60]
When you delete a file in a directory using the hotkeys, it'd be nice if the highlight focus moved to the next file or at least to the top of the directory that you were in so that you don't have to click back to where you were or scroll all the way down using the arrows. Right now the highlight focus disappears so if you press the down arrow, the highlight starts back at the top of the directory

**Comment by MEXdave1997** [comment]
Would like to help get on this, but not sure where to look in the project structure. Any ideas?
