### ISSUE TITLE
Menu key breaks when multiple projects folders are open

### ISSUE THREAD

**Issue by Tyriar** [atom/tree-view#611]
The menu key (typically next to right ctrl) seems to work fine with a single project folder. When used if there are two project folders are open it will select a seemingly random entry in one of the projects and launch the context menu.

Using Atom 1.0.19 and tree-view 0.187.0 on Ubuntu 15.04

![out](https://cloud.githubusercontent.com/assets/2193314/10561661/549e3326-74e9-11e5-82ce-606bc1586ee3.gif)

**Comment by 50Wliu** [comment]
Confirmed on Windows 10, Atom 1.0.19.

**Comment by 50Wliu** [comment]
Can no longer reproduce.
