### ISSUE TITLE
Proposal to fix performance of tree view lots of files

### ISSUE THREAD

**Issue by billybonks** [atom/tree-view#612]
this issue has been briefly discussed here https://github.com/atom/tree-view/issues/491

The change that caused this performance regression is: https://github.com/atom/tree-view/commit/b88af495e9e34fe3dfea2ec143ea643ca81f1a2e

i did some bench marks:
- NaturalSort package takes 17s to sort 539 files
- Original comparison method takes 9ms

As we can see it has a exponential performance impact.

The change indicated that this was a new default, but its the only option. The sort does not follow the posix standard that many developers are comfortable with. The main issue with atom adoption over sublime is performance.

I would love to know what sort order fs.readDir returns files and directories.

My proposed changes:
 - Make the default the original comparison function
 - Hide slow sort function behind a config variable
 - (optional) if fs.readDir returns items localeSorted, remove sort function completely

This will keep atom performant to improve adoption, and if someone wants the other sort they can enable it.

I spoke with @nathansobo about making this process async, but its not worth it when we can get a super quick win just off this change. personally i don't find it rational to wait for a sort that takes 17s sync or not.

perhaps we should add benchmarking test suites, to atom core and atom packages?

**Comment by nathansobo** [comment]
@billybonks Thanks for the investigation. My preference would be to either improve the performance of natural sorting when applied to paths or just remove it completely. Exposing an option that causes terribly performance seems unfortunate, even if it's optional.

@maxbrunsfeld, any thoughts here?

**Comment by maxbrunsfeld** [comment]
Yeah, I'm fine with simply removing `NaturalSort` if it performs that badly.

**Comment by billybonks** [comment]
closing this
