### ISSUE TITLE
Numbers are sorted before punctuation marks.

### ISSUE THREAD

**Issue by sftd** [atom/tree-view#620]
When files and folders are sorted in `files list` the order is following:

1. numbers
2. punctuation marks
3. letters

I think the right order should be:

1. punctuation marks
2. numbers
3. letters

Recently I started project where I have a few folder with names starting with number and as I'm using git for it the order is following:

- 1dir
- 2dir
- 3dir
- .git
- Adir
- Bdir

It's a little bit unintuitive for me. I would prefer to have `.git` folder on top.

Windows 8.1, Atom 1.0.19, tree-view 0.187.0

![screen](https://cloud.githubusercontent.com/assets/3073859/10716303/d1ac1760-7b34-11e5-83d0-82aa68e28285.PNG)

**Comment by billybonks** [comment]
struggling to recreate that sort order.

<img width="203" alt="screen shot 2015-10-25 at 9 35 55 pm" src="https://cloud.githubusercontent.com/assets/1640136/10715869/6ac07f9c-7b60-11e5-802c-c4dffd2ca120.png">

**Comment by sftd** [comment]
Ok... For some reason tree-view version in my Atom i stuck on 0.187.0 and doesn't update any further. I will report if problem still exist when I will manage to update tree-view.

**Comment by billybonks** [comment]
might be because i'm using the atom beta.

**Comment by Tyriar** [comment]
Reproduced on v1.0.19 and tree-view v0.187.0. Could this have something to do with the natural sort change that was reverted in 0.194.0 for performance reasons? https://github.com/atom/tree-view/commit/3ef7d75b82b3f16188858d152a977b7739ebfb3a https://github.com/atom/tree-view/commit/ca1d1f60e519ad646733802b466ba800488a8ae7

**Comment by Tyriar** [comment]
Confirmed that [`javascript-natural-sort`](https://www.npmjs.com/package/javascript-natural-sort) which is now reverted is what was causing the issue.

```
$ node
> var ns = require('javascript-natural-sort')
undefined
> ns
[Function: naturalSort]
> ['1', '.', 'a', 'A'].sort(ns)
[ '1', '.', 'A', 'a' ]
> ['.gitignore', '1', 'a', 'A'].sort(ns)
[ '1',
  '.gitignore',
  'A',
  'a' ]
```

This issue is probably safe to be closed.
