### ISSUE TITLE
File names green even when commited - non-ascii chars.

### ISSUE THREAD

**Issue by vjeranc** [atom/tree-view#625]
git represents čćžšđ differently.
Have files that are commited but still appear green.

git ls-files returns something below..

src/train.m
src/trainlms.m
"src/vje\305\276ba1-izvje\305\241taj.md"
"src/vje\305\276ba2-izvje\305\241taj.md"
tasks/vjezba_1.pdf
tasks/vjezba_2.pdf

It adds the apostrophe around those words above.

this is how they would look without direct numerical coding
"src/vježba1-izvještaj.md"
"src/vježba2-izvještaj.md"

**Comment by izuzak** [comment]
:wave: Bok @vjeranc :smile_cat:. I think you're seeing this issue: https://github.com/atom/atom/issues/1890, so I'm going to close this in favor of that issue. Let me know if I misunderstood your report, though. :v:

**Comment by vjeranc** [comment]
Yes, true, my skimming abilities failed me, 2014 seemed miles away for this not to be fixed :mag:
