### ISSUE TITLE
Files still highlighted even after pushed

### ISSUE THREAD

**Issue by thedaniel** [atom/tree-view#628]
_From @trd-leoalexander on October 27, 2015 6:42_

I'm really having problem lately recognizing which files I recently modifying after pushing a certain branch on github.com. Atom was not like this before, After each pushed it automatically clean my file explorer by removing all highlighted files but now it's not. 

![untitled](https://cloud.githubusercontent.com/assets/11266104/10751244/824f5016-7cb9-11e5-9578-787a4e0c1310.png)

Thanks. 

_Copied from original issue: atom/atom#9301_

**Comment by thedaniel** [comment]
Thanks for the report - a few questions:

- When your tree view is in this unexpected state, what does running `git status` from the command line, or opening the repo in GitHub desktop show?
- Can you reproduce it in atom's safe mode? 
- What version of Atom are you running?

**Comment by trd-leoalexander** [comment]
Here's what it show after making a command <code>git status</code>
![untitled](https://cloud.githubusercontent.com/assets/11266104/10783876/c51667fe-7d95-11e5-95b3-111a1c3132ad.png)

I am new to Atom, How will I got to safe mode, I am using windows.

Atom 1.0.19 <---- this is my version

**Comment by 50Wliu** [comment]
Open up the command prompt and type `atom --safe`.  You should see a blue or green square in the lower-left corner when Atom loads.

**Comment by trd-leoalexander** [comment]
Thanks. I did it, I can see a green box on the lower-left corner but it did nothing. Files that was already been pushed still highlighted.

**Comment by oxo42** [comment]
I am having the same issue.  I uninstalled atom and deleted `%appdata%\Atom` and `%userprofile%\.atom` and reinstalled.

Running `atom --safe` doesn't help.

git version 2.6.2.windows.1
Atom version 1.0.19

Additional packages I have installed

    C:\Users\oxle019\.atom\packages (34)
    ├── atom-beautify
    ├── atom-material-syntax@0.2.4
    ├── atom-material-syntax-light@0.0.3
    ├── atom-material-ui@0.6.2
    ├── autocomplete@0.47.0
    ├── column-select@0.2.0
    ├── editorconfig@1.2.0
    ├── feedback@0.38.0
    ├── file-type-icons@0.7.3
    ├── git-control@0.4.0
    ├── git-log@0.4.1
    ├── html-entities@0.4.0
    ├── language-docker@1.1.3
    ├── language-fp@0.5.4
    ├── language-gitignore@0.2.0
    ├── language-ini@1.13.0
    ├── language-nginx@0.6.1
    ├── language-powershell@2.1.0
    ├── language-puppet@0.15.0
    ├── language-r@0.4.0
    ├── language-splunk@0.1.1
    ├── linter@1.9.1
    ├── markdown-table-formatter@2.5.4
    ├── minimap@4.15.0
    ├── minimap-bookmarks@0.1.0
    ├── minimap-find-and-replace@4.3.1
    ├── minimap-git-diff@4.1.8
    ├── minimap-selection@4.3.1
    ├── python-nosetests@0.2.0
    ├── script@3.0.1
    ├── sync-settings@0.6.0
    ├── tablr@0.6.1
    ├── tree-view-git-status@0.2.2
    └── xml-formatter@0.9.1

**Comment by Zireael07** [comment]
Hmm, tried deleting atom storage folder and/or moving the repo?

**Comment by oxo42** [comment]
Which is the atom storage folder?  If you mean the one in `%AppData%` I have done that

**Comment by glangford** [comment]
See also #213

**Comment by oxo42** [comment]
Thanks @glangford. 

Adding `* text=auto` to `.gitattributes` works around the issue.

**Comment by trd-leoalexander** [comment]
I'm sorry for my ignorance but what exactly should I do about <code>.gitattributes</code>? and where should I save this? inside the project folder? or inside the <code>.git</code> folder?

What's in my mind is to create a file naming it with <code>.gitattributes</code>, but it saved as .txt file.

![atom](https://cloud.githubusercontent.com/assets/11266104/10899344/c5226e50-820e-11e5-9139-803311060787.png)

**Comment by 50Wliu** [comment]
Name it `.gitattributes.` (notice how it's surrounded by periods).  You can place it in the root directory of your git project.  A better(TM) solution would be to run the Git for Windows installer again and choose not to let Git modify line endings for you (the last option).  By default Git will try converting LF-->CRLF, which will make Atom think that the files are modified.

**Comment by trd-leoalexander** [comment]
Thanks for the quick response. I did the first way. I do it like below:

![atom](https://cloud.githubusercontent.com/assets/11266104/10899528/94e1bd16-8210-11e5-9069-be92a64fe329.png)

but, it was saved as .txt again.

The second way, so I should install again Git? Will try this. 

Thanks.

**Comment by 50Wliu** [comment]
Oh, you probably don't have the option enabled to always view file extensions.  Your best bet then might be to copy a `.gitignore` from somewhere and rename it (don't you love Windows), though I'm not even sure if that'll work.

**Comment by trd-leoalexander** [comment]
Also <code>.gitignore</code> is a .txt file. :(
![atom](https://cloud.githubusercontent.com/assets/11266104/10899847/f7013050-8213-11e5-8cab-28c431a38959.png)

**Comment by trd-leoalexander** [comment]
It's okay now, this solved my problem, I installed latest Git Version and followed the instructions below.

"A better(TM) solution would be to run the Git for Windows installer again and choose not to let Git modify line endings for you (the last option). By default Git will try converting LF-->CRLF, which will make Atom think that the files are modified."

Thanks @50Wliu.

**Comment by 50Wliu** [comment]
No problem!  Glad we managed to fix your issue :smile:.
