### ISSUE TITLE
Flush align files with folders

### ISSUE THREAD

**Issue by jantonypdx** [atom/tree-view#629]
Currently, if a directory contains both files & subdirectories, the alignment of files make them look like they are contained within one of the child subdirectories. For example in the image below, the file "/global/desktop/vars.json" looks like it is actually contained in the child "STG" subdirectory (e.g. "/global/desktop/STG/vars.json):

![alignment current](https://cloud.githubusercontent.com/assets/6666040/10767556/da37db2e-7c99-11e5-85b7-1fcbed0689a5.png)

Would it be possible to align files left so that they line up under the folder " > " icons instead, like this? 

![alignment wish](https://cloud.githubusercontent.com/assets/6666040/10767564/dfcf6228-7c99-11e5-91cc-49b97199915a.png)

Now, it looks like the subdirectories and files are all contained in the "/global/desktop" directory.

**Comment by thedaniel** [comment]
This sounds something that could be solved in a theme or your personal style - try adding this to your styles.less file:

```less
.tree-view {
  li.file.entry.list-item {
    margin-left: 0px;
  }
}
```

**Comment by jantonypdx** [comment]
Perfect. Thanks for the tip!
