### ISSUE TITLE
Add option to configure multiple root folders in tree-view

### ISSUE THREAD

**Issue by martndemus** [atom/tree-view#63]
Use case:
I have a project. In that project I have a few folders that are used often.
I'd like to access these quickly (and optionally be able to hide the others). I solved this in other editors by having the frequently used folders as root folders in the filetree.

Here is an example (of an typical Ruby on Rails project) how I'd do this:
```
_ app/
|_ assets/
|_ controllers/
|_ models/
|_ views/

_ javascripts/
|_ templates/
|_ models/
|_ application.js

_ stylesheets/
|_ application.css

_ my_project/
|_ app/
|_ config/
|_ db/
|_ README
```

This is much easier to browse and also takes up less horizontal space then:
```
_my_project/
|_ app/
  |_ assets/
    |_ javascripts/
      |_ templates/
      |_ models/
      |_ application.js
    |_ stylesheets/
      |_ application.css
  |_ controllers/
  |_ models/
  |_ views
|_ config/
|_ db/
|_ README

```

**Comment by ook23** [comment]
yes i would really like this too

**Comment by izuzak** [comment]
@maxbrunsfeld we can close this now since https://github.com/atom/tree-view/pull/368 was merged, right?

**Comment by izuzak** [comment]
Closing this -- it's possible to have multiple root folders now. #368 :tada:

**Comment by martndemus** [comment]
🍻

**Comment by craighooghiem** [comment]
Amazing. GoodbYe Sublime Text.

**Comment by craighooghiem** [comment]
I don't know that this feature is as good as it could be.
For example, in ST3 I can add a child folder as an additional root folder. This is not working in the latest build of Atom.

Example: I have a PHP project with a composer vendor directory. I have the main project open as my main root, but I also like to add a root folder of 
`vendor/COMPANYNAME/package/` so that I'm not destroying the sidebar by have 4 or 5 folder levels deep. 

When I try to add this in Atom it simply does nothing.

**Comment by benogle** [comment]
@craighooghiem can you make a new issue for this?

**Comment by fpupor** [comment]
I think that this function is really necessary, I use a lot in other editors

**Comment by izuzak** [comment]
@fpupor If you're referring to @craighooghiem's improvement suggestion, there's another issue for that here: https://github.com/atom/tree-view/issues/404

**Comment by danielpsf** [comment]
I'm thinking to myself how we could create a customized tree-view for different kind of projects, like:
![image](https://cloud.githubusercontent.com/assets/3307367/9140925/3aa13254-3d0b-11e5-9605-94672d147707.png)

For Grails projects. So +1 for this request.
