### ISSUE TITLE
Close subfolders when parent folder closes?

### ISSUE THREAD

**Issue by ponogam** [atom/tree-view#633]
Its very annoying when you open folder and all subfolder, which was opened in past session, are opened again. Maybe any settings exists or plugin to solve this?

**Comment by wdspkr** [comment]
There is a keybinding to recursive collapse a directory! I just found it. Just open the Settings for the Tree View Package and look for `tree-view:recursive-collapse-directory` to find the key combination for your system. (It's `alt-left` or `ctrl-alt-[` on mac).

**Comment by ponogam** [comment]
wdspkr, it's work! thx

**Comment by sdo91** [comment]
Is there any way to make this default behavior? I would like the `tree-view:recursive-collapse-directory` behavior every time I close a folder
