### ISSUE TITLE
Tree View Does Not Fill Parent Pane

### ISSUE THREAD

**Issue by eviljoe** [atom/tree-view#635]
Since Atom v1.1.0, the tree view is no longer filling its allocated pane (see screenshot).  The unused space cannot be right-clicked to bring up the normal context-menu for the tree view.

![atom-tree-view-not-filling](https://cloud.githubusercontent.com/assets/7276751/10846068/1f2231ee-7ee3-11e5-8cda-1da3e01151fd.png)

**Comment by geekish** [comment]
Seeing the same thing on Mac.

**Comment by 50Wliu** [comment]
This was fixed by #602 but was not included in the Atom 1.1.0 release.  Atom 1.2.0-beta1 contains the fix however.
