### ISSUE TITLE
Files/directories sorted in the tree view

### ISSUE THREAD

**Issue by jlecour** [atom/tree-view#64]
Hi,

I don't understand why some people can even like having directories grouped/sorted together, then files grouped/sorted together, but I respect that.

However, coming from a Mac only background, I'm very used to having all items in the tree view sorted alphabetically, regardless of their type, to have for example the `config` directory just near my `config.ru` file.

Is there a setting to do that ?
If not, it should be :)

Thanks a lot for making Atom and letting us play with it while in beta.

**Comment by damiendr** [comment]
Would also like the option to sort by date. My use case is note-taking, where it is convenient to display the most recently updated notes at the top (like Notational Velocity).

**Comment by 50Wliu** [comment]
@damiendr, could you please open another issue for this?  The directory/file sorting functionality that seems to be the main point of this issue has been fixed.

**Comment by damiendr** [comment]
@50Wliu done, just opened #343 for that.
