### ISSUE TITLE
Right click missing

### ISSUE THREAD

**Issue by Sogl** [atom/tree-view#647]
Hi!

How to enable right click on treeview to show context menu?
If we have one file, only right click on this file shows the menu:
![image](https://cloud.githubusercontent.com/assets/7556290/11106297/b7740c8c-8920-11e5-891f-66973541e2a4.png)

But if you click below - the menu doesn't appear:
![image](https://cloud.githubusercontent.com/assets/7556290/11106316/e1c22f50-8920-11e5-814b-4d37b5fd70c8.png)

I often use "Add Project Folder" and this problem is inconvenience.

Env:
Windows 7 x64
Atom 1.1.0
TreeView 0.190.0

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.2.0.  All the 1.2.0 betas should have this fix.
