### ISSUE TITLE
Copying and pasting a file with no extension adds 'undefined' extension.

### ISSUE THREAD

**Issue by Mr-Wallet** [atom/tree-view#648]
Normally when copy-pasting `fileName.txt`, we see this pattern:
```
fileName.txt
fileName0.txt
fileName1.txt
...
```

If the file being copied has no extension, it instead creates files with a new extension:
```
fileName
fileName0.undefined
fileName1.undefined
...
```

**Comment by 50Wliu** [comment]
What Atom version is this?

**Comment by Mr-Wallet** [comment]
Oops, sorry! This is 1.2.0 on Windows 8.

**Comment by 50Wliu** [comment]
Couldn't reproduce this myself (because of a different bug), but the issue seems to be here:
https://github.com/atom/tree-view/blob/4eea2f197ee4232e25fdf8f680c1dc6a98346bcf/lib/tree-view.coffee#L591-L592
