### ISSUE TITLE
Copying and pasting directories inside themselves has undesirable results

### ISSUE THREAD

**Issue by Mr-Wallet** [atom/tree-view#656]
Version 1.2.2, Windows 8.
- Select a folder `A` with file `x`.
- Perform a copy, then perform 3 pastes.
- The following structure results:

```
A
| A
| | x
|
| A0
| | A
| | | x
| | x
|
| A1
| | A
| | | x
| |
| | A0
| | | A
| | | | x
| | | x
| | x
| x
```

The paste operation is looking at the source path _at the moment of pasting,_ which is unintuitive. I would expect it to store a list of all file paths _at the moment of copying._

I'm not familiar with the exact effects of #631 but in 1.2.2, the effects of selecting the pasted item can be disastrous:
- Select a folder `A` with file `x`.
- Perform a copy, then perform a paste.
- Select the folder `A/A`.
- Perform a paste.
- The following structure results:

```
A
| A
| | A
| | | A
| | | | A
| | | | | A
| | | | | | A
...
| | x
| x
```

Atom locks up and continues making empty `A` directories until the application is forcibly closed.
When reproducing this issue, it's very easy to end up with file paths so long that Windows is unable to delete them. I found [rimraf](http://superuser.com/questions/78434/how-to-delete-directories-with-path-names-too-long-for-normal-delete) very helpful in cleaning up afterward.

**Comment by glangford** [comment]
Under #631 - this sequence causes an ENAMETOOLONG to be thrown (rather than generating tons of directories):

* Select a folder A with file x.
* Perform a copy, then perform a paste. [paste triggers reselection]
* Perform a paste.

**Comment by Ben3eeE** [comment]
Duplicate https://github.com/atom/tree-view/issues/509?

**Comment by Mr-Wallet** [comment]
The 2nd half looks like a duplicate, but the first half is not attested in 509, even though I believe they probably have a common cause.

**Comment by openks** [comment]
yes,I got the same result,it take me for half an hour to remove the useless folders, before i remove all the folders when i open the atom it continues make new folders... it's not easy to remove these folders beacse its too long for windows file system. something must be wrong with it,

**Comment by Ben3eeE** [comment]
@ungb can you reproduce this and check https://github.com/atom/tree-view/issues/509 also?

**Comment by ungb** [comment]
I can repro this.  

We should do what the OS does and not allow this behavior.  Neither mac or windows File Explorer allows this.

![image](https://cloud.githubusercontent.com/assets/5624870/22558835/ff86cb90-e923-11e6-83d2-96c81b570154.png)

![image](https://cloud.githubusercontent.com/assets/5624870/22558843/0744c01c-e924-11e6-8f1e-f33deafb7985.png)

**Comment by 50Wliu** [comment]
I just tried reproducing this with #1173 merged and was unable to, so I am assuming that this has been fixed.
