### ISSUE TITLE
"Move to trash" on network-mounts that have no trash.

### ISSUE THREAD

**Issue by digitalhitler** [atom/tree-view#659]
My Atom's `1.2.4` tree-view `0.195.0` running on OS X `10.11.1` is trying to "trash" files on drives that has no trash in it's filesystem:

![screen shot 2015-11-24 at 12 21 28 am](https://cloud.githubusercontent.com/assets/1048856/11350565/2bb60264-9243-11e5-9ec8-49e921375487.png)

When I choose 'Move to trash' nothing happens, file is still here.

To example, this issue can be replayed with SFTP-mount based on Transmit.app

Thanks for great code app!

**Comment by lee-dohm** [comment]
Atom isn't network aware, but this is a greater problem than just the tree-view. We've been tracking this mostly via atom/atom#3306.

**Comment by izuzak** [comment]
Yeah, I think we can close this in favor of https://github.com/atom/atom/issues/3306 which describes the same problem (nothing happens after selecting "move to trash" if the file is on a network drive). Thanks for reporting this, @digitalhitler, and sorry for the trouble.
