### ISSUE TITLE
Entries for collapsed folders with same ending folder name are duplicated when modified if "collapse directories" is selected

### ISSUE THREAD

**Issue by ilikebits** [atom/tree-view#660]
To duplicate:
1. `mkdir -p test/a/c test/b/c`
2. `atom test`
3. `cd test`
4. `touch a` or `touch b`

![atom-tree-view-collapse-name-bug](https://cloud.githubusercontent.com/assets/2092654/11431239/7e67502e-9448-11e5-9ff4-c298e4bb0eb4.gif)

**Comment by izuzak** [comment]
Thanks for the report, @ilikebits, but I can't reproduce this. 

![lice2](https://cloud.githubusercontent.com/assets/38924/11443530/2b7b5686-951e-11e5-8c22-9f8017b8af6d.gif)

Can you reproduce this in safe mode? Which version of Atom are you using and on which OS+version? 

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by ilikebits** [comment]
Yes, this still occurs for me in safe mode. I'm running Atom 1.2.4, using tree-view 0.195.0 on Ubuntu 14.04.3.

**Comment by ilikebits** [comment]
Here's my relevant config:
```
// ...
core:
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
      "*.pyc"
      "__pycache__"
      "*.class"
    ]
// ...
"tree-view":
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true
    squashDirectoryNames: true
// ...
```

**Comment by izuzak** [comment]
Thanks. I'm still unable to reproduce on OSX, so it might be something specific to Linux

**Comment by jfmengels** [comment]
Having the same issue here. I noticed:
- it only duplicates nested directories at the root level
- they only get duplicated when you save a file at the root level
- always two new ones appear
- for some reason it's always the same directory that gets duplicated, and if I try to create a new nested directory, the new one won't get duplicated.
- happens on Atom v1.2.4 and still happens in Atom v.1.6.0beta6 (I'm using Ubuntu 15.10).

I don't think it's linked to vim mode, as I don't use it.
Let me know if you want more information ;)

A similar issue was opened as #730, where @jyggen displays an example of this error, and it *looks* to me like he is on OSX

**Comment by jyggen** [comment]
I'm running OS X indeed. My colleague's got the same issue on OS X as well, we're still trying to pinpoint the cause.

**Comment by 50Wliu** [comment]
I can reproduce this as well on Windows 10 x64, Atom 1.7.0-dev-663d9b2.

**Comment by 50Wliu** [comment]
Cannot reproduce anymore, assuming fixed.
