### ISSUE TITLE
`Open Folder` results in some files not shown in tree view

### ISSUE THREAD

**Issue by NirmalL** [atom/tree-view#664]
* Some files are not shown in tree view when a folder is opened with **File --> Open Folder...**. Even in the Windows' native _File Select_ window, even more files are invisible.
![github issue](https://cloud.githubusercontent.com/assets/7931869/11522284/def0497c-98db-11e5-8146-f349470d8271.png)

* But at the same time, if I open the same folder from Windows Explorer, everything shows in the tree view.
![github issue 2](https://cloud.githubusercontent.com/assets/7931869/11522334/205d2b3c-98dc-11e5-8f41-fa80b1e6ba45.png)

* Also, opening a single file from Windows Explorer gives a folder-like entry in the tree view.
![image](https://cloud.githubusercontent.com/assets/7931869/11522451/1e421a5a-98dd-11e5-98f5-4fef218137cd.png)

Sometimes these issues come, and sometimes they don't. un-reliable behavior is disturbing as a developer might overlook files in the environment, leading to confusions and hours lost trying to figure out what happened with something in the project.

**Comment by 50Wliu** [comment]
Refs atom/one-dark-ui#109, atom/atom#9892.

**Comment by Ben3eeE** [comment]
This should be fixed by https://github.com/atom/one-dark-ui/pull/112
