### ISSUE TITLE
tree-view:remove-project-folder not working

### ISSUE THREAD

**Issue by GFernie** [atom/tree-view#665]
Neither using the command palette nor assigning a key binding seem to work when the project folder (or it's files) is selected and tree view is focussed.

Only right-clicking seems to work.

System Version: OS X 10.10.5
Kernel Version: Darwin 14.5.0
Atom Version: 1.2.4

**Comment by letientai299** [comment]
I got the same problems. The command is only work when using mouse (Right Click -> Remove Project Folder).
I'm using Atom beta 1.4.0-beta0 on Window 10.

**Comment by xHN35RQ** [comment]
I confirm. Ubuntu 15.10. Atom 1.4.1. The tree-view:remove-project-folder won't work via command palette.

**Comment by kaecy** [comment]
If anyone's looking for a work around you can add this to your init.coffee.
``` coffee
# removes the selected folder from the tree-view

atom.commands.add(
  "atom-wrokspace", "custom:close-project": (event) ->
    (atom.project.removePath(item.getPath()) if item.className.indexOf("selected" > 0) \
    for item in document.getElementsByClassName("tree-view")[0].children)
);
```
And add the command `custom:close-project` to a context menu or run it from command palette.
I just realized there's a bug when there's no more entries in the tree-view. Oh well.

**Comment by xHN35RQ** [comment]
Thanks. That does help. You have a typo: `atom.wrokspace` should be `atom.workspace`

**Comment by kaecy** [comment]
That last snippet doesn't work as intended. This new command works as intended and fixed the bug when there's no more entries unintendedly.

```coffee
atom.commands.add(
  "atom-workspace", "custom:close-project": (event) ->
    list = document.getElementsByClassName("tree-view")[0].children
    if list != undefined
      for item in list
        if item.className.indexOf("selected") > 0
          atom.project.removePath(item.getPath())
          break
);
```

> xHN35RQ  commented 2 hours ago  
> Thanks. That does help. You have a typo:  atom.wrokspace  should be  atom.workspace 

Thanks for the heads up.

**Comment by pgg** [comment]
v1.19.0
```
atom.commands.add(
  "atom-workspace", "custom:remove-project-folder": (event) ->
    treeView = document.getElementsByClassName("tree-view")[0].children
    if treeView != undefined && treeView[0].children != undefined
      for item in treeView[0].children
        if item.className.indexOf("selected") > 0
          atom.project.removePath(item.getPath())
          break
);
```

**Comment by kaecy** [comment]
@pgg Hey, thanks! Is that a fix for the new version of atom?

I don't really use atom anymore. I'm using something that's based on atom: vscode. I'm sure you heard of it.

**Comment by pgg** [comment]
@kaecy For v1.19.0 yes. Sure have, vscode is awesome. I am also really enjoying typescript!

**Comment by Eskander88** [comment]
> .0
> 
> ```js
> atom.commands.add(
> ```

Can you help me, pleace? How to install this solution and plugin `ctrl-shift-delete` shortcut?
