### ISSUE TITLE
Cannot delete file or folder (atom 1.3.0)

### ISSUE THREAD

**Issue by oh-ren** [atom/tree-view#666]
See subject. Answering `Move to Trash` to the delete dialog results in nothing.

Works fine in atom 1.2.4.

Windows 7 (zip file install)

This seems to be an Electron issue (since v0.34.3): atom/electron#3656 (`shell.moveItemToTrash`)

---
*[Moved from: atom/atom#9909]*
*[edit] ai, 666.. :P ;)*

**Comment by fruggiero** [comment]
I confirm this bug in 1.3.1 too .

**Comment by heisian** [comment]
confirmed, deletion no longer works

**Comment by Mohanson** [comment]
confirmed, too.

**Comment by klaas1979** [comment]
confirmed as well

**Comment by norwack** [comment]
Same in 1.3.2

**Comment by ApatheticG** [comment]
Confirmed in 1.3.2 at Windows 7.

**Comment by VoronaPavel** [comment]
Same on Win7 atom 1.3.2

**Comment by teej043** [comment]
Replicated on Windows 7, Atom 1.3.2

**Comment by rafster** [comment]
Can't delete files in "tree view"  using Atom  1.3.2 and  Windows 7 Home Premium

**Comment by njwangchuan** [comment]
Yes，on WIndows 7，“move to trash” do nothing，how to fix it?

**Comment by 50Wliu** [comment]
> how to fix it?

There is no known fix.  I'm working on upgrading Electron which will include the fix, but you'll have to wait a while (sorry).

**Comment by oh-ren** [comment]
Well, [a new 0.35 version (0.35.5)](https://github.com/atom/electron/releases/tag/v0.35.5) has been released with a fix ([discussion](https://github.com/atom/electron/issues/3656#issuecomment-167743658)). So instead of waiting for an Atom release based on Electron 0.36, a new 1.3 (and 1.4-beta) release could be done with an upgraded Electron 0.35?

In the meantime I'm on 1.2.4 myself. Not sure if I'm missing much from 1.3.

**Comment by 50Wliu** [comment]
Yeah, I'm aware of that.  We're still on 0.34 though which is the problem.

**Comment by oh-ren** [comment]
Oops, ah yeah, indeed, for a moment I assumed here Atom was @ 0.35...

**Comment by oh-ren** [comment]
Wouldn't it be worthwhile then to do a new 0.34 release with the fix (and perhaps other fixes)?
Also because, as it seems, Atom 1.4.0 will also be based on 0.34? Is there any *target* Atom release that should be based on Electron 0.35/0.36?

**Comment by Foamysworld** [comment]
Confirmed: 
OS: Win7 Pro
Atom: 1.3.3

**Comment by xDinomode** [comment]
Confirmed on win7 atom v.1.3.3
vscode is starting to look like the alternative atom...

**Comment by 50Wliu** [comment]
> Is there any target Atom release that should be based on Electron 0.35/0.36?

Not yet.  Atom running Electron 0.36 is *pretty much* ready, the only thing that's really blocking it at this point are a few rendering spec failures on CI that I can't reproduce on Windows.  I've been running it locally without any issues for around two, three weeks now.

**Comment by briantweed** [comment]
Currently using 1.4 on Windows7, still can't delete files ans haven't been able to for some time now. I surprised how frustrating this makes using Atom

**Comment by eduardogch** [comment]
Still Atom 1.4.0 on Windows 7 is unable to delete files

**Comment by 50Wliu** [comment]
We are aware of this issue, and are working on a fix.  Please refrain from confirming that this bug still exists.  Thanks!

**Comment by netsi1964** [comment]
Confirmed on ATOM 1.4.0 Windows 7: Delete is not working :-(

**Comment by 7upcat** [comment]
Atom 1.4.1 on Windows 7 can not delete file!!!!

**Comment by norwack** [comment]
>We are aware of this issue, and are working on a fix. Please refrain from confirming that this bug still exists. Thanks! - @50Wliu 

As stated previously, please refrain from confirming.

**Comment by keeper0811** [comment]
Atom 1.4.1 on Windows 7
Delete is not working !

**Comment by norwack** [comment]
@50Wliu Perhaps you should lock this issue.

**Comment by 50Wliu** [comment]
Thanks for the heads up @norwack.  We're almost done with the fix for this issue, and we'll provide updates as they arrive.

**Comment by 50Wliu** [comment]
From @edgarasf123:
***
This issue was really bugging me, and I just wanted to share my solution.

https://atom.io/packages/permanent-delete

keymap.cson
```cson
'.tree-view':
  'delete': 'permanent-delete:delete'
  'shift-delete': 'tree-view:remove'
```

**Comment by 50Wliu** [comment]
Sorry for the suuuuuper-long delay in fixing this!  We've finally merged the Electron PR, and at the current pace of development you should be able to delete files again starting in Atom 1.7.0.
