### ISSUE TITLE
Comma in path breaks Show in Explorer 

### ISSUE THREAD

**Issue by wrummler** [atom/tree-view#667]
Using 1.2.4 on Windows 7 64-bit. Reproducible with `--safe`.

Given the following folder/file structure,

```
~/test/here,/hello.txt
~/test/there/hello.txt
```

and having opened the `test` folder in atom, right-clicking `here,/hello.txt` and selecting "Show in Explorer" brings up the home folder instead of `~/test/here,`. Doing likewise for `there/hello.txt` brings up `~/test/there` as expected.

**Comment by 50Wliu** [comment]
Cannot reproduce - this has probably been fixed since it was reported.
