### ISSUE TITLE
Drag and Drop script, css, and image import

### ISSUE THREAD

**Issue by dtruel** [atom/tree-view#673]
In Netbeans, you can drag a js file from the tree-view into an HTML file, and Netbeans automatically creates the `<script src="path/to/file.js" type=text/javascript></script>` for you.  It does the same for CSS and Images.  This is really convenient if not using a templating language.  Any chance this could be added?

**Comment by mnquintana** [comment]
This sounds like a great idea for a package, but a bit out of scope for tree-view (as Atom is a general text editor, and not an IDE). Feel free to post this idea on [Discuss](https://discuss.atom.io/) and hopefully someone from the community will pick it up!

**Comment by dtruel** [comment]
Ok thank you!
