### ISSUE TITLE
Opening a file should focus on the opened file.

### ISSUE THREAD

**Issue by robballou** [atom/tree-view#677]
This is just a feature request I think, but when you select a file in the tree view to open it I think it should focus on the text editor.

Current flow:

1. Select a file in tree view
2. The file opens
3. Hit `cmd-R` to pull up the symbols list for that file, but it doesn't work because the focus is still on the tree view.

I couldn't find a command that would focus on the active editor ... so I guess that could also be a package (or part of this). If I get some time I may take a look closer to see if there is something to do on a PR level here. Thanks!

**Comment by lee-dohm** [comment]
Double-clicking the file in the tree-view will focus the editor. Also, <kbd>Ctrl+0</kbd> on OS X or <kbd>Alt+\\</kbd> on other platforms will toggle focus for the tree-view.
