### ISSUE TITLE
Opens blank document on startup for unmounted project tree.

### ISSUE THREAD

**Issue by garretwilson** [atom/tree-view#680]
If one of the project folders references an unmounted drive, the unmounted project folder will be disabled; this is correct and desired behavior. But if the project folder is unmounted, on startup Atom will get confused and also open up a blank document representing the unavailable project folder.

For example, imagine that on Windows 10 Pro 64-bit I add a project folder `X:\foo\bar`. If I later unmount `X:` and start up Atom, the editor will disable the `X:\foo\bar` project folder; this is correct behavior. But Atom will also upon startup open a blank document `bar`. I would expect no blank document `bar` to be opened to represent an unavailable project folder; this is a bug.

**Comment by jsejcksn** [comment]
I don't think this is bad behavior, because it shows consistency in reopening previously opened projects. I think it's a failed attempt to do so because the resource is unavailable. Perhaps a better solution would be to check for availability of the resource before regenerating the project window, and then if the resource is unavailable, presenting a dialog or notification to the user, informing them of the situation. The user would then be able to dismiss it.

**Comment by garretwilson** [comment]
>  ... if the resource is unavailable, presenting a dialog or notification to the user ...

No!!! It's common that you may not have some network drive mounted; that folder should simply be disabled until the drive comes back online. We all know what a gray disabled item in a tree means.

The behavior now is fine --- there's just no point in opening up a blank document for a _folder_ that isn't available. In the example I gave, there is no `bar` document --- there is simply a `bar` folder that isn't accessible. It works fine now, if Atom would simply not open up a `bar` document when it can't access the item.

**Comment by jsejcksn** [comment]
@garretwilson I misunderstood your message when I read it. After re-reading, I think that you worded it clearly—my fault. I thought you were talking about the whole project window.

**Comment by lee-dohm** [comment]
I agree this is a bug, though it isn't on the tree-view. Would you mind reopening it on atom/atom?

**Comment by garretwilson** [comment]
Hmmm... I figured that if I opened it on atom/atom, they would tell me to re-file it here. (sigh) :)

**Comment by mnquintana** [comment]
Closing in favor of https://github.com/atom/atom/issues/10330
