### ISSUE TITLE
Custom file manager for "Show in File Manager" action

### ISSUE THREAD

**Issue by fusion809** [atom/tree-view#685]
Hi,

I asked at [discuss.atom.io](https://discuss.atom.io/t/how-to-adjust-the-file-manager-used-by-atom-when-selecting-show-in-file-manager/24027/2) how to set the file manager used for the "Show in File Manager" action for this package and I was told that this feature does not currently exist, hence it is one I would have to request here in order to get it. I am running on the Linux distros Manjaro and Sabayon Linux and whenever I use this action in the treeview I open the folder in PCManFM. Setting my file manager using `xdg-mime default nautilus.desktop inode/directory` does not change the file manager used to open the folder. So I know that this is an issue the developers of this wonderful package will need to address in order for it to be fixed. 

Thanks for your time,
Brenton

**Comment by mnquintana** [comment]
`Show in File Manager` should be opening in your shell's default file manager – just to clarify, is that not what's happening?

**Comment by fusion809** [comment]
Certainly is not happening. Running `xdg-mime default nautilus.desktop inode/directory` sets my default file manager to Nautilus (GNOME Files) and despite this whenever I use the "Show in File Manager" action the folder is opened up in PCManFM, a **different** file manager.

**Comment by fusion809** [comment]
To be clear this is happening in **both** Manjaro Linux and Sabayon Linux. Even though I have set my file managers to different programs than PCManFM using `xdg-mime`.

**Comment by ambidot** [comment]
`inode/directory` was it; thanks

**Comment by bradonomics** [comment]
Has this been addressed? I'm getting the same behavior. I asked [on the forum](https://discuss.atom.io/t/show-in-file-manager-is-opening-browser/49416) before seeing this.

I'm running Ubuntu 17.10 with nemo as the default file manager. If VS Code is installed, it's opening that, if not, it's opening Chrome.

**Comment by daaru00** [comment]
Same problem using Ubuntu 17.10 with Nautilus, it open Google Chrome (even if it is not the default bowser) as file manager. How we can fix this issue? There's a workaround?

**Comment by bradonomics** [comment]
It seems like it's something with how Atom is compiled or packaged in the Ubuntu Software Center. I removed that version and added it from the [WebUp8 PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/atom) and everything works fine.

**Comment by daaru00** [comment]
Lot of thanks @bradonomics it works! I installed it not using Ubuntu Software Center but using snap, the error was the same.

So, the solution is:
If Atom is installed using Ubuntu Software Center remove it
```bash
sudo apt remove atom
```
or Snap 
```bash
sudo snap remove atom
```
Add  WebUp8 PPA repositories
```bash
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
```
Then re-install atom
```
sudo apt install atom
```
