### ISSUE TITLE
Access denied issues: Uncaught Error: EPERM: operation not permitted, scandir 'D:\MSOCache'

### ISSUE THREAD

**Issue by rugk** [atom/tree-view#687]
See https://github.com/adrianlee44/atom-aligner/issues/44

> But the real cause of this seem to be some directories, which Atom cannot access, because administrative rights are required (like `MSOCache` here).

**Comment by dlebedynskyi** [comment]
any news on this? bump

**Comment by paradoxxxzero** [comment]
Same thing on Linux, dup of #651, #671.

Step to reproduce:

```bash
mkdir dir
chmod -r dir
atom .
```

**Comment by rugk** [comment]
That's a workaround is not it?

**Comment by damieng** [comment]
Ideally the folder would have some indication it has no permission available but not crashing is I think the primary goal of this bug unless some other behavior was expected?
