### ISSUE TITLE
Rearrange project folders via drag and drop

### ISSUE THREAD

**Issue by KSXGitHub** [atom/tree-view#691]
When I add many projects to tree-view, I want to easily change their position without having to remove projects and re-add them.

**Comment by greenhoe** [comment]
This would be very helpful as it's a big pain when you need to add a folder to an existing project you have to pretty much recreate the entire project in the order you want the folders to appear rather than just rearranging the folder icons in a matter of seconds like you can do with Sublime.

**Comment by knzudgt** [comment]
This would be really helpful indeed, since most of the time we want the project we are working on to be at the bottom of the tree-view. It should be available the possibility to move any project folder up or down the tree-view.

**Comment by anothernode** [comment]
There is already a promising pull request for exactly this feature: https://github.com/atom/tree-view/pull/525

**Comment by marcopiraccini** [comment]
+1 for this feature. 
In the meantime, there's a way to change it manually? I didn't find where atom stores the project order...

**Comment by 50Wliu** [comment]
I would suggest that you wait for Atom 1.13-beta which is when this feature will become available

**Comment by marcopiraccini** [comment]
Ok, I will. 
But...at this point I'm just curious...where is stored the project order? If I change `~/.atom/storage/application.json` the order remains the same...

**Comment by 50Wliu** [comment]
Sorry, I don't know the answer to your question.  It may be stored somewhere in IndexedDB.

**Comment by adammenges** [comment]
excited for this, any idea on when Atom 1.13 will be out?

**Comment by Ben3eeE** [comment]
You can test it out today in the beta 🙂
