### ISSUE TITLE
Unable to delete files/folders from TreeView - File is shown as folder

### ISSUE THREAD

**Issue by claudio-b** [atom/tree-view#696]
Hello,

These issues have been notified before, however I can't find a fix. I have two problems that seriously affect me:

1) Unable to delete files/folders from tree-view - basically when I choose to delete something and confirm it (Move to Trash), nothing happens - neither the file on disk nor the file in the tree-view gets deleted. Same for folders.

2) Whenever I double-click a file and open it with Atom, in the TreeView, even if it's a single file, it doesn't show me the file extension icon, but it shows me like it's a folder.

**Comment by 50Wliu** [comment]
Hi @claudio-b, what OS are you on?

**Comment by claudio-b** [comment]
Windows 10 64-bit up to date.

**Comment by 50Wliu** [comment]
Ok.  I'm pretty sure your first issue is a duplicate of #666, and your second is a duplicate of #471 - please subscribe there for updates.
