### ISSUE TITLE
Root folder is displayed incorrectly when "Collapse directories" turned on and opening empty Git repo

### ISSUE THREAD

**Issue by lee-dohm** [atom/tree-view#697]
## Repro Steps
1. Turn off the "Collapse directories" setting in Tree View
2. Exit Atom
3. Create a new directory `~/test`
4. Execute the command `cd ~/test`
5. Execute the command `git init`
6. Launch Atom
7. Observe the normal Tree View appearance (see "Normal" screenshot below)
8. Turn on the "Collapse directories" setting in Tree View

**Expected:** Root folder display should not change from "Normal"
**Actual:** Root folder changes to "Broken" screenshot below

**Normal:**

<img width="216" alt="screen shot 2016-01-12 at 1 15 57 pm" src="https://cloud.githubusercontent.com/assets/1038121/12277176/dcdc2c50-b92e-11e5-8d0d-d16162ad20c1.png">

**Broken:**

<img width="199" alt="screen shot 2016-01-12 at 1 16 21 pm" src="https://cloud.githubusercontent.com/assets/1038121/12277186/e532b0c2-b92e-11e5-8df6-5b1c4db91edd.png">

**Comment by petemill** [comment]
I have also observed that when this happens, you cannot 'Remove Project Folder'.

**Comment by mishak87** [comment]
I have same issue with 1.7. and 1.8.0-beta1

**Comment by liuderchi** [comment]
@petemill issue #942 is discussing this.

**Comment by miguelcg** [comment]
@lee-dohm One question. If "Collapse directories" setting is set to true. What's the expected behaviour if you have the following directories: 

>rootFolder
│  directory1

Should it be shown squashed (`rootFolder/directory1`) or not (since it's the root directory)?

**Comment by lee-dohm** [comment]
That scenario is specifically described by my repro steps. It should not be shown squashed.
