### ISSUE TITLE
Tree View turns completely black - no files are showing

### ISSUE THREAD

**Issue by nirmoav** [atom/tree-view#701]
No files are showing on the Tree View, only after hiding & showing it, will it show for a brief moment,
and then go blank again.
Please fix this.

**Comment by 50Wliu** [comment]
@nirmoav Can you reproduce this in `atom --safe`?

**Comment by nirmoav** [comment]
Good call. I can't seem to reproduce it with "atom --safe".
Does this mean the problem might originate from some plugin?
Thanks!

**Comment by 50Wliu** [comment]
> Does this mean the problem might originate from some plugin?

Yes, most likely.  You can try using @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package to find out which one it is.
