### ISSUE TITLE
Creating or deleting file does not update folder's "collapsed" status.

### ISSUE THREAD

**Issue by phyllisstein** [atom/tree-view#702]
###### Steps to Reproduce
1. Enable the "Collapse directories" setting in the `tree-view` package.
2. Create a nested directory---for instance, `foo/bar`.
3. Create a new file under `foo`---for instance, `baz.md`.
4. Reload the window.
5. Delete `baz.md`.
###### Expected Behavior

The folders should "expand" from their collapsed state when a file is created, making `foo/baz.md` visible in the tree. Deleting `foo/baz.md` should collapse the folders again, now that `foo` has no children.
###### Actual Behavior

When creating a single child, it remains hidden and its parent remains collapsed until the window is reloaded. When deleting a single child, the parent remains expanded until the window is reloaded.
###### Demo

![collapse-demo](https://cloud.githubusercontent.com/assets/2207980/12379785/318f8e14-bd2f-11e5-9b09-465a6d88313b.gif)

**Comment by dingus9** [comment]
I was going to report this... I can verify that this is an issue as of tree-view#0.198.1 Same steps to reproduce as above with the addition of renaming a file into another sub directory also does not trigger a refresh.

**Comment by miguelcg** [comment]
This might be fixed by #1008

**Comment by 50Wliu** [comment]
I believe that only covers the deletion case, not the creation case.

**Comment by mcampagonzalez** [comment]
I'll check it and prepare a PR when I have some time :)
Even if it solved by #1008 it may be worthy to have a test covering this scenario.
Happy new year!

**Comment by miguelcg** [comment]
I'll check it and prepare a PR when I have some time :)
Even if it solved by #1008 it may be worthy to have a test covering this scenario.
Happy new year!

**Comment by miguelcg** [comment]
@50Wliu PR ready to review! #1012

**Comment by lee-dohm** [comment]
This is fixed in #1012. There are some alternative repro steps where it still occurs, but I'll file a new issue for those since the primary use case (creating and deleting files/directories through the tree-view itself) is fixed.
