### ISSUE TITLE
Ctrl/Cmd-Drag and drop should copy the selected file / directory

### ISSUE THREAD

**Issue by mattqs** [atom/tree-view#703]
Ctrl drag and drop in file tree does not create a copy of the file/directory (as it is in Visual Studio) instead it just moves the file.

**Comment by bananastalktome** [comment]
:+1: would be very useful to have!

**Comment by ahnbizcad** [comment]
Yes, currently, you can select multiple files and folders, but once you dry to move them by click dragging, it undoes all your effort and selects only the file you clicked, rather than the files you selected.

**Comment by yamsellem** [comment]
I guess `alt-drag` should copy on mac, to keep a consistent behavior with the os, don't you think?

**Comment by bhj** [comment]
Yes, when alt/option-dragging a file from Finder, the green plus sign indicates the file is being copied but is moved when released onto tree-view. I think this should be considered a bug. Furthermore the operation is not undo-able in Finder (not sure if that's possible to implement, but it does compound the issue)

**Comment by jcollum** [comment]
It looks like this was never merged in? #816 was closed for being a dupe. 

PR #800 appears to be unmerged.

**Comment by 50Wliu** [comment]
That's correct.  #800 has not been merged yet.

**Comment by Zelgadis87** [comment]
Any updates on this?

**Comment by egeland** [comment]
This would be really great to get merged in - I keep expecting it to just work, and instead it just moves my file...

**Comment by DeividasK** [comment]
+1 for merge

**Comment by TigersWay** [comment]
Any hope for this one?
Hoping to be able to copy files from explorer (windows) to Atom editor/tree-view.

**Comment by fonziemedia** [comment]
Please, someone fix/merge this..
