### ISSUE TITLE
Vertical scroll bar

### ISSUE THREAD

**Issue by KSXGitHub** [atom/tree-view#710]
![image](https://cloud.githubusercontent.com/assets/11488886/12527720/7d37927a-c1b3-11e5-8c12-86a594359406.png)

**Comment by lee-dohm** [comment]
Thanks for your feedback. This appears to be a theme problem:

<img width="501" alt="screen shot 2016-01-24 at 5 21 42 pm" src="https://cloud.githubusercontent.com/assets/1038121/12540491/ffbadcaa-c2be-11e5-95bf-d89186efd065.png">

If you would like us to take a deeper look at this issue, please feel free to add more details. See the [How Do I Write a (Good) Bug Report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) section of the CONTRIBUTING guide for suggestions.
