### ISSUE TITLE
File Deletion Temporary Fix

### ISSUE THREAD

**Issue by edgarasf123** [atom/tree-view#716]
Sorry for making new issue, but I wasn't able to comment in issue #666 . This issue was really bugging me, and I just wanted to share my solution.

https://atom.io/packages/permanent-delete

keymap.cson
```
'.tree-view':
  'delete': 'permanent-delete:delete'
  'shift-delete': 'tree-view:remove'
```

**Comment by 50Wliu** [comment]
Thanks @edgarasf123, I'll copy your comment over there.

**Comment by dlebedynskyi** [comment]
@edgarasf123 Thanks. hopefully they will fix this soon
