### ISSUE TITLE
tree-view on atom 1.5 beta incorrectly shows subtrees as "new" git files

### ISSUE THREAD

**Issue by chrishiestand** [atom/tree-view#717]
This problem only occurs when you tell atom to open a sub-folder of a git repository.

To reproduce:

1. Install atom 1.5 beta
2. `git clone git@github.com:atom/tree-view.git`
3. `atom-beta tree-view/spec` (alternatively use the gui and open this subfolder) 

Note that "git clean" files and folders are shown in green on tree-view. Sometimes when you open the file in atom the green will refresh to gray.

**Comment by lee-dohm** [comment]
Which OS are you experiencing this on?

**Comment by chrishiestand** [comment]
OS X

**Comment by alooffool** [comment]
I see similar behavior in Atom 1.5.0 on Windows 10.

If I click on a green file, the file opens and the tree colors are updated correctly, but when i restart Atom, the file colors revert to green.

I tried a few different UI themes and the issue persists.

**Comment by chrishiestand** [comment]
Looks like this may have been handled in atom/atom#10746. I'm still experiencing the issue on 1.5 and 1.6beta, but after the next release I'll update this issue about whether or not it's been fixed.

**Comment by lee-dohm** [comment]
@chrishiestand Yeah, I strongly suspect this is a duplicate of that Issue.

Also, the fix is in https://github.com/atom/atom/pull/10758 and we're working on putting out a hotfix for it today.

**Comment by chrishiestand** [comment]
@lee-dohm awesome, thanks!

**Comment by alooffool** [comment]
Thanks much!

**Comment by joshaber** [comment]
We just released 1.5.1 which fixes this. Thanks for all the reports and sorry for the hassle!

![](http://www.reactiongifs.com/r/swag.gif)

**Comment by chrishiestand** [comment]
@joshaber confirmed fixed, thanks!

**Comment by alooffool** [comment]
Same here--thanks again for the speedy response! :)
