### ISSUE TITLE
Nested files for typescript or any support for .map files for css or js file types . 

### ISSUE THREAD

**Issue by defyjoy** [atom/tree-view#720]
Is there a way to support nesting file for app.js and app.js.map under app.ts . It makes easier to find the typescript file or else it gets lost under lot of files . Need a feature very similar to [Microsoft File Nesting extension ](https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c), Can we do this for typescript or may be css/less . It'd be pretty handy to provide a grouping based on file names .

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/tree-view/issues/572. Please subscribe there for updates.
