### ISSUE TITLE
want to change the directory that the tree view shows

### ISSUE THREAD

**Issue by mitacDUO** [atom/tree-view#722]
hey,
something strange happened after i downloaded some files from github and now my tree view only shows the directory config and i'm not sure how to change it. what should i do?

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

Also try the following:

1. Completely exit all instances of Atom
1. Move or rename the `~/.atom/storage` directory
1. Restart Atom normally

**Comment by mitacDUO** [comment]
hi again, sorry about the long delay. 
according to the description the product version is 1.0.19, i'm running it on windows 10. 
ill have a go at the instructions your given me a bit later

**Comment by 50Wliu** [comment]
@mitacDUO The latest version of Atom is currently 1.5.3, so I highly suggest that you update as soon as possible (after following @lee-dohm's steps of course).

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/722#issuecomment-188503364 and https://github.com/atom/tree-view/issues/722#issuecomment-181514308. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
