### ISSUE TITLE
How to hook onto expand Directory

### ISSUE THREAD

**Issue by tomitrescak** [atom/tree-view#723]
Hi

I have an Atom plugin in which I add some buttons to the treeview.
These buttons show correctly, but they disappear when directory is collapsed as all child elements are removed.

How can I hook onto direcotry expansion so that I can automatically add elements as needed?

similar to that, how can I hook onto Selection change? Thanks!

Thanks!

**Comment by lee-dohm** [comment]
The tree view doesn't have an API for hooking these events currently. A proposal or PR for a well-designed API for these kinds of things would be welcome!
