### ISSUE TITLE
Allow tree-view to be set to bottom of window

### ISSUE THREAD

**Issue by james-lawrence** [atom/tree-view#729]
similar to https://github.com/atom/tree-view/pull/46

but at the bottom of the window. probably want to change 'show on right side' from a checkbox to a drop down.

**Comment by lee-dohm** [comment]
Thanks for the suggestion! While we think it could be interesting, we don't really want to support adding the tree-view to sides other than left and right at this time.

Thanks for your interest in Atom!

**Comment by james-lawrence** [comment]
left and right sides take up too much space on portait oriented screens.

**Comment by meech-ward** [comment]
It would be nice if I could use atom on a my portrait screen.

**Comment by gilad905** [comment]
+1

**Comment by nickjbauer** [comment]
+1 reopen this - "a tool you can customize to do anything"

**Comment by 50Wliu** [comment]
> from the atom.io homepage: "a tool you can customize to do anything"

Yes - this can be done in a package, and does not need to be included in the core tree-view package.

**Comment by icyrockcom** [comment]
@lee-dohm 

> While we think it could be interesting, we don't really want to support adding the tree-view to sides other than left and right at this time.


What is the rationale for such decision?

**Comment by lee-dohm** [comment]
> What is the rationale for such decision?

We have finite resources and have to determine where to best invest them.

**Comment by krasimir** [comment]
Did someone found an answer on this question. I'm also using a portrait monitor and the tree takes too much space. @icyrockcom
