### ISSUE TITLE
atom squashing directories duplicates directories whenever a file is changed

### ISSUE THREAD

**Issue by from-nibly** [atom/tree-view#730]
~~It looks like it has to do with the git highlighting as it doesn't duplicate if i modify a file that is already modified according to git.~~

looks like it has to do with vim mode.  When i hit `esc, :` it pops up the window and it looks like it redraws the whole window. It looks like this redraw causes the directories to be duplicated.

**Comment by jyggen** [comment]
I'm having a similar issue. Not sure what's causing it, but every time I save a file it duplicates some squashed directories (doesn't matter which or if there are any changes).

![730](https://cloud.githubusercontent.com/assets/264300/13073462/356f18ec-d49f-11e5-8088-20666471997c.gif)

**Comment by jfmengels** [comment]
Having the same issue here. I noticed:
- it only duplicates nested directories at the root level
- they only get duplicated when you save a file at the root level
- always two new ones appear
- for some reason it's always the same directory that gets duplicated, and if I try to create a new nested directory, that one won't get duplicated.
- happened on Atom v1.12.4 and still happens in Atom v.1.16beta6.

I don't think it's linked to vim mode, as I don't use it.
Let me know if you want more information ;)

**Comment by 50Wliu** [comment]
Closing in favor of #660.
