### ISSUE TITLE
Tree-view API is not being called on startup

### ISSUE THREAD

**Issue by azawawi** [atom/tree-view#732]
I am trying to use https://github.com/atom/tree-view#api in my https://github.com/azawawi/atom-perl6-editor-tools/blob/master/lib/file-icons.js#L12 to display custom file icons for Perl 6 file type. The problem is that `iconClassForPath(path)` is called only after a collapse/expand folder event and not on atom environment startup.

I have been trying to work around it via the following code but it is not working either.

```js
atom.workspace.getLeftPanels()[0].emitter.emit("tree-view:collapse-directory")
atom.workspace.getLeftPanels()[0].emitter.emit("tree-view:expand-directory")
```

Your help is appreciated.

**Comment by lee-dohm** [comment]
Right now I can't test this because you have a bug in your code. You don't `require` the Path module, so this throws an exception:

https://github.com/azawawi/atom-perl6-editor-tools/blob/master/lib/file-icons.js#L13

If you could fix that so I can investigate more, I'd appreciate it :grinning:

**Comment by azawawi** [comment]
Thanks for pointing it out. It is now fixed. However, it did not throw any exception when loaded. On startup, it is not calling `iconClassForPath(path)`. On collapse/expand, it works since it creates a new entry (i.e. https://github.com/atom/tree-view/blob/master/lib/file-view.coffee#L22).

Thanks for your time.

**Comment by azawawi** [comment]
@lee-dohm, Any update on this one?

**Comment by ssorallen** [comment]
It looks like a call to `@treeView.updateRoots()` after consuming the FileIcons service re-renders and gets the icons correct.

```
  consumeFileIcons: (service) ->
    FileIcons.setService(service)
    @fileIconsDisposable = service.onWillDeactivate -> FileIcons.resetService()
    @treeView?.updateRoots()
```

**Comment by azawawi** [comment]
Thanks.

Fix in https://github.com/azawawi/atom-perl6-editor-tools/commit/fa0339e332cb951e0c5d559e55d604eda95bb928 as a workaround. Please fix in tree-view.

@ssorallen :+1:

**Comment by lee-dohm** [comment]
@azawawi @ssorallen since you both are familiar with the fix, would one of you mind submitting a PR? I'm swamped with a kajillion other things at the moment and I'm not sure when exactly I'll be able to get free to work on this.

**Comment by azawawi** [comment]
@lee-dohm np, it is already there... https://github.com/atom/tree-view/pull/756

**Comment by lee-dohm** [comment]
Thanks! Sorry I missed it :laughing:

**Comment by azawawi** [comment]
Thanks :+1:
