### ISSUE TITLE
Atom tree-view does not mark files with uncommitted changes in the file system browser, again

### ISSUE THREAD

**Issue by nabeelomer** [atom/tree-view#735]
The problem reported in issue https://github.com/atom/tree-view/issues/725 and https://github.com/atom/atom/issues/10791 is happening again, and this time even the yellow lines on the left side of the editor are not appearing. Atom v1.5.3 Ubuntu 14.04.

**Comment by lee-dohm** [comment]
If a bug shows up again (often referred to as a "regression"), please post on the original issue so that everyone who is already subscribed there can be notified.
