### ISSUE TITLE
Cannot delete files through tree view

### ISSUE THREAD

**Issue by evrimoztamur** [atom/tree-view#745]
![2016-02-21_12-19-41](https://cloud.githubusercontent.com/assets/11677504/13203337/18ad6694-d8b6-11e5-99db-237a0118ef4b.gif)

As the GIF demonstrates, I am unable to delete (or send to trashcan) items through the tree view. I went through previous mentions of this issue, and noticed that certain ones were marked as closed or resolved. Unfortunately, that seems to not be the case.

**Comment by 50Wliu** [comment]
@evrimoztamur The fix for this will be in Atom 1.7.0.  Sorry for the inconvenience.
