### ISSUE TITLE
Preview file contents on click

### ISSUE THREAD

**Issue by elkwood** [atom/tree-view#75]
I've found that single clicking files in the tree view will open the file in a tab. This has been causing a lot of tab clutter as I am browsing through the files.
I'd like to see a single click not open a new tab but rather just preview the file contents.
A double click would open the file as a tab.
This functionality can be found in the Sublime Text tree view.

**Comment by phpprogrammer2015** [comment]
Copied from: https://github.com/atom/tree-view/issues/199
Hey, you should try to configure sublime-tabs plugin, which seems to be installed by default in recent Atom builds.

    Settings
    Packages
    Installed Packages
    Search for 'tabs' - it's a core package
    In its settings check 'Use preview tabs'
