### ISSUE TITLE
Show In Explorer unexpected behaviour

### ISSUE THREAD

**Issue by elemongw** [atom/tree-view#759]
**Reproduction Steps:**

1. File->Settings
2. In the treeview, write click on the config folder and select Show In Explorer
3. Internet explorer opens

**Expected behavior:**

The config folder is shown in explorer

**Observed behavior:**

Internet explorer opens

**Atom version:** 1.5.4
**OS and version:** Windows 7

Fresh install

**Comment by Ben3eeE** [comment]
Atom is not supposed to open that config folder in the tree-view when opening the settings. This has been fixed by https://github.com/atom/atom/pull/12694 and will be available in Atom 1.12.
