### ISSUE TITLE
Can't envoke tree view

### ISSUE THREAD

**Issue by Cw3D** [atom/tree-view#763]
After installing several terminal addons I can no longer invoke tree view.  I have uninstalled all addons and I'm back to vanilla atom but still no tree view.  Are there any any package repair options?  Running Debian 8 jessie, if it helps.

**Comment by 50Wliu** [comment]
@CW3D one of the packages you installed probably disabled tree-view.  You can try re-enabling it by searching for "Tree View" in Settings -> Packages and then enabling it.

**Comment by Cw3D** [comment]
Thanks I'll note that if it happens again.  I fixed it the old fashioned way -uninstalled then reinstalled- via apper package manager.

**Comment by 50Wliu** [comment]
Awesome, glad to see that you solved your issue.
