### ISSUE TITLE
Won't Enable on Startup

### ISSUE THREAD

**Issue by epochslee** [atom/tree-view#766]

**Comment by lee-dohm** [comment]
Please include more information. See the [How Do I Write a (Good) Bug Report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) section of the CONTRIBUTING guide for suggestions.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/766#issuecomment-195565477. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
