### ISSUE TITLE
Hide VCS Ignored Files doens't work. 

### ISSUE THREAD

**Issue by parmarsanjay** [atom/tree-view#767]
I have latest version of Atom. For some reason Atom is not hiding files in tree view based on .gitignore file in my project. 

![2016-03-11_15-14-12](https://cloud.githubusercontent.com/assets/1390072/13718139/f51f8e1a-e79b-11e5-8bf7-6ff3f777574e.png)

**Comment by lee-dohm** [comment]
From the look of the icon, the root folder is not a Git repository. The VCS ignored files feature doesn't operate unless there is a version control system, in other words Git. If you run `git init` in the root directory there, things should start working.

This is what the icon looks like when the root directory is a Git repository:

<img width="345" alt="screen-shot-git-repo-icon" src="https://cloud.githubusercontent.com/assets/1038121/13720934/c4a65d42-e7cb-11e5-843b-86084c6c94e3.png">
