### ISSUE TITLE
Hide after opening pane.

### ISSUE THREAD

**Issue by nixpulvis** [atom/tree-view#775]
I'd like the tree-view to hide automatically after opening a pane, and I could see this being a feature a lot of people might like.

It reinforces that you've lost focus of it, and need to perform some keystroke for opening/refocusing on it.

**Comment by Alhadis** [comment]
Optional of course, though, right?

**Comment by nixpulvis** [comment]
Yea this would be an option for sure, probably off by default too.

**Comment by abejfehr** [comment]
There's an Atom package called [autohide-tree-view](https://atom.io/packages/autohide-tree-view) that does exactly what you're asking. That being said, this would be a nice feature to have in the official tree-view package

**Comment by lee-dohm** [comment]
Since the [autohide-tree-view package](https://atom.io/packages/autohide-tree-view) exists, I'm going to close this. If someone wants to submit a PR for this functionality and needs help landing it, please let me know.
