### ISSUE TITLE
Files no longer opening in new tab

### ISSUE THREAD

**Issue by Alhadis** [atom/tree-view#776]
I just upgraded to Atom 1.6.0, and for some reason, anything I click in the tree view opens in the currently-open tab instead (replacing the current file, instead of creating a new tab).

<img width="432" src="https://cloud.githubusercontent.com/assets/2346707/13868731/039da042-ed20-11e5-99bb-11b1002d5fac.gif" />

For some reason, it's also italicising the text of the tab as well. Weirdly enough, it only italicises tabs that *haven't* been opened by directly clicking on a file in the tree view (such as if hitting *"Reopen Last Item"*). Even weirder, these particular tabs don't get replaced by the behaviour described above:

<img width="548" src="https://cloud.githubusercontent.com/assets/2346707/13868762/7ab31810-ed20-11e5-8b0e-371151254dae.gif" />

### System specs
* Mac OS X 10.9.5 (Mavericks)
* Atom 1.6.0
Running this in safe mode, behaviour's the same with or without packages enabled.

**Comment by Alhadis** [comment]
If it helps to locate the issue, the italicisation is being applied by a class called `.temp`:

<img width="384" src="https://cloud.githubusercontent.com/assets/2346707/13868830/34ea6120-ed21-11e5-8711-3cb050ef0d44.png">

**Comment by 50Wliu** [comment]
This is a new feature in Atom 1.6.0 called pending tabs.  You can learn more about it at http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html.

**Comment by Alhadis** [comment]
> "It's not a bug, it's a feature!"

Ah, how those words will never die.

Thanks for the clarification. =)

**Comment by KSXGitHub** [comment]
Sorry for off-topic, but it seems this issue should be placed [here](https://github.com/atom/tabs/issues)

**Comment by Alhadis** [comment]
Erm, I wouldn't say so. The `tree-view` package appears directly responsible for interacting with the filesystem, whereas the `tabs` package appears UI-related only.
