### ISSUE TITLE
Request: Use clipboard to copy/cut/paste files/folders in projects panel

### ISSUE THREAD

**Issue by KSXGitHub** [atom/tree-view#778]
Right-click context menu provides an options to copy/cut/paste items. And sure, I can copy/cut/paste from any location to any other location in the projects panel, but just in the projects panel.

So I guess that tree-view doesn't use clipboard to store these items, it's might be useful if it can communicate with OS and other programs, especially File Explorer. Is that possible?

**Comment by AndreaGriffiths11** [comment]
@lee-dohm Could you please take a look here?

**Comment by lee-dohm** [comment]
Thanks for your submission!

This is almost certainly possible, but isn't something that the maintainer team is going to work on in the near future. We agree that this would be helpful for some workflows but we have many other features that are higher priority than this one. We would be open to receiving a well-crafted PR for this though, so I'm going to mark this `help-wanted` and close it.

Thanks again for your interest in Atom.
