### ISSUE TITLE
Filename with italics requires a double click to stay

### ISSUE THREAD

**Issue by jwoertink** [atom/tree-view#781]
I'm not sure if this is a bug, or just an unwanted feature, but after updating I now have to double click each file for it to stay open. Just doing a single click will keep replacing the file that I'm looking at. I noticed that when I first click on the file I want to view, the name at the top of the tab is all in italic. Once I double click that file, then it becomes normal and I can open a second file.

If this is a new "feature", how do I disable this? If it's a bug, then what do I need to add so it can be fixed?

**Comment by jwoertink** [comment]
never mind. I just found an option called "pending pane items" that disables this.

**Comment by vesrah** [comment]
Quite annoying that this was added as a default.  This is the first Google result for this issue and will probably help many people.

**Comment by 50Wliu** [comment]
@vesrah Sorry to hear that you were having trouble.  This feature is documented under the 1.6.0 blog post (http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html), though I agree that the change definitely could have been communicated better.

**Comment by jasontenbrink** [comment]
Really glad this comment was here.  Saved me a lot of frustration!  Also glad it's still the first result when google comes up.

**Comment by RonnieOnRails** [comment]
Alleluia !
