### ISSUE TITLE
Drag-move multiple files and folders

### ISSUE THREAD

**Issue by ahnbizcad** [atom/tree-view#785]
If you select multiple files and folders in the tree view, and then try to drag-drop move them into another folder, it will forget what you selected, and select just the item you clicked, rather than all of the items you selected. 

This makes it impossible to move multiple files and folders en masse, like you can with any other GUI file system 

(Atom should be more advanced than Filezilla)

**Comment by anderoonies** [comment]
![tree-multi](https://cloud.githubusercontent.com/assets/6645121/14186641/ea8afa9e-f744-11e5-8028-d56b49a16844.gif)
took a stab at this [here](https://github.com/anderoonies/tree-view/tree/multi-drag), going to write specs and push those up

**Comment by alias1** [comment]
Duplicate #232

**Comment by 50Wliu** [comment]
Thanks @alias1.
