### ISSUE TITLE
Tree View pane on the right hand side

### ISSUE THREAD

**Issue by ranieribt** [atom/tree-view#786]
Hi, I'm coding with Atom from Ubuntu 14.04 64bit. When I open a project folder, the TreeView pane is being displayed on the right hand side. Before it was on the left. Is this a issue? How can I bring back the defeult display?
Many thanks,
Ranieri

**Comment by marcong95** [comment]
Hi, Ranieri. I found an option ```Show On Right Side``` in the settings of tree-view packages just now. You can check if this option has been checked in your Settings.

**Comment by ranieribt** [comment]
A-ha! Great! Many thanx to you, marcong95! keep coding

**Comment by 50Wliu** [comment]
Glad you fixed your issue @ranieribt!

**Comment by adamsiwiec** [comment]
I couldn't Show on Right Side, but I did find `Tree View: Toggle Side`

**Comment by inoas** [comment]
Doesn't work for me sadly.
After Atom re-installation it is back to the left side and hitting "Toggle Side" does nothing.
Atom 1.20.1 - MacOS 10.12.6

**Comment by rsese** [comment]
@inoas - please see https://github.com/atom/tree-view/issues/1186 and https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762.  If you still have trouble, feel free to post on https://discuss.atom.io/ and ping me (I'm @rsese there too).

**Comment by martinbuezas** [comment]
You can just drag it now
