### ISSUE TITLE
Folders lost when using Open with Atom

### ISSUE THREAD

**Issue by marcong95** [atom/tree-view#788]
Hi. When Atom is closed and I right-click a file and choose ```Open with Atom```, all folders in the tree-view will be replaced. How can I avoid this replacement?
Thanks,
Marco

**Comment by Zireael07** [comment]
You can't for now. See atom/atom for explanations why, search for "launch story confusing"

**Comment by 50Wliu** [comment]
Closing as a duplicate of atom/atom#10183 - feel free to subscribe there for updates.
