### ISSUE TITLE
Move to trash still not working on Windows 10 in Atom 1.7.0

### ISSUE THREAD

**Issue by manuelbieh** [atom/tree-view#806]
Sorry for "re-opening" this issue again but the original issue (https://github.com/atom/tree-view/issues/666) was limited to collaborators only.

@50Wliu wrote:
> Sorry for the suuuuuper-long delay in fixing this! We've finally merged the Electron PR, and at the current pace of development you should be able to delete files again starting in Atom 1.7.0.

I have updated to 1.7.0 and still get the error:
![error](http://i.imgur.com/E77ClTY.png)

I'm using Windows 10 and tried to delete a file which is not within my %USERPROFILE% using right click in the tree-view -> Delete -> Move to tash.

I used the auto update function in Atom to update to 1.7.0

**Comment by 50Wliu** [comment]
And if the file is in your `%USERPROFILE%`?

**Comment by manuelbieh** [comment]
Same problem :weary: 

![error](http://i.imgur.com/1pYUBz4.png)

**Comment by manuelbieh** [comment]
I tried running Atom as Administrator but it still doesnt work. My user account also has admin rights. And it is on Windows 10 Professional. Do you need any other information?

**Comment by ashevch** [comment]
Noticed similar behaviour if there additional directory inside the one I try to delete, if delete inside dir deletion of the parent become successful in my case.

**Comment by abejfehr** [comment]
I think the business logic for file deletion is actually handled in the [electron](https://github.com/electron/electron) project. There's an [issue there](https://github.com/electron/electron/issues/4974) about deleting not working if the recycle bin is set to immediately delete files...is that the case for you @manuelbieh?

**Comment by manuelbieh** [comment]
Indeed it is! I will check it out!

**Comment by 50Wliu** [comment]
Haha, that's actually my issue...don't know why I didn't think of that previously :/.  Closing in favor of the upstream issue.
