### ISSUE TITLE
Single-click no longer opens files when core.allowPendingPaneItems is false

### ISSUE THREAD

**Issue by MiracleBlue** [atom/tree-view#807]
In the latest update to Atom 1.7.0, single-click no longer opens files when allowPendingPaneItems is false.  I noticed in the tree view spec file that this is expected behaviour (https://github.com/atom/tree-view/blob/1a3eab1ed0cc3e4610077b953dbc5a0e24d46c4e/spec/tree-view-spec.coffee#L612), but is a real pain for me.  Is there any possibility of adding a setting to enable single click open behaviour without the pending option?

**Comment by 50Wliu** [comment]
Please subscribe to #804 where discussion is taking place over how best to re-implement single click behavior.

**Comment by MiracleBlue** [comment]
Whoops, sorry for the duplicate!  I tried looking for similar issues but didn't see that one.  Thanks!

**Comment by 50Wliu** [comment]
No problem, most people (including me!) don't think to search the open PRs as well :).
