### ISSUE TITLE
feature: ctrl-drag files in tree view to copy

### ISSUE THREAD

**Issue by varesa** [atom/tree-view#816]
I think it is standard UX nowdays that dragging a file moves it and ctrl-dragging copies it. It would be great if Atom could do the same.

![](http://i.imgur.com/ASjpdJ0.gif)

**Comment by anderoonies** [comment]
this looks like it could be tacked on pretty painlessly to #793

**Comment by Ben3eeE** [comment]
Is this a duplicate of https://github.com/atom/tree-view/issues/703?

**Comment by 50Wliu** [comment]
Thanks @Ben3eeE.
