### ISSUE TITLE
the gitignored files or folders is not visibility

### ISSUE THREAD

**Issue by openks** [atom/tree-view#818]
yesterday is still ok,today I can't find the gitignored files , i don't know why. Is there anybody can tell me how to show the ignored files and dolders? thanks!
![图片](http://7xl9u9.com1.z0.glb.clouddn.com/%E6%90%9C%E7%8B%97%E6%88%AA%E5%9B%BE_2016-04-21_13-14-11.png)
version:1.7.2

**Comment by Zireael07** [comment]
This is a feature you can control in the tree view settings. Untick the checkbox for 'Hide VCS ignored'
