### ISSUE TITLE
Can not delete folder

### ISSUE THREAD

**Issue by seanmars** [atom/tree-view#820]
Description

Can not delete or move the folder, if the folder have sub-folder and the sub-folder is unfolded.

Steps to Reproduce

Create the folder A;
Create the folder B under A;
Unfold the folder B in the Tree View;
Delete A;
Expected behavior: Delete the folder A and B;

Actual behavior: Get error;

Versions

Atom : 1.7.2
Electron: 0.36.8
Chrome : 47.0.2526.110
Node : 5.1.1
apm 1.9.2
npm 2.13.3
node 0.10.40
python
git 2.7.4.windows.1
visual studio

OS: Windows 7 SP 1

**Comment by Ben3eeE** [comment]
https://github.com/atom/tree-view/issues/259?

**Comment by 50Wliu** [comment]
Thanks.
