### ISSUE TITLE
File in tree view loses focus after renaming.

### ISSUE THREAD

**Issue by lukasoppermann** [atom/tree-view#824]
Hey, when renaming and hitting return to confirm the rename, the focus jumps into a current open file and the tree view loses the focus.

IMO the file in the tree view should keep the focus, so that you can for example open it after renaming it using the return key.

**Comment by ebardajiz** [comment]
Same here. I use heavy keyboard navigation, so it's time consuming to lose focus on the tree view after every rename, especially if there are multiple files you plan on renaming.

I would appreciate the tree keeping focus after renaming too.
