### ISSUE TITLE
Tree view get a white background after update. 

### ISSUE THREAD

**Issue by leozhang2018** [atom/tree-view#829]
Tree view get a white background after update. 
![](http://7xrkio.com1.z0.glb.clouddn.com/2016-05-09%2021-42-15%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by 50Wliu** [comment]
This is most likely a UI theme issue.  If you can still reproduce in safe mode (`atom --safe`) on Atom 1.7.3, please comment here.
