### ISSUE TITLE
Bug! Can't remove folders in non-disk volume

### ISSUE THREAD

**Issue by CaledoniaProject** [atom/tree-view#830]
https://github.com/atom/atom/issues/11716#issuecomment-217895071

**Comment by anderoonies** [comment]
looks like electron handles this [here](https://github.com/electron/electron/blob/e05804848f98959d63337aacd9047cd579c5b23f/atom/common/platform_util_mac.mm#L150)
a stackoverflow post [here](http://stackoverflow.com/questions/18479522/how-to-determine-if-a-volume-supports-trash) references some documentation i can no longer find that mentions that the `trashItemAtURL` method's return code can be used to determine if the file was able to be trashed.

**Comment by CaledoniaProject** [comment]
Interesting, xcode shares the exact same bug ....

**Comment by 50Wliu** [comment]
Closing in favor of #856.
