### ISSUE TITLE
Tree-view toggle doesn't work

### ISSUE THREAD

**Issue by jekoehler** [atom/tree-view#832]
With an open project there is no tree view on the left side. 

Opening Palette with `shift+cmd+P`:
I can not hide and show it with the **tree-view:toggle** command from the Palette. 
This command is not found!

Using `cmd+\` is impossible, because on a macbook I need to press `alt+shift+/` to get `\`

**Comment by 50Wliu** [comment]
This is most likely because the tree-view package has been disabled.  To re-enable it go to Atom > Preferences > Packages > (search for Tree View) and hit `Enable`.  If the problem persists please comment here.

**Comment by adamclark64** [comment]
@50Wliu best way to end to week was finding this out. ![dance-happy-yay-l41lJ8V74Q1dUfAjK](https://media4.giphy.com/media/l41lJ8V74Q1dUfAjK/giphy.gif)

**Comment by AbdulRehmanDevStudio** [comment]
For Mac Click Atom -> config..->  edit config.cson file with 
disabledPackages: [
      "tree-view":true
 ]
then save cmd+s.
Thanks

**Comment by PriyankaSaiprasad** [comment]
@AbdulRehmanDevStudio  I tried editing the "tree-view" :true 
feature in config.cson and now nothing is showing up for Atom at all. When I try to open the app the only option I get is to quit.
