### ISSUE TITLE
Does tree-view support searching filename in sidebar

### ISSUE THREAD

**Issue by hilojack** [atom/tree-view#836]
I'm a vimer, and I usually search filename in tree-view as  the following:
![image](https://cloud.githubusercontent.com/assets/1781999/15279264/099da376-1b55-11e6-8801-c02c1bc92802.png)

Could tree-view support this function?

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/tree-view/issues/159 or #200?

**Comment by 50Wliu** [comment]
Thanks @Ben3eeE.
