### ISSUE TITLE
Very high CPU and Memory usage.

### ISSUE THREAD

**Issue by sagarpanchal** [atom/tree-view#837]
![screenshot from 2016-05-17 14-06-55](https://cloud.githubusercontent.com/assets/6555461/15323918/cc0a70a8-1c61-11e6-9432-ca780610227c.png)

![screenshot from 2016-05-17 14-06-46](https://cloud.githubusercontent.com/assets/6555461/15324005/31076092-1c62-11e6-87d4-69e634428fa2.png)

Memory Usage when Atom is open. Sometimes is occupies more than 2GB RAM, CPU usage gets to high. Leads to frozen system!

**Comment by sagarpanchal** [comment]
![screenshot from 2016-05-17 14-07-13](https://cloud.githubusercontent.com/assets/6555461/15324189/14fcd534-1c63-11e6-895c-3a524b363abf.png)

after killing the process.

**Comment by sagarpanchal** [comment]
![screenshot from 2016-05-17 00-02-51](https://cloud.githubusercontent.com/assets/6555461/15324168/03843202-1c63-11e6-959a-324dbc0a38a9.png)

Packages installed by me

**Comment by sagarpanchal** [comment]
Ubuntu 16.04 64-bit
Atom 1.7.3 64-bit

**Comment by sagarpanchal** [comment]
deleted following files
`/home/sagar/.atom`
`/home/sagar/.cache/Atom`
`/home/sagar/.config/Atom`

removed atom, rebooted system, reinstalled atom, ran it without any third-party packages installed and still when a folder is opened in tree-view cpu usage and memory usage are high and freezes my system.
Also happens with `atom --safe`

So, I disabled `tree-view` package and atom is working great! But, I can't use `tree-view`.

**Comment by sagarpanchal** [comment]
Sorry, but this issue isn't solved after disabling `tree-view` package.
I also tried enabling and disabling several built-in packages one-by-one while running atom with `atom --safe`.
I spend hours to find one built-in package that is causing high cpu and memory usage and now I'm sure that this is caused by `fuzzy-finder` package.

**Comment by sagarpanchal** [comment]
Please, close this issue.

**Comment by 50Wliu** [comment]
Thanks for the update @sagarpanchal.
