### ISSUE TITLE
Provide a more accurate file extension matching through grammars

### ISSUE THREAD

**Issue by Ingramz** [atom/tree-view#838]
Recently I've started to refactor a lot of Blade template files, which have extension `.blade.php`. Renaming such files is slightly inconvenient because if I were to rename a file called `somefile.blade.php`, it would automatically select `somefile.blade` for me, I would quickly start typing and then lose the `.blade` suffix -- this forces me to override the suggested selection or re-type it.

I figured it would be rather neat if we could attempt matching the longest file extension from the available grammars and select the base file name based on that first. If there aren't any matches, then revert to old behavior.

Currently I am leaving this here as an idea, but I might eventually submit a pull request, unless someone else wants to do this.

**Comment by 50Wliu** [comment]
Should be simple given the new `getFullExtension` helper method.

**Comment by Ingramz** [comment]
@50Wliu thank you for mentioning `getFullExtension`, that approach is way simpler. I went ahead and submitted a pull request.
