### ISSUE TITLE
Not all ignored names are hidden

### ISSUE THREAD

**Issue by Stsosz** [atom/tree-view#841]
I have .DS_Store, .Trashes and .fseventsd hidden in the core settings options. I have "hide ignored names" enabled in the Tree View settings. None of my hidden files are hidden. 
![Core Settings](https://cloud.githubusercontent.com/assets/7494858/15438569/c0a98998-1e9a-11e6-8cc3-bbe5e5195d5c.png)
![Tree View Settings](https://cloud.githubusercontent.com/assets/7494858/15438570/c0ac5268-1e9a-11e6-9124-902205ec95eb.png)

**Comment by 50Wliu** [comment]
You're missing a comma after `.Trashes`.  If it still doesn't work after adding the comma, please comment here!
