### ISSUE TITLE
Can't delete any file in tree-view.

### ISSUE THREAD

**Issue by wurde** [atom/tree-view#846]
Any attempt to right-click and remove results in the following error:

![error-gvfs-trash](https://cloud.githubusercontent.com/assets/5455357/15509450/401ad65e-2199-11e6-9d87-aeceefaeff9d.png)

**Comment by wurde** [comment]
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by 50Wliu** [comment]
Is `gvfs-trash` installed?

**Comment by wurde** [comment]
wurde@solace:~$ /usr/bin/gvfs-trash --version
gvfs 1.28.1

**Comment by wurde** [comment]
Fixed. It was a systems problem, I just had to flush the existing trash directory.

**Comment by carloscarcamo** [comment]
I have the same problem, @ghost how did you solve it? any help will be appreciated!

I'm using atom v1.19.6  and node v6.9.1
