### ISSUE TITLE
tree-view cannot enable

### ISSUE THREAD

**Issue by tutumagi** [atom/tree-view#848]
when I open Atom every time. The tree-view state is alway diable.![](http://7xsw3s.com1.z0.glb.clouddn.com/1464159475391)

**Comment by 50Wliu** [comment]
What happens when you press the `Enable` button?  Does everything work correctly in safe mode (`atom --safe`) or when you rename your `~/.atom` folder to `~/.atom-backup`?

**Comment by tutumagi** [comment]
Atom version is `1.7.3`. when i press the `Enable` button. It switches the state. But it still display disable when I restart Atom. I'm on OSX 10.11

**Comment by tutumagi** [comment]
I find the reason. It is caused by the `Nuclide Package`. Look [The issue I created](https://github.com/atom/tree-view/issues/849)
