### ISSUE TITLE
Atom 1.7.3 single click open a permanent  tab not a pending tab

### ISSUE THREAD

**Issue by tutumagi** [atom/tree-view#849]
Atom 1.7.3 single click open a permanent  tab not a pending tab. I search all the web cannot find a solution. And the offical sayed [atom-1-7-and-1-8-beta](http://blog.atom.io/2016/04/12/atom-1-7-and-1-8-beta.html)

> Atom 1.7 brings some changes to the way clicking on files in the tree view behaves, making it easier to select files for operations like renaming and deleting and more closely matching the behavior of other editors.

> If you have pending pane items enabled, then single-clicking an item in the tree view will open the file in pending mode but leave the focus in the tree view; double-clicking the file will switch the file to permanent mode and focus the editor.

**Comment by Ben3eeE** [comment]
Is this what you are looking for https://atom.io/packages/single-click-open?

**Comment by tutumagi** [comment]
In the website,I have checked my setting.The Allow Pendding Item is enable.But the problem is still.

**Comment by tutumagi** [comment]
I find the reason. Because I use the `Nuclide Package`, and the `Nucide Package` provide a feature named `File-Tree`. The `File-Tree` override the `Atom` `Tree-View`. So cause the problem.Haha! I disable the `Nucide-File-Tree-Feature`, then `Atom` works well as I wanted. And it's also the reason cause the [issue](https://github.com/atom/tree-view/issues/848) I created.
