### ISSUE TITLE
Tree view gets focus after switching pane items

### ISSUE THREAD

**Issue by anderoonies** [atom/tree-view#850]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When switching between pane items (cmd+}, cmd+{), focus moves to the tree view.
Disabling tree-view fixes the issue.

### Steps to Reproduce

1. Open two or more tabs
2. Switch to another tab using cmd+}/cmd+{
3. Start typing

**Expected behavior:** Cursor to be in the text buffer and entering text

**Actual behavior:** Focus is on the tree view and the new file dialogue pops up.

### Versions

Atom: 1.7.4

cc @BinaryMuse

**Comment by Ben3eeE** [comment]
I did some tabbing around and I only saw the tree view stealing focus when changing tabs with `pane: show-next-[recently-used]item` or `pane: show-previous-[recently-used]item` when both `Auto Reveal` and `Focus On Reveal` were set to true.

The same focus stealing doesn't happen if you have both set to true and change active pane item in any other way (That I can find). I have no idea what the intended behavior is.

@anderoonies Do you have both these configuration options on? I am using a different OS and keybinding so maybe this is why I can't reproduce in other ways if there are any.

**Comment by anderoonies** [comment]
@Ben3eeE `Auto Reveal` was set to true—sorry for the oversight. that solves it!

**Comment by Ben3eeE** [comment]
@anderoonies We have classified this as a bug in https://github.com/atom/tree-view/issues/858 if you want to subscribe there for updates.
