### ISSUE TITLE
No visual indication when tree view is focused

### ISSUE THREAD

**Issue by wordofchristian** [atom/tree-view#853]
I often use the keyboard shortcut `ctrl-0` to focus the tree view, but it's unfortunate that there is no visual indication that the tree view has been focused. This causes some mental lag and occasional confusion when switching back and forth between editor and tree view frequently.

Is there a way to add this myself through theming?

**Comment by thomasjo** [comment]
Preeeeeetty sure this is strictly related to UI themes, in which case this issue should be re-opened on either of the One UI theme repos (assuming you're using a default theme).

There's a related issue open on one-dark-ui already, which is current blocked by what seems to be a bug in core. See https://github.com/atom/one-dark-ui/issues/75.

/cc @simurai @atom/feedback

**Comment by simurai** [comment]
Yeah, this depends a bit on the theme. The One theme has that blue line to indicate which pane or if the tree-view has focus. But currently removing the line on panes is still blocked by https://github.com/atom/atom/issues/10938. 

You could also style (in your `styles.less` file) the tree-view differently on focus to make it more clear. E.g. make it black:

```css
.tree-view:focus {
  background: black;
}
```

**Comment by wordofchristian** [comment]
Cool, thanks for the help, I'll close this out
