### ISSUE TITLE
Duplicating file with multiple '.'s in the name drops any after the first one.

### ISSUE THREAD

**Issue by cabloo** [atom/tree-view#855]
Ubuntu 14, latest atom and tree view package (as of today).

Reproduce:

- create a file with multiple '.'s, e.g. `list.controller.js`
- select the file in tree view
- copy, then paste.
- file name becomes `list0.controller`.

Issue does not occur when copying to a different folder. It is the component that adds the `0` that is causing the problem.

**Comment by 50Wliu** [comment]
This has already been fixed in Atom 1.9.0.
