### ISSUE TITLE
Failed to move entry .... already exists

### ISSUE THREAD

**Issue by ghost** [atom/tree-view#860]
### Description

Unable to drag-n-drop overwrite a file.
### Steps to Reproduce
1. Pick a file (in my case from the desktop).
2. Drag the file onto the folder structure of an open project.
3. You'll get the following error:

![selection_002](https://cloud.githubusercontent.com/assets/7646510/15610038/41205740-23f1-11e6-9235-2873dd99dc9a.png)

**Expected behavior:** Either automatically overwrites or Atom prompts me to overwrite.

**Actual behavior:** Does nothing.
### Versions

Atom 1.7.4

I have re-opened this issue here based on my report [here](https://github.com/atom/atom/issues/11854).

This occurs for me on both Xubuntu 14.04 and 16.04; I do not believe it's reproducible on a Mac system (based on the report above).

**Comment by fmaclen** [comment]
I'm experiencing the same issue on macOS Sierra 10.12.1.

![image](https://cloud.githubusercontent.com/assets/1434675/20325119/0f85dc0c-ab62-11e6-9eba-d2dae4dd778f.png)

**Comment by Ben3eeE** [comment]
### Steps to Reproduce
1. Pick a file with a filename that already exists in your project.
2. Drag the file onto the folder structure of an open project that contains the same filename
3. You'll get the following error:

![selection_002](https://cloud.githubusercontent.com/assets/7646510/15610038/41205740-23f1-11e6-9235-2873dd99dc9a.png)

![drag already exists](https://cloud.githubusercontent.com/assets/1058982/21463692/1f8354bc-c96d-11e6-8fc6-bd87ff90c10f.gif)

**Comment by mrleblanc101** [comment]
Will this even ship ?
