### ISSUE TITLE
most files not shown

### ISSUE THREAD

**Issue by OJFord** [atom/tree-view#866]
Since updating to Atom 1.8.0, most files in my current open project are not shown.

Some are (.erb, .gitignore, a few exec) but most not (.py, .js, .css, .html).

No luck on restart.

No luck starting atom from the directory as `$ atom ./`.

Interestingly, if the project is open and I run `$ atom path/to/file/in/project` it will bring the editor into focus, open the file, and highlight the folder which contains the file - but still not show the actual filename in the tree.

I'm on OS X 10.11.5 with Atom 1.8.0 and tree-view 0.205.0.

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?  Can you also paste the contents of your `config.cson` file here?  Thanks.

**Comment by OJFord** [comment]
Ah-hah. Checking config.cson I noticed the update seems to have reverted my setting `hideVcsIgnoredFiles: false`.

Resetting that to `false` (show ignored files) fixes the issue (but greys them out as if they're .gitignored).

However, they're not ignored by Git - verified with `git status --ignored` (which as I understand should list files matching .gitignore files even if they have been added and committed).

Reproducible with `--safe`.

**Comment by 50Wliu** [comment]
That's interesting.  What's the contents of your `.gitignore` file?

(Also, you probably accidentally pressed `i` while the Tree View was focused - that toggles the hide setting)

**Comment by OJFord** [comment]
> What's the contents of your .gitignore file?

Non-existent - I tried removing them and it was still an issue.

> you probably accidentally pressed i while the Tree View was focused - that toggles the hide setting

Agh, d'oh! Thanks, I'll disable that shortcut before I do it again 😆

**Comment by 50Wliu** [comment]
Well that's weird...not sure why those files are getting ignored even if there's not a `.gitignore` file.  Is there by chance a `.gitignore` higher up the directory tree?

**Comment by OJFord** [comment]
Nope. Well, there are a couple, but I removed them all to test.

Well, all except `.gitignore_global` actually. That's just logs, locks, swaps, compiled files, etc. though.

**Comment by OJFord** [comment]
Actually, my problems since upgrading to 1.8.0 to numerous to create issues for. I'm using the beta now, which is much more functional for me(!).

For one example - most packages in 1.8.0 seem to not have 'registered' with core; keybindings not working, and nothing for them listed in `cmd+shift+P` - despite them supposedly being enabled.

**Comment by sulliwane** [comment]
pressing ```i``` key when sidebar tree view was focused was the solution for me! my ```node_modules``` as well as other gitignore files show up again (they were hidden before). thanks @50Wliu

**Comment by pmuens** [comment]
Just stumbled upon the same issue. Happened after an update to 1.12.7.

Reverting `hideVcsIgnoredFiles` from `true` to `false` did the trick 👍

**Comment by AndreaGriffiths11** [comment]
@lee-dohm Can you please take a look?

**Comment by lee-dohm** [comment]
@OJFord are you still running into problems or can this be closed?

**Comment by OJFord** [comment]
I'm not currently using Atom. Looks like the others with this issue found fixes, so can be closed as far as I'm concerned, thanks.
