### ISSUE TITLE
tree-view enhancement for many files in a folder. i.e node_modules

### ISSUE THREAD

**Issue by jaunkst** [atom/tree-view#868]
I had the thought today while digging through node_modules that It would be amazing if the folder would display a search filter for its children. 

Maybe it could activate based on child length.

node_modules
 - [search filter box]
 - subfolder
 - subfolder
 - subfolder

Anyways just a thought for developer happiness. I absolutely dread having to open node_modules.

**Comment by Ben3eeE** [comment]
Duplicate of #159 or #200?

**Comment by 50Wliu** [comment]
Yeah, both.  Thanks @Ben3eeE!
