### ISSUE TITLE
.gitignore file not recognized.

### ISSUE THREAD

**Issue by jrbattles** [atom/tree-view#869]
.gitignore file not recognized.

**Comment by 50Wliu** [comment]
Can you please provide more information?  What do you mean that the .gitignore file is not recognized?  What version of Atom is this?  What OS are you using?

**Comment by Pangoraw** [comment]
Hi ! I think he means that the class `.status-ignored` is not being applied anymore to elements listed in the project folder's `.gitignore` file. 

I am on Windows 10, Atom v1.8.0

**Comment by glibsm** [comment]
@50Wliu I believe what he meant is "hide VCS ignored files" is not working correctly. Can reproduce in my environment: all of the sudden the *.pyc build files are showing up in the tree view. 

1.8.0. Atom, OS X.

**Comment by jrbattles** [comment]
I was not able to duplicate the error after I re-installed atom.
