### ISSUE TITLE
git pull seems to cause files to appear as changed

### ISSUE THREAD

**Issue by ryancole** [atom/tree-view#870]
This is something that has only started happening to me within the past month or so. I don't recall it being an issue longer than that.

I frequently work on two different machines. I'll code on one, push up to github, move to the other machine and finally git pull. I'll open up Atom after doing this and now all of the files affected by the git pull appear as modified (not sure if proper term there) in the tree view. Here's a screen shot ...

![change](https://cloud.githubusercontent.com/assets/484801/16136638/e845b208-33f1-11e6-9a06-bee5925beb79.png)

Once I open any of those files, it switches back to the unchanged, normal color. I usually find myself going through and just clicking every file. I'm not sure of another way to resolve this.

I'm on Windows using latest versions of Atom and tree-view. Any ideas?

**Comment by Kenqr** [comment]
I have the same issue when I checkout or merge another branch.
If the affected files are already opened, I'll have to close and reopen them to make them show the correct color.
Colors on tabs are also incorrect.

**Comment by thomasjo** [comment]
@ryancole, @Kenqr are you able to reproduce this in safe mode?

**Comment by trainking** [comment]
@thomasjo safe mode? how to enter?

**Comment by HMUDesign** [comment]
I have the same issue, for a little while, though I cannot recall how long. I too have just added the opening of each file to my workflow... =/

Though it did not occur to me that it is pull-triggered, my experiences support that. I have also noticed that if I make a commit, everything resets properly (even the files that were part of the commit).

**Comment by 50Wliu** [comment]
Closing as it seems like this has been fixed.
