### ISSUE TITLE
Feature request: tree-view vertical split

### ISSUE THREAD

**Issue by bufutda** [atom/tree-view#872]
When working between two projects or two folders and the tree view is long, it is time consuming to constantly scroll between the top and bottom. Please add functionality to vertically split the tree view.

**Comment by AndreaGriffiths11** [comment]
Thanks for the feedback!

We aren't planning on adding this kind of functionality to the Tree View itself. On the other hand, a community package could inject itself into the DOM around the Tree View to achieve a lot of what you're suggesting. We may look into making the [Panels API](https://atom.io/docs/api/latest/Workspace) more powerful in the future, though I don't have any ETA on when that might happen. Keep an eye on the [Atom blog](https://blog.atom.io) for updates!

Thanks again 👍

**Comment by fewspider** [comment]
it is useful feature

**Comment by Xapphire13** [comment]
Is this feature still off the table?

**Comment by 50Wliu** [comment]
We don't have any updates to share, and a community package implementing this approach is still probably the best way forward.
