### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferRow' of undefined

### ISSUE THREAD

**Issue by bsaunder** [atom/tree-view#874]
1. Open Atom
2. Right Click File, Select Duplicate

**Atom Version**: 0.182.0
**System**: linux 4.5.7-200.fc23.x86_64
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.160.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferRow' of undefined

```
At /usr/share/atom/resources/app/node_modules/tree-view/lib/copy-dialog.js:53

TypeError: Cannot read property 'getBufferRow' of undefined
  at /usr/share/atom/resources/app/node_modules/tree-view/lib/copy-dialog.js:53:80
  at WriteStream.<anonymous> (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:280:13)
  at WriteStream.emit (events.js:138:20)
  at fs.js:1731:14
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
  2x -0:06.3 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.5 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v1.0.1
autoclose-html, v0.23.0
autocomplete-plus, v2.2.0
language-asciidoc, v1.4.3
language-puppet, v0.19.1
linter-puppet-lint, v0.6.2
markdown-preview-plus, v2.4.0
pandoc-convert, v1.0.4
pigments, v0.29.2
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@bsaunder According to your command history, you backspaced twice before hitting enter.  Can you share exactly what the filename was originally and after you pressed enter?

**Comment by bsaunder** [comment]
Yea,

The Filename was "dev_statusReport_06_17_16.client.adoc" and i Backspaced
the "17" so the new file name for the Duplicated version would be
"dev_statusReport_06_24_16.client.adoc"

**Comment by Ben3eeE** [comment]
You are running an ancient version of Atom. Would it be possible to update and see if that resolves the problem?

**Comment by 50Wliu** [comment]
Oh jeez, I totally did not notice that Atom version.  @Ben3eeE is correct: could you please try updating to Atom 1.8.0?  If that still doesn't work please comment here and I'll reopen this issue.
