### ISSUE TITLE
Toggle Tree Side - per Atom instance ?

### ISSUE THREAD

**Issue by soren-n** [atom/tree-view#878]
Could not find any information on this issue, but is it possible to have a per Atom instance setting for Toggle Tree Side?

Currently if you have two instances of Atom open and you Toggle Tree Side, the Tree View will swap sides in all open instances of Atom. I have a use case where this is not the preferred behaviour.

It would make it easier to compare projects, here is a mock up:
![screen](https://cloud.githubusercontent.com/assets/1464933/16446146/717d777e-3de6-11e6-9892-93a6486c32a2.png)

**Comment by eduherminio** [comment]
You may want to have a look at [a possible solution](https://discuss.atom.io/t/folder-tree-view-in-the-right-side-of-the-screen/32496/14) I've just been offered in Atom's discuss forum.
Anyway, being able to choose where to place it in every open instance would be an awesome feature to add to Atom.

**Comment by AndreaGriffiths11** [comment]
@lee-dohm Can you please take a look?

**Comment by lee-dohm** [comment]
Thank you for the feedback!

We agree that this would be a useful feature for some workflows. Having per-instance settings isn't a use case that we want to support in a one-off way and per-instance settings also isn't something that is on our radar. For these reasons, I'm going to close this issue. If we implement [per-project settings](https://github.com/atom/atom/issues/5168), which is something we want to eventually do, then I suspect that would be an adequate work-around for this scenario. You may want to subscribe to that issue for updates.

Thanks again for your interest in Atom!
