### ISSUE TITLE
Option: hide when opening a file

### ISSUE THREAD

**Issue by ngryman** [atom/tree-view#885]
Hi,

Would be awesome to have this option out of the box.

![treeview-autohide](https://cloud.githubusercontent.com/assets/892048/16715737/13cccd08-46e9-11e6-9ce2-ea945e77d1c6.gif)

**Comment by ProLoser** [comment]
Is there a package that adds this behavior?

**Comment by 50Wliu** [comment]
@ProLoser https://atom.io/packages/autohide-tree-view sort of does what this issue is asking for.

**Comment by ProLoser** [comment]
Sadly I've found that package to be extremely buggy

**Comment by AndreaGriffiths11** [comment]
@lee-dohm Can you please take a look here.

**Comment by lee-dohm** [comment]
Thanks for the idea 👍 

This isn't something that we are going to be able to work on any time soon. For this reason, I'm going to close this issue. We do believe that it would be a great idea for a community package, as shown by [autohide-tree-view](https://atom.io/packages/autohide-tree-view). Perhaps people interested in this feature can contribute to fixing the bugs with that package?

Thanks again for your passion and interest in Atom!
