### ISSUE TITLE
Clickable expansion icons wrong

### ISSUE THREAD

**Issue by Redsandro** [atom/tree-view#887]
I'm sorry, I don't know what these are called.

![image](https://cloud.githubusercontent.com/assets/1702193/16832630/6b50c722-49ab-11e6-9fc2-4f67ad04e9d5.png)

Version `1.8.0` on Linux Mint 18 (basically Ubuntu 16.04). Note that this used to work.

**Comment by Redsandro** [comment]
![image](https://cloud.githubusercontent.com/assets/1702193/16832732/e8d119cc-49ab-11e6-9108-435046e8ff40.png)

**Comment by simurai** [comment]
Looks like all icons don't show up, not just the arrows in the tree-view.

If you open https://atom.io/packages in Chrome, so you see the "cloud with arrow" icon?

![screen shot 2016-07-15 at 8 58 46 am](https://cloud.githubusercontent.com/assets/378023/16859520/7b6834e6-4a6a-11e6-84d4-88295832a372.png)

It's the same as the Updates icon.

**Comment by Redsandro** [comment]
@simurai Yes. Chome was fine. Making this issue interesting. However, I updated all packages and now the issue is gone. I don't know what caused this, as I believe the icons are atom-related and not package related. And atom does not (yet) (auto-)update on Linux. Still, now the icons show correctly.

Since this makes it hard to reproduce and the solution seems rather simple, I think we might as well close this issue and leave this comment for googling visitors:

__If icons show up kinda like those those _curses_ ASCII drawing symbols `┬║~`, update your packages.__

**Comment by simurai** [comment]
Interesting. Yeah, the Octicons icons come bundled with Atom. Maybe they got overridden by another package. Good to hear it works again.

**Comment by Redsandro** [comment]
@simurai Meanwhile, I have seen this before again and again, always fixed by a restart. However, now, it's still there after restarting. 

But this issue should go to another repository. The icons have the same problem everywhere, like on tabs etc. It's not a tree-view bug.

Any suggestion?

**Comment by simurai** [comment]
Have you tried to use [Safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) `atom --safe`? It will open Atom without any community packages. So it's easier to narrow down the issue.

**Comment by Redsandro** [comment]
@simurai I seem to randomly have this issue after rebooting. Now I cannot recreate it. I'm sure it will happen again and when it does, I will try `--safe` and report back.

**Comment by Redsandro** [comment]
@simurai `--safe` and the problem goes away. It has to be one of the plugins I'm using. I had no idea plugins had the "power" to mess up the entire UI.

**Comment by 50Wliu** [comment]
If you have the package file-icons or file-type-icons installed you might want to report this problem to them.
