### ISSUE TITLE
Double click on a file in the tree opens a file two times.

### ISSUE THREAD

**Issue by PurHur** [atom/tree-view#890]
Double click on a file in the tree opens a file two times. If the file is already opened it only jumps to the old tab. Is this a new "feature" (i cant find any option for that) or a bug?

**Comment by Ben3eeE** [comment]
https://github.com/atom/tree-view/pull/847?

**Comment by 50Wliu** [comment]
This has been fixed and will be available starting in Atom 1.10.0.
