### ISSUE TITLE
Unable to delete file from File Tree

### ISSUE THREAD

**Issue by claudio-b** [atom/tree-view#911]
Hello,

This problem was adressed a lot of times, however it seems after all the updates (current Atom version 1.9.4) I still cannot delete files from file tree.  I want to say my server files are on a USB stick and I only meet this problem when deleting from it (on hard disk works fine).

There is not a problem with permissions as other code editors can delete from it. May I know a solution?

**Comment by Ben3eeE** [comment]
https://github.com/atom/tree-view/issues/856

**Comment by 50Wliu** [comment]
@Claudio-b what version of Atom are you on?

**Comment by claudio-b** [comment]
Version 1.9.4, specified it initially as well. The referred issue in my opinion is similar, but what does it even mean "Recycle Bin" isn't on the USB drive? I mean, I can delete the files with Total Commander or Dreamweaver from the file tree, but not with Atom. Must be more of a bug and less of a configuration error on my operating system.

**Comment by 50Wliu** [comment]
Ugh, sorry, I meant "what operating system are you on"?

**Comment by claudio-b** [comment]
Windows 10 64 bits

**Comment by 50Wliu** [comment]
In that case I'm going to close this in favor of #856.
