### ISSUE TITLE
Cannot set font size

### ISSUE THREAD

**Issue by destenson** [atom/tree-view#914]
I had this problem on windows & never solved it. Now I'm on linux & I want to figure this out. How do you change the size of the text and icons in the tree view?

**Comment by 50Wliu** [comment]
See atom/atom#2530.  There are a few solutions in there.

**Comment by destenson** [comment]
@50Wliu I was unaware of that message board. I will use it instead from now on unless there's a confirmed bug. Thanks. Also adding the following to styles.less was very helpful:

```@font-size: 18px;
html, body, .tree-view, .tab-bar .tab {
  font-size: @font-size;
}```

**Comment by destenson** [comment]
If it's not already, I think you guys should make the existence of that site known prominently, so everyone knows to go there first for answers. It should be everywhere from the github readme.md to the help menu (which, I see it is, but it just says "Community Discussions" which to me screams "social media" and so I stay away from by default.) It would also be great if the questions like these, and their answers were collected into an easily searchable FAQ or something like so that we can get the answer we want quickly. Thanks :+1:

**Comment by 50Wliu** [comment]
Thanks for the feedback - I'll bring it up with the team!
