### ISSUE TITLE
"Show In Finder" cannot be used with Finder replacements

### ISSUE THREAD

**Issue by boneskull** [atom/tree-view#915]
- This issue is Darwin-specific, and likely affects all versions of the OS.  
- Reproduced in v10.11.6 and Atom 1.9.1.
- It's an edge case involving "Finder replacement" applications such as Cocoatech's [Path Finder](http://cocoatech.com/pathfinder/).

On [this line](/atom/tree-view/blob/master/lib/tree-view.coffee#L501), Atom looks for a nonzero exit from the "Show in Finder" command.

`open -R /path/to/file`--or whatever internal service it delegates to--assumes a Finder process is running.  Ultimately, as a command-line executable, `open` should return a non-zero exit code if it's unsuccessful.  In the case of `open -R` anyway, _it doesn't_, which I'd consider a bug in `open`:

``` shell
$ osascript -e 'tell application "Finder" to quit'
$ open -R . || echo 'nonzero!!!'
2016-08-07 14:43:40.727 open[81453:6543036] NSWorkspace received an error while attempting to send a 'mvis' AppleEvent to the Finder. The error was Error Domain=NSOSStatusErrorDomain Code=-600 "procNotFound: no eligible process with specified descriptor" (line 1851)
```

The user experience is that Atom silently fails ([screencast](http://screencast.com/t/zDdvq6jQj9L)) when performing this action.

To fix the above, Atom may want to actually check if Finder is running before executing `open -R`.

But, even if Atom could notify the user, Atom's "Show In Finder" won't work without a running Finder process.

My WAG here is that Atom isn't really interested in maintaining a special case for Path Finder specifically, _but in case it is_, a potential solution is:
- Recent versions of Path Finder ship with [a "helper" app](http://support.cocoatech.com/kb/installation-and-compatibility/reveal-in-path-finder-toolbar-item) to be used in the Finder's toolbar.  This app opens the selected Finder item in Path Finder.
- I'm not sure how this app actually works, but I'm sure there's developer documentation on Apple's site for "how to make a button in the Finder's toolbar".  My guess is that it'd respond to JS run via the `osascript` executable or [npm package](https://www.npmjs.com/package/osascript)).
- If that's the case, it should be scriptable, so the logic might look like:
  1. Check if `process.platform === 'darwin'`
  2. If so, check if Path Finder is running
  3. If so, get the path to the `Path Finder.app` container.
  4. Give `/path/to/Path Finder.app/Contents/Helpers/Reveal.app` the file path via `osascript`, which should cause the file to open in Path Finder.

A _workaround_, which is a likely more digestible solution (but still maybe not digestible), is:
1. Check if `process.platform === 'darwin'`
2. Check if the selected tree item is a directory
3. If the item is a directory, open the item via `open` instead of `open -R`
4. If the item is not a directory, assert Finder is running
5. If Finder is not running, either display error to user OR `open -a Finder` (which, upon failure, exits with a nonzero code), then try `open -R`.  It's improbable Finder would crash before `open -R` is executed.

This would work because `open /path/to/directory` will open `/path/to/directory` in whatever application is the default handler for "directories".  If you have Path Finder installed, this is likely Path Finder.

Another version of this could be:
1. Check if `process.platform === 'darwin'`
2. Check if the selected tree item is a directory
3. If the item is a directory, open the item via `open` instead of `open -R`
4. If the item is not a directory, check for a running `Finder` process via appropriate means
5. If Finder is running, use `open -R` (which should work fine)
6. If Finder is not running, use something like `open dirnameOf(/path/to/file)`

(Another edge case here is that `open /path/to/symlinkTo(some/dir)`, where the symlink crosses filesystem boundaries, seems to _always_ open in Finder; if it isn't running, it will be launched to do so.)

Finally, a better-than-nothing user experience is simply:
1.  Check if `process.platform === 'darwin'`
2.  If Finder isn't running, launch it.
3.  `open -R` the item.

I've likely spent way longer explaining this than it'll take you to close this as "won't fix", but if you are interested in any of these patches, I can probably implement something.  :smile:

**Comment by AndreaGriffiths11** [comment]
@lee-dohm Can you please take a look.

**Comment by lee-dohm** [comment]
Thank you @boneskull for the detailed information :bow: I wish every feature request was this detailed 👏 

My apologies for taking so long to get back to you on this. As you suspected, this isn't something that we are going to be able to take on. On the other hand, it sounds like you have a deep enough understanding of this area that we would be willing to accept a well-crafted pull request for one of your two workaround cases. It might be best if this was built into the Atom or Electron API for all Atom packages to benefit from. (Electron has a `shell.openItem` function now ... I think this tree-view functionality was written before that API was added.) I'm going to close this issue since we use the open issue list as our maintainer team's backlog, but I would be happy to help point people in the right direction for improving this functionality.

Thanks again for your help!
