### ISSUE TITLE
.gitignore files being hidden and no way to allow in file tree

### ISSUE THREAD

**Issue by timothymarois** [atom/tree-view#917]
I know there are many issues with this on the VCS, however it's hiding files from the gitignore just fine. The problem is, I want to display the ignored files. and there is no way to do that in ATOM settings. (unless I've missed it)

**Comment by 50Wliu** [comment]
Settings -> Packages -> search for Tree View -> Settings -> uncheck Hide VCS Ignored Files.

**Comment by timothymarois** [comment]
@50Wliu tried this. Files still hide (even after atom restart)

![screenshot 2016-08-08 18 52 49](https://cloud.githubusercontent.com/assets/2489333/17499117/7a1b5cde-5d99-11e6-86d6-55ecd05d21ef.png)

**Comment by 50Wliu** [comment]
And are they still hidden even in safe mode (`atom --safe`)?  After starting Atom like that you'll have to re-toggle the setting (or press `i` while having the Tree View focused).

**Comment by timothymarois** [comment]
I'm using MacOS, I tried to use the toggle `i` nothing changed, here is a new image that shows its toggled off, the finder shows the directory `cache` but Atom hides it due to the .gitignore. And yes, it's still hidden while in safe mode. 
<img width="957" alt="screenshot 2016-08-09 12 43 44" src="https://cloud.githubusercontent.com/assets/2489333/17525089/460a0d1e-5e2f-11e6-9200-f09211f0cac8.png">

**Comment by lee-dohm** [comment]
I can't replicate this using Atom v1.11.0-dev-5d24bcf on Mac OS X 10.11.5. Do you have a public project where I can replicate the problem @timothymarois?

**Comment by timothymarois** [comment]
For me it happens on all projects that use .gitignore. I'm using Mac OS 10.12 Beta (if that makes any difference) What other information can I provide or give try to troubleshoot? @lee-dohm

**Comment by pierregodard** [comment]
same behavior here, even in safe mode, on `OS X 10.11.6` with:
```
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
Happy to provide more information to help reproducing it. Even with the simplest `.gitignore` with, say, only one line to ignore the `.imdone` folder, the folder disappears from `tree-view` despite `Hide VCS Ignored Files` being unchecked.

**Comment by timothymarois** [comment]
Is there anyway to fast track an update to this? It's starting to prevent me from using Atom in some projects, I have to go back to sublime so I can view and upload these .env files now. @lee-dohm

**Comment by lee-dohm** [comment]
@timothymarois I still can't replicate the problem using Atom v1.9.8 on Mac OS X 10.11.6. The only unique thing you've mentioned so far is that you're on a beta of macOS Sierra, @timothymarois. Can you replicate the problem on a machine that isn't running a beta OS?

**Comment by timothymarois** [comment]
After doing the testing on both OS's, it was still going on, but from @pierregodard got me thinking, and found this guy snug in the `styles.less`

`.tree-view {
  .status-ignored {
    display: none;
  }
}`

Looked to have resolved my issue. thanks again! @lee-dohm

**Comment by ffxsam** [comment]
I'm having the same issue. .gitignore is hiding files in the file tree, nor can I open them via Cmd-T to search for files. The thing is, .gitignore also ignores folders like node_modules which I absolutely do not want Atom/Nuclide to search through.

So I feel like there needs to be a way to hide folders from Atom, but also not ignore/hide whatever I list in .gitignore. Just because I don't want it in git doesn't mean I don't want the ability to edit it.

Atom 1.14.3, Nuclide 0.206.0, Mac OS 10.12.3.

**Comment by ffxsam** [comment]
Actually, I think this setup might work (see below). I'll leave this here in case it helps anyone else stumbling upon this issue.

![image](https://cloud.githubusercontent.com/assets/12532733/23198181/76287112-f87a-11e6-8e74-088b433374ac.png)

**Comment by timothymarois** [comment]
@ffxsam Thanks for that. I'm referencing this again because I reinstalled and now I can't replicate the functionality I once had. This is not an intuitive process. I do not want to see files like ".DS_Store" within my fire tree. I have the default "Ignored Names" set. I've tried to use the CSS listed above to display:none on the status of ignored. However that just does all the files that are listed in my gitignore. Which is not what I want in this case.  "Exclude VCS Ignored Paths" are unchecked, though it does nothing when you flip it on or off. 

**I just want to hide the "Ignored Names" how can I do that?**

**Comment by lee-dohm** [comment]
In the Tree View settings, there are two checkboxes: Hide Ignored Names and Hide VCS Ignored Files ...

1. Launch Atom
1. Open Settings View using <kbd>Cmd+,</kbd> on macOS and <kbd>Ctrl+,</kbd> on other platforms
1. Click the Packages tab on the left of the settings view
1. Enter "tree" in the search box, wait for the search to resolve
1. Click "Settings" in the Tree View package card
1. Scroll down to "Hide Ignored Names" and check the box:

<img width="756" alt="screen shot 2017-07-26 at 9 34 41 am" src="https://user-images.githubusercontent.com/1038121/28632516-b0df910c-71e5-11e7-830c-d473da7b5d75.png">

**Comment by ffxsam** [comment]
If I'm not mistaken, Nuclide disables the Atom `tree-view` package.

**Comment by lee-dohm** [comment]
If you're having problems with Nuclide, you should contact their support: https://nuclide.io/support/

**Comment by ffxsam** [comment]
Nope, no problems! Just wanted to point that out to any Nuclide users who might be confused. Nuclide users should use solely the Nuclide settings to control what the file tree shows/hides.
