### ISSUE TITLE
Group root files

### ISSUE THREAD

**Issue by ReinoutvanKempen** [atom/tree-view#920]
I would like to request a new setting called `Group root files`.

What it should do is hide all files in the root of the project folder and place a folder called `../*projectFolderName*` containing all the files in root below the other folders by default.

This would shorten the tree view in projects with multiple project folders that contain a lot of `.file` files in the root for example. But you can still quickly acces the files, something I would miss if I were to use one of the hide settings to get a similar setup.

**Comment by lee-dohm** [comment]
If I'm understanding you correctly, you want us to create what looks like a folder underneath all the actual folders in the Tree View? And then put all the files from the root of the project directory in that not-actually-a-folder?

**Comment by ReinoutvanKempen** [comment]
Yes, exactly. And it should also behave just like a regular folder.

**Comment by lee-dohm** [comment]
Thanks very much for the suggestion. I've talked it over with the team and this isn't something that we want to invest in. You may want to look into forking the tree-view package to create a modified version that provides this feature.

Thanks again for your ideas and interest in Atom!
