### ISSUE TITLE
Git status color changes for every item in folder when one modified

### ISSUE THREAD

**Issue by octoxan** [atom/tree-view#923]
I'm running version 1.10.0-beta5 (although the issue has been around since 1.10-beta0 I believe). Whenever I modify one file in a folder, it colors the entire folder orange as well as every item in the folder. Does this for me with every repo.

**Comment by 50Wliu** [comment]
Does this happen in safe mode (`atom --safe`)?  What OS are you using?

**Comment by LRego** [comment]
I'm having the same issue, but if I open my atom beta on safe mode everything looks good. I dig a little bit and I find this issue only happens with some themes, with the Material-UI I have the issue of the entire folder get orange but If I change my theme for exemple nucleus-dark everything comes back to normal. This issue only happens on the Atom Beta.

**Comment by octoxan** [comment]
Confirmed what LRego said.

It works fine in atom beta safe mode.. but some themes (like Material-UI) the entire folder goes orange. So I guess maybe this is actually just a Material-UI theme issue?

**Comment by 50Wliu** [comment]
Yeah, this sounds like a theme issue.
