### ISSUE TITLE
Doesn't work rename, copy project path in the main project folder on Windows

### ISSUE THREAD

**Issue by icetee** [atom/tree-view#933]
The project folder (first in tree-view) context menu doesn't work rename and copy project path.

**Reproduction Steps:**

1. Open project
2. Click right-clicked in main project
3. Select rename

**Expected behavior:**

Open toggle and request new file name.

**Observed behavior:**

Nothing happens.

**Screenshots and GIFs**

![window_rename_bug](https://cloud.githubusercontent.com/assets/1855340/18151193/a3a8b9be-6fed-11e6-96f3-a3b6a0019ca8.gif)

![window_projectpath_bug](https://cloud.githubusercontent.com/assets/1855340/18151310/a3c8c37a-6fee-11e6-9f04-ae41e22edc2c.gif)

**Atom version:**
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**OS and version:**
Windows 10 Pro x64

**Installed packages:**

Built-in Atom Packages (90)
├── about@1.5.3
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-grammar-test@0.6.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.44.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.39.0
├── find-and-replace@0.201.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.2
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.2
├── language-csharp@0.12.1
├── language-css@0.37.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.42.1
├── language-html@0.45.1
├── language-hyperlink@0.16.0
├── language-java@0.23.0
├── language-javascript@0.119.0
├── language-json@0.18.2
├── language-less@0.29.5
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.2
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.69.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.56.0
├── language-shellscript@0.22.4
├── language-source@0.9.0
├── language-sql@0.23.0
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.9
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.65.0
├── one-dark-syntax@1.3.0
├── one-dark-ui@1.5.0
├── one-light-syntax@1.3.0
├── one-light-ui@1.5.0
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.241.2
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.47.0
├── symbols-view@0.113.0
├── tabs@0.100.2
├── timecop@0.33.2
├── tree-view@0.208.2
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.33.0
└── wrap-guide@0.38.1

Dev Packages (1) C:\Users\icetee\.atom\dev\packages
└── palladium@0.10.5

Community Packages (36) C:\Users\icetee\.atom\packages
├── atom-beautify@0.29.11
├── atom-css-comb@3.1.0
├── atom-handlebars@1.3.0
├── atom-html-preview@0.1.22
├── atom-live-server@1.2.5
├── autoprefixer@3.2.1
├── build@0.65.0
├── build-gulp@0.11.0
├── build-processing@0.1.2
├── busy@0.6.0
├── copy-filename@1.0.1
├── editorconfig@1.4.1
├── es6-javascript@1.0.0
├── file-icons@1.7.19
├── git-control@0.8.2
├── git-time-machine@1.5.3
├── highlight-bad-chars@1.0.5
├── jshint@1.8.6
├── keyboard-localization@1.4.18
├── language-awk@0.1.11
├── language-babel@2.36.0
├── language-htaccess@0.1.1
├── language-latte@0.3.1
├── language-monkberry@4.0.6
├── language-powershell@2.1.1
├── language-svg@0.9.0
├── language-vue@0.16.0
├── linter@1.11.16
├── linter-sass-lint@1.7.1
├── pigments@0.34.0
├── processing-language@0.2.0
├── quick-highlight@0.5.0
├── sass-autocompile@0.13.0
├── todo-show@1.7.0
├── travis-ci-status@1.2.1
└── vue-autocomplete@0.1.0

└── (empty)

**Additional information:**

* Problem can be reproduced in safe mode: [Yes]
* Problem started happening recently, didn't happen in an older version of Atom: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by Ben3eeE** [comment]
https://github.com/atom/tree-view/issues/179?

**Comment by 50Wliu** [comment]
Thanks.
