### ISSUE TITLE
Blacklist setting for "Hide VCS Ignored Files"

### ISSUE THREAD

**Issue by HyeonuPark** [atom/tree-view#934]
Say, I want to store some user credentials and auth tokens in my project directory. So I made a directory named "tokens" and add it to .gitignore so it will not be published to public github repo.

In this case, I cannot edit my credential files naturally! As it's specified in .gitignore, tree-view just hide this directory, unless I turn-off the "Hide VCS Ignored Files" option and suffering with node_modules directory.

So, It would be nice to add another field in tree-view setting to prevent ignoring directories with certain names. Isn't it?

**Comment by Ben3eeE** [comment]
https://github.com/atom/tree-view/issues/880?

**Comment by HyeonuPark** [comment]
Oh, I missed it
