### ISSUE TITLE
Files not shown

### ISSUE THREAD

**Issue by Deekers** [atom/tree-view#943]
Tree-view .205.0
Platform IDE 1.5.0
OSX 10.11.2

The files in project folder/.pioenvs/megaatmega2560/lib list all the directories in my lib directory that was specified in my platformio.ini file.  The sub-directories though only show the .o files but none of the source files such as .cpp, .c, or .h.

**Comment by damieng** [comment]
What is 'Platform IDE' and platformio.ini ?

**Comment by AndreaGriffiths11** [comment]
[PlatformIO](http://platformio.org/) is a development environment built on top of Atom but has enough separate customizations that they have their own [message board](https://community.platformio.org/). Are you trying to report a problem with PlatformIO or with Atom?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/943#issuecomment-277858366. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
