### ISSUE TITLE
Reveal in Tree View just opens prior Tree View on Windows 10

### ISSUE THREAD

**Issue by harriott** [atom/tree-view#946]
1. Tree view is open on a directory with some of it's files opened in tabs.
2. I use `File > Open Recent` to open a file `faraway` from a separate directory tree.
3. Atom's focus is now on file `faraway`, and then:
   - `right-click in the file's tab > Reveal in Tree View`
   - `Ctrl+Shift+\`
   - `Ctrl+Shift+p > tree-view:reveal-active-file`

\- all just open Tree View where it already is - it is not relocated to the directory of `faraway`.
- `Atom 1.10.2`
- `Windows 10 Home Version 1607 OS Build 14393.105`

This bug reduces Atom on Windows 10 into a one-directory-tree editor.

**Comment by damieng** [comment]
Are you using an extension for 2?  Because Atom has no File > Open Recent by default.

**Comment by AndreaGriffiths11** [comment]
Thank you for contributing!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/946#issuecomment-264251580. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
