### ISSUE TITLE
If renaming a folder while file in that folder open, saving the file will save it in old location

### ISSUE THREAD

**Issue by adamreisnz** [atom/tree-view#948]
I have a file open in the editor, e.g. `some/path/file.js`.
If I rename the folder via tree view to be `some/other-path`, while my file is open, when I then proceed to edit the file again and save it, it will save it as `some/path/file.js`, not realising that the new path for the file is now `some/other-path/file.js`.

This can be rather frustrating, as the new file (in the old location) is created silently, and you're left wondering why your changes aren't appearing/working, until you realise you are editing the wrong file.

Happens on OS X with Atom 1.10.0-dev-98fc8db

**Comment by isherwood** [comment]
This sounds like a workflow issue, and not a bug in Atom. Do other editors track such folder changes?

**Comment by adambuczynski** [comment]
If you rename a folder *through* Atom (Tree view), I would expect that this could be tracked.
I don't need Atom to track if I rename a folder from *outside* of Atom.

**Comment by liuderchi** [comment]
@isherwood I tested on Sublime Text Build3126 (Win7) found it _does not_ track folder changes.
Also saving of previously opened file leads to _error messages_ like 'path not found'

**Comment by adambuczynski** [comment]
I think I would prefer an error as opposed to it just saving the buffer to a new file. I really don't think my workflow is that strange or uncommon.

1) Edit a bunch of files
2) Decide that the folder the files are in should be renamed/moved
3) Click folder in tree view and hit `m` to rename
4) Enter new name, go back to editing files
5) Save edits, boom new files get created in the old location.

I don't think I should be realistically expected to close all my files after I rename a folder within Atom.

In order of preference, a solution for this issue would be for Atom to either:

1) Track when a folder is renamed within Atom tree view, and update the paths of any open buffers accordingly. This would be ideal.

2) Less ideal, but probably better than current situation, detect that the file has moved and show a confirmation dialog when you save it, informing you that the file is no longer present and asking if you want to create the file again or save it under a different path.

**Comment by ungb** [comment]
I am able to repro this with renaming a folder within a project that's open.  This is also somewhat related to https://github.com/atom/tabs/issues/12

**Comment by OmgImAlexis** [comment]
This is definitely a bug as moving said file while editing doesn't cause this.
