### ISSUE TITLE
Only set icon for a particular file type

### ISSUE THREAD

**Issue by greyarch** [atom/tree-view#949]
I would like to be able to set icon class only for one file type. I have a language plugin and I want it to also set the tree view icon for my language files. However, when i provide atom.file-icons service implementation my file type gets the icon I want, but all other file types loose their icons. I return undefined for all other file paths since I do not know what the icon classes should be.

I am using [file-icons package](https://atom.io/packages/file-icons) and it seems that when I provide an atom.file-icons service implementation it stops working nicely with the tree view. 

Is there a way to only provide icon class for a single (or a set of) file paths and have all others rely on the theme?

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

The way the `atom.file-icons` service is designed, it is an all or nothing affair. If you provide a file-icons service, you are expected to provide icons for everything. It was designed specifically with packages similar to [file-icons](https://atom.io/packages/file-icons) in mind. If you want to provide icons only for a specific file type, you may want to look at my [file-type-icons package](https://atom.io/packages/file-type-icons) or earlier versions of file-icons to see how this can be done using CSS. I hope this helps!
