### ISSUE TITLE
Icons not showing if project has too many files.

### ISSUE THREAD

**Issue by gumlym** [atom/tree-view#954]
This is how it looks when there are a lot of files in the project:
![lots_of_files](https://cloud.githubusercontent.com/assets/1327783/19187201/68d8f10a-8c8a-11e6-9854-9eab656c71fa.png)

And this when there are only a few:
![only some files](https://cloud.githubusercontent.com/assets/1327783/19187101/e8ecf342-8c89-11e6-8ac6-206a6b4ca9af.png)

Is this behaviour expected?

**Comment by Ben3eeE** [comment]
Please provide the output of `atom --version` and `apm --version`.
Does this happen in safe mode `atom --safe`?

**Comment by gumlym** [comment]
I dont know what was happening, but its apparently working now, without me doing anything. Hope it doesnt come up again
