### ISSUE TITLE
Ignore file failed

### ISSUE THREAD

**Issue by wsqy** [atom/tree-view#957]
In config.cson:
  "tree-view":
    alwaysOpenExisting: true
    focusOnReveal: false
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true

if  core setting:
    ignoredNames: [
      ".pyc"
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
    ]

BUT~~  *.pyc show  in  tree-vew   yet

**Comment by AndreaGriffiths11** [comment]
@wsqy there was a discussion on [Discuss, the official Atom message board](https://discuss.atom.io/t/ignored-names-still-show-in-tree-view/219/19) with a possible solution to this.

**Comment by AndreaGriffiths11** [comment]
Oops I accidentally posted the wrong linked, here is the [correct link to the solution](https://discuss.atom.io/t/ignored-names-still-show-in-tree-view/219/10?u=andreagriffiths11). I hope that helps.
