### ISSUE TITLE
Move VCS-ignored files and directories to the bottom of the tree

### ISSUE THREAD

**Issue by TylerAckerson** [atom/tree-view#959]
Currently, VCS-ignored files are sorted alphabetically, e.g. resulting in a tree that looks like this:
_.git_
**dist**
_elm-stuff_
_node-modules_
**src**

**Desired behavior:**
- VCS-ignored files are available in the tree and search/finder (i.e. not _hidden_)
- VCS-ignored files are de-prioritized from the tree view and appear below VCS-tracked files

Example from above:
**dist**
**src**
_.git_
_elm-stuff_
_node-modules_

**Atom version**
Atom    : 1.10.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**MAC** OS X Yosemite 10.10.5

**Comment by lee-dohm** [comment]
Thanks for the feedback!

This is an interesting idea and sounds like a great idea for a community package. Since we're not going to be implementing this feature, I'm going to close this issue. Thanks again for the suggestion and for your interest in Atom 👍
