### ISSUE TITLE
Files managed by git-lfs always shown as modified despite clean repository.

### ISSUE THREAD

**Issue by hszhsh** [atom/tree-view#961]
Files managed by git-lfs always shown as modified despite clean repository.

**Comment by AndreaGriffiths11** [comment]
Do you have a public repository using git-lfs that we can use to reproduce this?

**Comment by AndreaGriffiths11** [comment]
@ungb Can you help reproduce this for us?

**Comment by hszhsh** [comment]
It's ok now. I didn't notice it because I had disabled coloring status in tree view since I found this issue.
