### ISSUE TITLE
Blank tree view

### ISSUE THREAD

**Issue by samholmes** [atom/tree-view#962]
![screen shot 2016-10-18 at 3 22 09 pm](https://cloud.githubusercontent.com/assets/517469/19498595/b8d6850e-9546-11e6-9cca-bb9d3619ef5c.png)

**Comment by 50Wliu** [comment]
This should be fixed in the Atom 1.12 betas.

**Comment by jirsbek** [comment]
Sice Atom 1.20 I've started to have the same issue. Sometimes project (Project Manager) starts with the blank Tree View. So far shutting the project and Atom down and restarting the Atom works as a _solution_.

**Comment by KangarooCreativeTeam** [comment]
This has struck me too - thats' why I found this report.  

For me, it's Atom 1.21 where I've seen this (but may have begun on v1.20).

Sometimes it takes multiple restarts.  O_O

Of note; project switching also causes this issue (I'm using Project Manager package).  In this case; I have to activate the project, then restart Atom - which I've set to auto-reopen the last state (/ project) (in the Core Atom settings). 

O_O

**Comment by jirsbek** [comment]
I think I've got the problem solved by disabling **file-icons** plugin. It may have something to do with icons in the tree view.

**Comment by ratmav** [comment]
I ran into this today on 1.21.2 after installing the [golden-ratio](https://github.com/geksilla/atom-golden-ratio) plugin. I had to uninstall the plugin and re-add my project folders, and the project folders then seem to survive a restart. Not sure if it's something the plugin is doing or something that Atom is doing, or both.

**Comment by ArvinB** [comment]
I am having this issue as well, please help

**Comment by SODA110** [comment]
I face the same problem when i use "View/Toggle Tree View". It was empty, but when i drag a file and drop in atom then everything was working fine. May be this help.

**Comment by oliviacheng** [comment]
Hi, this is still happening for me, even when I drag in the projects. 
<img width="1222" alt="Screen Shot 2021-04-20 at 8 00 41 PM" src="https://user-images.githubusercontent.com/56930189/115490523-1e380c00-a213-11eb-976c-d855c04ab132.png">
