### ISSUE TITLE
Fail to install the latest version

### ISSUE THREAD

**Issue by iherman** [atom/tree-view#964]
I get the error message below. My node.js and npm is the most up to date, and I have no problem installing any other atom package...
 
> >> runas@3.1.1 install /Users/ivan/tmp/apm-install-dir-116927-7680-1ob22pp/node_modules/tree-view/node_modules/runas
> > node-gyp rebuild
> 
> /Users/ivan/tmp/apm-install-dir-116927-7680-1ob22pp
> `-- (empty)
> 
> 
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> 
> 
> Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
> 
> 
> 
> 
> 
> Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
> 
> 
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 69
> gyp ERR! stack     at ChildProcess.onExit (/Users/ivan/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Darwin 15.6.0
> gyp ERR! command "/Users/ivan/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/ivan/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
> gyp ERR! cwd /Users/ivan/tmp/apm-install-dir-116927-7680-1ob22pp/node_modules/tree-view/node_modules/runas
> gyp ERR! node -v v4.4.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open '/Users/ivan/tmp/apm-install-dir-116927-7680-1ob22pp/package.json'
> npm WARN apm-install-dir-116927-7680-1ob22pp No description
> npm WARN apm-install-dir-116927-7680-1ob22pp No repository field.
> npm WARN apm-install-dir-116927-7680-1ob22pp No README data
> npm WARN apm-install-dir-116927-7680-1ob22pp No license field.
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/Users/ivan/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/ivan/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ivan/.atom/.apm/.apmrc" "--userconfig" "/Users/ivan/.atom/.apmrc" "install" "/Users/ivan/tmp/d-116927-7680-g11l2x/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
> npm ERR! node v4.4.5
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! runas@3.1.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the runas package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs runas
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls runas
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/ivan/tmp/apm-install-dir-116927-7680-1ob22pp/npm-debug.log
> npm ERR! code 1
>

**Comment by iherman** [comment]
Sorry, I forgot to add: version 0.209.3 was installed and runs, it is an update to the next version that does not...

**Comment by Ben3eeE** [comment]
You are not supposed to manually install bundled packages. That can lead to many problems because the packages may have breaking changes. Please uninstall the tree-view package that you have manually installed and use the version that is bundled with Atom. The upgrade will come when a new version is released with Atom.

**Comment by iherman** [comment]
This error message comes when I get a notification to update the tree-view package in atom (alongside with other, possible updates for other packages) and I just say "update" there. If I am not supposed to do that, why does it appear as a package to be update in the first place?

If I simply disable the tree-view package, then I do not see any possibility to have any 'built-in' tree view, ie, I am not sure anything is bundled with atom... (I run 1.11.2)

**Comment by 50Wliu** [comment]
It is because you may be using a community package that is "helpfully" updating all packages for you, including indeed that shouldn't be.  Run `apm uninstall tree-view` as a fix.
