### ISSUE TITLE
Can't show tree view on two top level atom windows?

### ISSUE THREAD

**Issue by chamons** [atom/tree-view#97]
After I "File->Window", I get a second top level as expected. However, I'm unable to have the tree view appear in the new window.

- Changing tree view location only appears to change the "main" window.
- Double clicking files in tree-view only open in the "main" window
- I'm unable to drag between windows due to (https://github.com/atom/tabs/issues/40)
- File -> opens in the "main" window only.

**Comment by kevinsawicki** [comment]
Closing this out, please comment if you are still seeing this on Atom 1.0.3+, thanks.

**Comment by Datseris** [comment]
Hi, please re-open this. The problem exists for me on latest version.

I open a Second Atom window, but it is impossible to see the Tree View (by going to Toggle Tree View). On the first Atom Window the toggle Tree View works. 

In addition to this problem, when I close Atom with 2 windows, and then re-open Atom, I get 2 windows as expected. However the 2nd Atom Window is completely blank. I think those 2 issues are somehow associated.

**Comment by nexhub** [comment]
I encounter the same problem. Exactly as described by @Datseris .

**Comment by Datseris** [comment]
You mean the problem of a second window not saving its layout?
I think this problem belongs to a different issue.

I said I was going to file a new issue for them, but now I don't know where this is since atom has 10 different github pages with 1000+ issues...

**Comment by nexhub** [comment]
No, I was referring to the first issue. Sry
"Toggle TreeView" in a second Window doesn't work.
