### ISSUE TITLE
Tree-view always disabled by default

### ISSUE THREAD

**Issue by EddyTheDove** [atom/tree-view#972]
Everytime I open a new project, tree-view is disabled by default and it also disable tree-view on every other projects that's opened.

**Comment by 50Wliu** [comment]
Please provide the following information:
* Is your problem reproducible in safe mode (`atom --safe`)?
* What version of Atom are you running (`atom --version`)?
* What OS are you using?
* Have you had Nuclide installed in the past?

If the answers to these questions are not answered within a week your issue risks being closed.

**Comment by EddyTheDove** [comment]
MacOS Sierra 10.12.1
Atom Version 1.11.2
Nuclide is still installed 
`atom --safe` no clue what that is. Sorry. 
Thank you for quick reply

**Comment by 50Wliu** [comment]
Nuclide disables the builtin tree-view in favor of their own version.  If no tree view is showing up please create an issue on the Nuclide repo instead.  Thanks!

https://nuclide.io/docs/editor/uninstall/#re-activate-disabled-core-packages
