### ISSUE TITLE
how to run tests?

### ISSUE THREAD

**Issue by capaj** [atom/tree-view#974]
I was looking at how to run tests that are inside https://github.com/atom/tree-view/tree/master/spec directory but was unable to find any indication on how to run them. How do you run them? Somewhere from atom right?

**Comment by Ben3eeE** [comment]
http://flight-manual.atom.io/hacking-atom/sections/writing-specs/#running-specs

[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
