### ISSUE TITLE
Directories under project folder listed multiple times

### ISSUE THREAD

**Issue by kartagis** [atom/tree-view#977]
I have seen the weirdest thing the other day. Some directories under the project folder are listed multiple times.

![screenshot 2016-10-19 15 40 44](https://cloud.githubusercontent.com/assets/1607518/20088922/229ab30c-a58c-11e6-80a9-f4b19a672c87.png)

**Comment by 50Wliu** [comment]
Hi @kartagis, thanks for reporting.  A few questions:
* Is this reproducible in safe mode (`atom --safe`)?  Is it reproducible at all, or was it just a one-time thing?
* Do the duplicate directories happen with any project folder, or just this specific one?
* What is the output of `atom --version`?

**Comment by kartagis** [comment]
Hello,

- I reproduced the bug with safe mode.
- I've seen it only with this project folder (I wasn't able to add other project folders on shares though)
- The Atom version is 1.11.2

Cheers,

**Comment by Ben3eeE** [comment]
@kartagis 

* Please provide the full output of `atom --version`. It provides more information than just Atom version.
* Is this a project folder on a network share?
* What operating system are you using?
* Can you provide some steps on how you reproduced this in safe mode?

**Comment by kartagis** [comment]
Hello

- Version output is

Atom    : 1.11.2\n Electron: 0.37.8\n Chrome  : 49.0.2623.75\n Node    : 5.10.0

- This project folder is indeed on a network share.
- I am using macOS Sierra
- When I opened Atom in safe more, I removed that project folder, then added it again.

**Comment by lee-dohm** [comment]
@ungb Can you reproduce this and add repro steps?

**Comment by kartagis** [comment]
I can't reproduce this myself. I guess it was an issue with that particular share.

**Comment by lee-dohm** [comment]
Thanks for following up @kartagis. If you can reproduce this in the future, let us know and we'll reopen it 👍
