### ISSUE TITLE
Fixed folder in tree-view

### ISSUE THREAD

**Issue by Si7ius** [atom/tree-view#979]
User should able to block some project folders!

**Comment by 50Wliu** [comment]
Can you elaborate on what you mean by "block"ing the project folder?

**Comment by Si7ius** [comment]
I will explain the problem. I work with many projects. So I choose some project folders to work with. Then I close Atom editor. After that I open some file with Atom editor and it drops my project folders replacing them to opened file directory.

So I want to pin (block) necessary project folders to tree view. Editor can drop other project folders that I did'nt pinned.

**Comment by Ben3eeE** [comment]
In Atom 1.13 we have added a way to reopen recent projects available from the file menu which will let you go back to recent projects more easily.

What you request here is a duplicate of https://github.com/atom/atom/issues/9643 so I am closing this in favor of that issue.
