### ISSUE TITLE
Show/Hide Tree view changes view position in text editor

### ISSUE THREAD

**Issue by xgdgsc** [atom/tree-view#984]
Now when I Show/Hide(Open/Close) Tree view with shortcut `ctrl+\`, the view on the right text editor would change to a new position because of the width change of the editor. I have to scroll up or down to return to where I was.  Is it possible for this operation not change where the editor view is at to improve productivity?

$ atom --version
Atom    : 1.12.2
Electron: 1.4.5
Chrome  : 53.0.2785.113
Node    : 6.5.0

on archlnux.

**Comment by Ben3eeE** [comment]
> Electron: 1.4.5

This is an [unofficial Atom distribution](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md). You should report this issue to the arch linux repository.

**Comment by xgdgsc** [comment]
It also happens on Window 10, atom 1.12.2. It is very obvious with latex files where you have a lot of very long lines and you enable line wrapping.

**Comment by Ben3eeE** [comment]
When I open and close the `tree-view` the TextEditor on the right stays on the same line. Please provide full steps to reproduce the issue you are facing.

**Comment by lee-dohm** [comment]
Thanks for contributing!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/984#issuecomment-260297546. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
