### ISSUE TITLE
Vertical scrollbar appears only because the horizontal scrollbar appears

### ISSUE THREAD

**Issue by jkupczak** [atom/tree-view#987]
Is there a way to prevent this from happening? A scrollbar appears in my tree view allowing me to scroll up and down. The problem is that I don't have enough files/directories open in the tree view for this to be necessary. The only reason it's appearing is because I have long filenames which creates a horizontal scrollbar.

![scrollbars](https://cloud.githubusercontent.com/assets/455221/20330897/a961a7cc-ab56-11e6-8ae1-da5f9f7313b1.png)

**Comment by Ben3eeE** [comment]
@simurai also happens in TextEditors https://github.com/atom/atom/issues/12139
