### ISSUE TITLE
FR: Tree-view with pane capabilities

### ISSUE THREAD

**Issue by i-apellaniz** [atom/tree-view#988]
Hey,

I would like the idea of having pane capabilities into the tree-view. It would be nice to use that empty space at the bottom of the tree-view. At least when the projects don't have many files. 

I think the tree-view should be treated as a normal pane thus we can move, split it etc.

What do you think?

**Comment by AndreaGriffiths11** [comment]
@lee-dohm please take a look at this.

**Comment by lee-dohm** [comment]
Thanks for the feedback!

We aren't planning on adding this kind of functionality to the Tree View itself. On the other hand, a community package could inject itself into the DOM around the Tree View to achieve a lot of what you're suggesting. We may look into making the [Panels API](https://atom.io/docs/api/latest/Workspace) more powerful in the future, though I don't have any ETA on when that might happen. Keep an eye on the [Atom blog](https://blog.atom.io) for updates!

Thanks again 👍
