### ISSUE TITLE
Disabling the tree-view package does not actually disable tree-view.

### ISSUE THREAD

**Issue by nemchik** [atom/tree-view#994]
Like the title says, I have the tree-view package disabled, but the tree-view still shows up all the time and I have to either manually hide it or keep a plugin like hide-tree installed to get the tree-view out of my way.

I NEVER use tree-view for any reason. It's just not for me. For my usage of Atom, tree-view is an annoyance to have to constantly hide because it LOVES to open itself when I open the editor. It seems to appear most often when I have Atom closed and I tell a file to open in Atom and that file was not previously open in atom (via a former session) and the file is in a directory where I do not already have other files from a previous session open. I'm sure there are other factors but that's the best description I can give for now. Point is, with the package disabled, tree-view should not even exist.

For those of us trying to keep Atom as light as possible, having a separate package installed (such as hide-tree) is just extra overhead to accomplish something that should be easily done by just disabling the tree-view package.

**Comment by thomasjo** [comment]
If you actually disable a package, it will still disabled unless you've got a community package installed that actively enables it without your consent. There is no mechanism in Atom core that forcefully enables disabled packages.

Just to make sure we're on the same line here, I'm assuming you've actually *disabled* tree-view, as opposed to merely hidden it. This is not a bug in tree-view, nor Atom core, so I would start by investigating installed community packages to find the culprit.

**Comment by nemchik** [comment]
I did some testing last night, disabled all community packages as well as tree-view and this did not seem to resolve the issue. tree-view remained usable, and as described above if I close Atom and then open a new file via double click Atom will open the file with tree-view visible even though it is disabled.

I will try and look into completely removing Atom and making a fresh install with no community packages or preferences and then test disabling tree-view and I will report my results.

**Comment by nemchik** [comment]
Ok I've found the issue. The seti-ui seems to be forcing tree-view to be enabled. I'll file a bug report with the theme package.
