### ISSUE TITLE
Disable greying out VCS Ignored files

### ISSUE THREAD

**Issue by PranavSathy** [atom/tree-view#999]
I would love to be able to disable `tree-view` from greying out my VCS ignored files as setting. Is this possible?

**Comment by PranavSathy** [comment]
I apologize, for clarity, I mean from "Project Folders" that are really subfolders within a directory where they are ignored, i.e.:

```
project
│   .gitignore (contains subproject)  
│
└───subproject
    │   README.md
    │   main.go
```

If I add "subproject" as a project folder, I would like Tree view to show me modifications within that project even though it is .gitignored further up the directory hierarchy.

**Comment by tsamaya** [comment]
Hi,
check `Atom -> Preferences -> Packages`
then look at `tree-view` settings
uncheck `Hide VCS Ignore Files`
Hope this helps

**Comment by lee-dohm** [comment]
@PranavSathy Showing if something is "modified" only makes sense if there is a way of detecting if something has been modified from some base state. Atom uses Git to make that determination. If a file is ignored by Git, then Atom can't use Git to check if the file has been modified.

Is there something about the problem you're describing here that I'm not understanding?

**Comment by AndreaGriffiths11** [comment]
Thanks for contributing!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/999#issuecomment-269913237. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
